import test from 'node:test';
import assert from 'node:assert/strict';
import {courses,restoreAcademy,answerCourse,startPractice,stepPractice} from '../src/academy.js';
import {createVessel} from '../src/physics.js';
test('4~1급의 세 과목과 사고 대응, 정답·실습 보상 중복 방지',()=>{const b=restoreAcademy();for(const grade of [4,3,2,1]){const list=courses.filter(c=>c.grade===grade);assert.equal(list.length,4);assert.equal(new Set(list.map(c=>c.subject)).size,4);for(const c of list){assert.equal(answerCourse(b,c.id,(c.answer+1)%3),false);assert(!b.passed.includes(c.id));assert(answerCourse(b,c.id,c.answer));answerCourse(b,c.id,c.answer);}}assert.equal(b.passed.length,16);assert.deepEqual(restoreAcademy({passed:['3-cargo','3-cargo','bad'],practiced:['3-cargo','bad']}),{passed:['3-cargo'],practiced:['3-cargo']});assert.deepEqual(restoreAcademy(null),{passed:[],practiced:[]});});
test('조타 실습은 실제 타각 변화와 중앙 복귀가 필요하고 손상 시 리셋',()=>{const s=createVessel(),p=startPractice('4-english',s,1),env={dt:.1,gm:1};assert(!stepPractice(p,s,env));s.rudder=.4;assert(!stepPractice(p,s,env));s.damage=20;assert(!stepPractice(p,s,env));s.damage=0;s.rudder=0;assert(!stepPractice(p,s,env));s.rudder=.4;stepPractice(p,s,env);s.rudder=0;assert(stepPractice(p,s,env));});
test('감속 실습은 실제 고속→감속, 닻 정지·자동항해 제외',()=>{const s=createVessel(),p=startPractice('4-operation',s,1),env={dt:.1,gm:1};s.speed=1;s.throttle=.2;assert(!stepPractice(p,s,env));s.speed=4;stepPractice(p,s,env);s.anchored=true;s.speed=0;assert(!stepPractice(p,s,env));s.anchored=false;s.speed=4;stepPractice(p,s,env);s.speed=1;assert(stepPractice(p,s,env));});
test('레이더 실습은 동일 표적을 8초 추적하며 사라지면 초기화',()=>{const s=createVessel(),p=startPractice('3-operation',s,1),c={id:'tug',kind:'tug',x:100,z:100};for(let i=0;i<7;i++)assert(!stepPractice(p,s,{dt:1,tracked:c}));assert(!stepPractice(p,s,{dt:1,tracked:null}));for(let i=0;i<7;i++)assert(!stepPractice(p,s,{dt:1,tracked:c}));assert(stepPractice(p,s,{dt:1,tracked:c}));});
test('적재 실습은 정박·실제 적재 작업 완료·GM 변화 모두 필요',()=>{const s=createVessel(),p=startPractice('4-cargo',s,1);s.anchored=true;assert(!stepPractice(p,s,{gm:2,dt:1}));assert(!stepPractice(p,s,{gm:1,dt:1,cargoChanged:true}));assert(stepPractice(p,s,{gm:2,dt:0,cargoChanged:true}));});
