import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:960}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto(process.env.VOYAGE_URL||'http://127.0.0.1:5197');await page.locator('#start').click();await expect(page.locator('body')).not.toHaveClass(/bridge-view/);await page.waitForTimeout(1200);await page.screenshot({path:'/tmp/yoonseul-v2-bridge.png'});
await page.locator('#camera-toggle').click();await expect(page.locator('body')).toHaveClass(/bridge-view/);await page.screenshot({path:'/tmp/yoonseul-v2-third.png'});
await page.locator('#motion-readout').click();await page.locator('summary').filter({hasText:'항해사 실습'}).click();await page.locator('[data-preset="low"]').click();await expect(page.locator('#cargo-unit-count')).toHaveText('12 / 18 단위',{timeout:10000});const low=parseFloat(await page.locator('#gm-value').textContent());await page.locator('[data-preset="high"]').click();await expect(page.locator('#handling-info')).toBeHidden({timeout:10000});const high=parseFloat(await page.locator('#gm-value').textContent());expect(high).toBeLessThan(low);await page.screenshot({path:'/tmp/yoonseul-v2-stability.png'});
await page.locator('[data-preset="low"]').click();await expect(page.locator('#handling-info')).toBeHidden({timeout:10000});await page.locator('#close-panel').click();await page.locator('#anchor').click();await page.locator('#motion-readout').click();await expect(page.locator('[data-bay="0"][data-change="1"]')).toBeDisabled();await page.locator('#close-panel').click();await page.locator('#anchor').click();
await page.setViewportSize({width:390,height:844});await page.locator('#camera-toggle').click();await page.waitForTimeout(500);await page.screenshot({path:'/tmp/yoonseul-v2-mobile-bridge.png'});await page.locator('#camera-toggle').click();await page.screenshot({path:'/tmp/yoonseul-v2-mobile-third.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
await page.locator('#menu').click();await page.screenshot({path:'/tmp/yoonseul-v2-mobile-menu.png'});await page.locator('[data-panel="fleet"]').click();for(const id of ['yacht','tanker','bulk','chemical','container']){await page.locator(`[data-ship="${id}"]`).click();await expect(page.locator(`[data-ship="${id}"]`)).toHaveClass(/chosen/);}
await page.locator('#panel-back').click();await page.locator('[data-panel="chart"]').click();await page.locator('[data-region="han"]').click();await page.locator('#close-panel').click();await page.locator('#camera-toggle').click();await page.screenshot({path:'/tmp/yoonseul-v2-yacht.png'});console.log(JSON.stringify({errors,lowGM:low,highGM:high,mobileOverflow:false}));await browser.close();if(errors.length)process.exit(1);
