import test from 'node:test';import assert from 'node:assert/strict';
import {applyImpact,repairTap,repairByCrew,rescueRoute,stepRescue} from '../src/damage.js';
import {createVessel,stepVessel} from '../src/physics.js';import {ships,regions} from '../src/data.js';import {tripSnapshot,restoreTrip} from '../src/trip-save.js';import {emptyCargo} from '../src/stability.js';
test('고속 충돌의 손상이 크고 접촉 중 중복 손상을 제한한다',()=>{const a=createVessel(),b=createVessel();applyImpact(a,2,0);applyImpact(b,15,0);assert(b.damage>a.damage);const old=b.damage;assert.equal(applyImpact(b,15,1),0);assert.equal(b.damage,old);assert.equal(b.speed,0);for(let t=3;t<100;t+=3)applyImpact(b,15,t);assert.equal(b.damage,95);});
test('정지 후 반복 수리로 내구도를 복구하며 과도한 중복 입력은 무시한다',()=>{const s={...createVessel(),damage:48,speed:3};assert(!repairTap(s,0));s.speed=0;assert(repairTap(s,1));assert(!repairTap(s,1.01));for(let i=1;i<7;i++)repairTap(s,1+i*.2);assert.equal(s.damage,0);assert(s.anchored);});
test('심하게 파손되어도 후진은 가능하고 수리 후 정상 추진력을 회복한다',()=>{const s={...createVessel(),damage:95,throttle:-.3};for(let i=0;i<200;i++)stepVessel(s,ships[1],{wind:0},.05,{});assert(s.speed<-.5);repairByCrew(s,20);assert.equal(s.damage,0);});
test('구조정은 육지를 피한 수로로 접근하고 선박 100 m 앞에서 수리를 준비한다',()=>{const s={x:0,z:0,heading:0},ground=(x,z)=>x>60?10:-40,p=rescueRoute(s,[],ground);assert(p);const c={...p[0],rescuePath:p,status:'responding'};for(let i=0;i<600;i++)stepRescue(c,.05);assert.equal(c.status,'assisting');assert(Math.abs(Math.hypot(c.x,c.z)-100)<2);assert.equal(rescueRoute(s,[],()=>10),null);});
test('새로고침해도 선체 손상과 화물을 보존한다',()=>{const region=regions[0],ship=ships[1],cargo=emptyCargo();cargo.bays[0]=2;const s={...createVessel(),damage:63};const result=restoreTrip(tripSnapshot(region,ship,s,cargo,null,null),region,ship);assert.equal(result.state.damage,63);assert.deepEqual(result.cargo,cargo);});

test('수리 복구는 육지·장애물·타선을 피해 전방 수역 확보 후 전진',async()=>{const {recoveryPose,restorePropulsion}=await import('../src/damage.js');const s={...createVessel(),x:0,z:0,heading:Math.PI/2,damage:65,throttle:-.3,anchored:true,rudder:1};const ship=ships.find(s=>s.id==='container'),ground=(x,z)=>x>50?5:-10,contacts=[{kind:'tug',radius:30,x:0,z:-100}];const pose=recoveryPose(s,ship,[{x:70,z:0,radius:35}],ground,contacts);assert(pose);for(let d=0;d<=250;d+=10){const x=pose.x+Math.sin(pose.heading)*d,z=pose.z-Math.cos(pose.heading)*d;assert(ground(x,z)<0);assert(Math.hypot(x,z+100)>90);}const distance=s.distance;assert(restorePropulsion(s,pose));assert.equal(s.damage,0);assert.equal(s.anchored,false);assert.equal(s.throttle,.65);assert.equal(s.rudder,0);assert.equal(s.distance,distance);for(let i=0;i<120;i++)stepVessel(s,ship,{wind:0},.05,{steer:0});assert(s.speed>0);});
test('복구 위치가 없으면 육지로 강제 이동시키지 않는다',async()=>{const {recoveryPose,restorePropulsion}=await import('../src/damage.js');const s=createVessel();assert.equal(recoveryPose(s,ships[0],[],()=>10),null);assert.equal(restorePropulsion(s,null),false);});
