import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1440,height:960}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.addInitScript(()=>localStorage.setItem('yoonseul-save',JSON.stringify({mode:'free',region:'east',ship:'container',trip:{version:1,region:'east',ship:'container',position:{x:0,z:-3500,heading:0},cargo:{bays:[0,0,0,0,0,0],high:false,ballast:false}}})));
await page.goto(process.env.VOYAGE_URL||'http://127.0.0.1:5198/');await page.locator('#start').click();await page.locator('#menu').click();await page.locator('#settings').click();await page.locator('[data-weather="rough"]').click();await page.locator('[data-time="day"]').click();await page.locator('#close-panel').click();
const canvas=page.locator('#ocean canvas');await expect.poll(async()=>Number(await canvas.getAttribute('data-foam')),{timeout:12000}).toBeGreaterThan(10);const anchored=await canvas.getAttribute('data-foam');await page.locator('#throttle').fill('100');await page.locator('#throttle').dispatchEvent('input');await expect.poll(async()=>Number(await page.locator('#speed').textContent()),{timeout:15000}).toBeGreaterThan(25);await expect.poll(async()=>Number(await canvas.getAttribute('data-spray'))).toBeGreaterThan(20);await page.waitForTimeout(1800);await page.screenshot({path:'/tmp/foam-cruise.png'});const cruise=await canvas.evaluate(c=>({...c.dataset}));
await page.locator('#pause').click();const frozen=await canvas.evaluate(c=>({...c.dataset}));await page.waitForTimeout(300);expect(await canvas.evaluate(c=>({...c.dataset}))).toEqual(frozen);await page.locator('#pause').click();
await page.mouse.move(800,400);await page.mouse.down();await page.mouse.move(380,480,{steps:20});await page.mouse.up();await page.waitForTimeout(300);await page.screenshot({path:'/tmp/foam-bow.png'});
await page.locator('#camera-toggle').click();await page.screenshot({path:'/tmp/foam-bridge.png'});await page.setViewportSize({width:390,height:844});await page.locator('#camera-toggle').click();await page.screenshot({path:'/tmp/foam-mobile.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);
await page.reload();await page.locator('#start').click();await page.locator('#menu').click();await page.locator('#settings').click();await page.locator('[data-weather="rough"]').click();await page.locator('#close-panel').click();await page.waitForTimeout(1200);expect(Number(await canvas.getAttribute('data-foam'))).toBeLessThanOrEqual(180);expect(Number(await canvas.getAttribute('data-spray'))).toBeLessThanOrEqual(320);console.log({anchored,cruise,pause:'frozen',mobileBudget:'180 foam / 320 droplets',errors});await browser.close();expect(errors).toEqual([]);
