import test from 'node:test';import assert from 'node:assert/strict';
import {newFishing,castFishing,strikeFishing,stepFishing,newRace,stepRace,restoreLeisure} from '../src/leisure.js';
import {createVessel,stepVessel} from '../src/physics.js';import {ships} from '../src/data.js';
test('입질 전에 챔질할 수 없고 입질을 놓치면 재시도한다',()=>{const f=newFishing(()=>0);castFishing(f,()=>0);assert.equal(strikeFishing(f),false);for(let i=0;i<81;i++)stepFishing(f,.05);assert.equal(f.phase,'bite');for(let i=0;i<81;i++)stepFishing(f,.05);assert.equal(f.phase,'escaped');castFishing(f);assert.equal(f.phase,'waiting');});
test('릴을 계속 감으면 놓치고 장력을 조절하면 물고기를 잡는다',()=>{const f=newFishing();f.phase='bite';strikeFishing(f);f.held=true;for(let i=0;i<100;i++)stepFishing(f,.05);assert.equal(f.phase,'escaped');const g=newFishing();g.phase='bite';strikeFishing(g);for(let i=0;i<700&&g.phase==='reeling';i++){g.held=g.tension<.65;stepFishing(g,.05,()=>.5);}assert.equal(g.phase,'caught');assert.ok(g.catch.length>0);});
test('레이싱은 순서대로 통과하며 빠른 프레임 이동도 감지하고 완주는 한번만 기록한다',()=>{const r=newRace({x:0,z:0});for(let i=0;i<62;i++)stepRace(r,{x:0,z:0},.05);assert.equal(r.phase,'racing');stepRace(r,r.gates[3],.05);assert.equal(r.next,1);r.previous={x:0,z:-140};stepRace(r,{x:0,z:-220},.05);assert.equal(r.next,2);let finished=false;while(r.next<r.gates.length)finished=stepRace(r,r.gates[r.next],.05);assert.ok(finished);assert.equal(stepRace(r,{x:0,z:0},.05),false);});
test('수상오토바이는 5초 안에 빠르게 가속하고 조타가 적용된다',()=>{const s=createVessel(),spec=ships.find(s=>s.id==='jetski');s.throttle=1;for(let i=0;i<100;i++)stepVessel(s,spec,{wind:0,loadFactor:1},.05,{steer:.2});assert.ok(s.speed>20);assert.ok(s.distance>80);assert.ok(s.heading>.1);});
test('어획 기록은 알려진 어종과 크기만 복원하고 길이를 제한한다',()=>{const b=restoreLeisure({fish:[{name:'고등어',length:30},{name:'x',length:30},{name:'농어',length:999}],best:-1});assert.equal(b.fish.length,1);assert.equal(b.best,null);});
test('실제 수상오토바이 물리로 전체 부표 코스를 순서대로 완주할 수 있다',()=>{const r=newRace({x:0,z:0}),s=createVessel(),spec=ships.find(s=>s.id==='jetski');s.anchored=true;for(let i=0;i<62;i++)stepRace(r,s,.05);s.anchored=false;for(let i=0;i<5000&&r.phase!=='finished';i++){const g=r.gates[r.next],a=Math.atan2(g.x-s.x,-(g.z-s.z)),diff=Math.atan2(Math.sin(a-s.heading),Math.cos(a-s.heading));s.throttle=Math.abs(diff)>.5?.4:.85;stepVessel(s,spec,{wind:0,loadFactor:1},.05,{steer:Math.max(-1,Math.min(1,diff*1.7))});stepRace(r,s,.05);}assert.equal(r.phase,'finished');assert.ok(r.elapsed>20&&r.elapsed<150);});
