import test from 'node:test';import assert from 'node:assert/strict';import {courseFeatures,stepRaceFeatures} from '../src/race-course.js';import {newRace} from '../src/leisure.js';
test('코스에는 연속 경계, 점프대와 회피 장애물이 있다',()=>{const f=courseFeatures(newRace({x:0,z:0}).gates);assert.equal(f.rails.length,7);assert.equal(f.ramps.length,2);assert.equal(f.barriers.length,3);});
test('빠르게 점프대에 진입하면 이륙하고 중력으로 착수한다',()=>{const r=newRace({x:0,z:0});r.phase='racing';const s={x:0,z:-94,speed:18,heading:0};r.previous={x:0,z:-85};assert.equal(stepRaceFeatures(r,s,.05),'jump');assert.ok(s.jumpVelocity>0);s.speed=0;for(let i=0;i<100;i++)stepRaceFeatures(r,s,.05);assert.equal(s.jumpHeight,0);});
test('코스 장애물은 접촉 지점에서 정지하고 페널티 대기 중에도 통과하지 않는다',()=>{const r=newRace({x:0,z:0});r.phase='racing';const b=courseFeatures(r.gates).barriers[0],s={x:b.x+20,z:b.z,speed:20,heading:0};r.previous={x:b.x-20,z:b.z};assert.equal(stepRaceFeatures(r,s,.05),'obstacle');assert.equal(r.penalty,2);assert.equal(s.speed,0);assert.ok(s.x<b.x-8);r.previous={x:s.x,z:s.z};s.x=b.x+20;s.speed=20;assert.equal(stepRaceFeatures(r,s,.05),'obstacle');assert.equal(s.speed,0);assert.equal(r.penalty,2);});
import {stepRace} from '../src/leisure.js';
test('결승 아치 앞에 접근하는 것만으로 완주하지 않고 실제 선을 넘어야 한다',()=>{const r=newRace({x:0,z:0});r.phase='racing';r.next=7;const a=r.gates[6],g=r.gates[7],l=Math.hypot(g.x-a.x,g.z-a.z),dx=(g.x-a.x)/l,dz=(g.z-a.z)/l;r.previous={x:g.x-dx*30,z:g.z-dz*30};assert.equal(stepRace(r,{x:g.x-dx*10,z:g.z-dz*10},.05),false);assert.equal(r.phase,'racing');assert.equal(stepRace(r,{x:g.x+dx,z:g.z+dz},.05),true);});
import {createVessel,stepVessel} from '../src/physics.js';import {ships} from '../src/data.js';
test('실제 추진 물리에서도 장애물 앞에서 정지하고 후진하여 벗어난다',()=>{const r=newRace({x:0,z:0}),s=createVessel(),spec=ships.find(s=>s.id==='jetski'),b=courseFeatures(r.gates).barriers[0];r.phase='racing';s.x=b.x;s.z=b.z+12;s.speed=25;s.throttle=1;for(let i=0;i<20;i++){r.previous={x:s.x,z:s.z};stepVessel(s,spec,{wind:0,loadFactor:1},.05,{steer:0});stepRaceFeatures(r,s,.05);}assert.equal(s.speed,0);assert.ok(s.z>b.z+8);const stopped=s.z;for(let i=0;i<40;i++){r.previous={x:s.x,z:s.z};s.throttle=-.3;stepVessel(s,spec,{wind:0,loadFactor:1},.05,{steer:0});stepRaceFeatures(r,s,.05);}assert.ok(s.z>stopped+1);assert.ok(s.speed<0);});

test('두 점프대 모두 방향에 맞춰 진입할 때 이륙한다',()=>{for(const ramp of courseFeatures(newRace({x:0,z:0}).gates).ramps){const r=newRace({x:0,z:0});r.phase='racing';r.previous={x:ramp.x-Math.sin(ramp.heading)*5,z:ramp.z+Math.cos(ramp.heading)*5};const s={x:ramp.x,z:ramp.z,heading:ramp.heading,speed:18};assert.equal(stepRaceFeatures(r,s,.05),'jump');}});
