import test from 'node:test';import assert from 'node:assert/strict';
import {createVessel,stepVessel,waveHeight} from '../src/physics.js';import {ships} from '../src/data.js';
import {sailDrive} from '../src/sailing.js';import {underwaterProfile,localToSea,immersedHeave} from '../src/immersion.js';import {stepAttitude,emptyCargo,stability} from '../src/stability.js';
const yacht=ships.find(s=>s.kind==='yacht');
test('돛을 펼치면 바람으로 가속하고 접으면 추진력이 줄어든다',()=>{const s=createVessel(),env={wind:9,windDirection:Math.PI/2,loadFactor:1};s.sailTarget=1;stepVessel(s,yacht,env,.05,{});assert.ok(s.sailArea>0&&s.sailArea<1);for(let i=0;i<500;i++)stepVessel(s,yacht,env,.05,{});const fast=s.speed;assert.ok(fast>3);assert.equal(s.sailArea,1);s.sailTarget=0;for(let i=0;i<500;i++)stepVessel(s,yacht,env,.05,{});assert.equal(s.sailArea,0);assert.ok(s.speed<fast*.1);});
test('무풍·맞바람에서는 돛 추진이 없고 닻을 내리면 움직이지 않는다',()=>{const s={...createVessel(),sailArea:1,sailTarget:1};assert.equal(sailDrive(s,{wind:0}).speed,0);assert.equal(sailDrive(s,{wind:9,windDirection:Math.PI}).speed,0);s.anchored=true;for(let i=0;i<100;i++)stepVessel(s,yacht,{wind:9,windDirection:Math.PI/2},.05,{});assert.equal(s.speed,0);assert.equal(s.z,100);});
test('요트는 돛을 접은 상태에서도 보조기관과 후진이 가능하다',()=>{const s=createVessel();s.throttle=1;for(let i=0;i<300;i++)stepVessel(s,yacht,{wind:0},.05,{});assert.ok(s.speed>1&&s.speed<3);s.throttle=-.3;for(let i=0;i<300;i++)stepVessel(s,yacht,{wind:9},.05,{});assert.ok(s.speed<0);});
test('선종별 수중 구조가 흘수에 비례하고 프로펠러가 용골보다 위에 있다',()=>{for(const ship of ships.filter(s=>s.kind!=='jetski')){const p=underwaterProfile(ship);assert.equal(p.depth,ship.draft*.7);assert.ok(p.propY+p.propRadius<0);assert.ok(p.propY-p.propRadius>-p.depth);}});
test('롤링·피칭·파도 골에서도 모든 선종 프로펠러 둘레가 잠긴다',()=>{for(const ship of ships.filter(s=>s.kind!=='jetski'))for(let i=0;i<80;i++){const s={x:i*13,z:-i*7,heading:i*.23,roll:Math.sin(i)*.3,pitch:Math.cos(i)*.22,heave:4},p=underwaterProfile(ship),surface=(x,z)=>waveHeight(x,z,i*.4,6),h=immersedHeave(s,ship,surface);for(let k=0;k<12;k++){const a=k*Math.PI/6,v=localToSea(s,Math.sin(a)*p.propRadius,p.propY+Math.cos(a)*p.propRadius,p.propZ);assert.ok(h+v.y<=surface(v.x,v.z)-.1199);}}});
test('화물 적재에 따른 흘수 증가가 선체 높이에 반영된다',()=>{const ship=ships[1],s=createVessel(),cargo={...emptyCargo(),bays:[2,2,2,2,2,2]};for(let i=0;i<1600;i++)stepAttitude(s,ship,cargo,{wave:0},i*.05,.05);assert.ok(Math.abs(s.heave+(stability(ship,cargo).draft-ship.draft*.7))<.01);});
test('수상오토바이 점프를 수중 프로펠러 보정으로 억제하지 않는다',()=>{const s={...createVessel(),heave:2,jumpHeight:4};assert.equal(immersedHeave(s,ships.find(s=>s.kind==='jetski'),()=>0),2);});

import {makeSail,updateSail} from '../src/sail-mesh.js';import {Group} from 'three';
test('돛 천이 바람에 변형되고 접을 때 높이가 줄어도 마스트 가장자리는 고정된다',()=>{const g=new Group();g.add(makeSail(yacht));const s={heading:0,sailArea:1},p=g.getObjectByName('mainsail').geometry.attributes.position;updateSail(g,yacht,s,1,.05,10,.5);const before=p.array.slice();updateSail(g,yacht,s,2,.05,10,.5);assert.ok(p.array.some((x,i)=>Math.abs(x-before[i])>.0001));for(let i=0;i<p.count;i++)if(i%21===0)assert.equal(p.getX(i),0);const full=Math.max(...Array.from({length:p.count},(_,i)=>p.getY(i)));s.sailArea=0;updateSail(g,yacht,s,2,.05,10,.5);assert.ok(Math.max(...Array.from({length:p.count},(_,i)=>p.getY(i)))<full*.05);});
