import test from 'node:test';
import assert from 'node:assert/strict';
import {createTraffic,stepTraffic,trafficAdvisory,routePoint,towEnd,contactSolution} from '../src/traffic.js';
import {clearLeg} from '../src/navigation.js';
test('같은 시드는 재현되고 다른 항차는 항로·위치가 달라진다',()=>{const a=createTraffic({layout:'harbor'},[],42),b=createTraffic({layout:'harbor'},[],42),c=createTraffic({layout:'harbor'},[],43);assert.deepEqual(a,b);assert.notDeepEqual(a.contacts,c.contacts);for(const kind of ['tug','towing','fishing','research','cargo','ferry'])assert(a.contacts.some(c=>c.kind===kind));});
test('타선은 연속 곡선으로 이동하고 작업선은 장비 위치를 지킨다',()=>{const w=createTraffic({layout:'harbor'},[],42),start=w.contacts.map(c=>[c.x,c.z]);for(let i=0;i<600;i++)stepTraffic(w,.05);w.contacts.forEach((c,i)=>{assert(Number.isFinite(c.x+c.z+c.heading+c.vx+c.vz));if(c.site)assert.deepEqual([c.x,c.z],start[i]);else assert(Math.hypot(c.x-start[i][0],c.z-start[i][1])>1);});assert(w.contacts.filter(c=>c.kind==='whale').some(c=>c.depth<0));});
test('선박 교차 접근을 예측하고 먼 배는 경고하지 않는다',()=>{const s={x:0,z:0,heading:0,speed:5};const w={contacts:[{x:100,z:-100,heading:-Math.PI/2,speed:5,radius:20}],hazards:[]};assert(trafficAdvisory(w,s).danger);w.contacts[0].x=1000;assert.equal(trafficAdvisory(w,s),null);});
test('이격 중인 표적의 TCPA를 미래 충돌로 해석하지 않는다',()=>{const s=contactSolution({x:100,z:0,heading:Math.PI/2,speed:5,radius:20},{x:0,z:0,heading:0,speed:0});assert(s.rawTcpa<0);assert(!s.danger);});
test('어구·작업구역과 강의 생태 구분',()=>{const w=createTraffic({layout:'harbor'},[],42);for(const h of w.hazards)assert(trafficAdvisory(w,{x:h.x,z:h.z,heading:0,speed:0}).collision);assert.equal(createTraffic({layout:'river'}).contacts.length,0);assert(w.contacts.some(c=>c.status==='fishing'));assert(w.contacts.some(c=>c.status==='restricted'));});
test('부두와 어구를 가로지르는 순환 항로를 제외한다',()=>{const obs=[{x:-650,z:-1000,radius:400}];for(let seed=0;seed<20;seed++){const w=createTraffic({layout:'harbor'},obs,seed);for(const c of w.contacts.filter(c=>c.rx))for(let i=0;i<64;i++)assert(clearLeg(routePoint(c,i*Math.PI/32),routePoint(c,(i+1)*Math.PI/32),[...obs,...w.hazards],c.radius+30+(c.kind==='towing'?110:0)));}});
test('예인선과 바지선 사이도 충돌 영역이다',()=>{const c=createTraffic({layout:'harbor'},[],42).contacts.find(c=>c.kind==='towing'),end=towEnd(c),own={x:(c.x+end.x)/2,z:(c.z+end.z)/2,heading:0,speed:0};const alert=trafficAdvisory({contacts:[c],hazards:[]},own);assert(alert.collision);assert.equal(alert.kind,'towline');});
test('고래는 정지한 선박을 향해 계속 들어오지 않는다',()=>{const w=createTraffic({layout:'harbor'},[],42),own={x:-346,z:-2366,anchored:false,speed:0};for(let i=0;i<10000;i++){stepTraffic(w,.05,own);for(const c of w.contacts.filter(c=>c.kind==='whale'))assert(Math.hypot(c.x-own.x,c.z-own.z)>c.radius+10);}});

test('정지한 배 앞에서 예인줄과 바지선까지 고려해 일시 정지한다',()=>{const c={id:'tow',kind:'towing',cx:0,cz:0,rx:260,rz:230,phase:0,direction:1,cruise:2.2,radius:32,x:260,z:0,heading:Math.PI,speed:2.2},w={time:0,contacts:[c],hazards:[]},own={x:0,z:300,speed:0,heading:0,anchored:true};let stopped=false;for(let i=0;i<10000;i++){stepTraffic(w,.05,own);const advisory=trafficAdvisory(w,own,10);assert(!advisory?.collision);stopped ||=c.speed===0;}assert(stopped);});

test('정지 선박 옆에서 멀어지는 타선은 계속 진행한다',()=>{const c={id:'departing',kind:'tug',cx:0,cz:0,rx:260,rz:230,phase:0,direction:1,cruise:4,radius:17,x:260,z:0,heading:Math.PI,speed:4},w={time:0,contacts:[c],hazards:[]};stepTraffic(w,.05,{x:260,z:-80,speed:0,anchored:true});assert(c.z>0);assert(c.speed>0);});

test('자동 항해 보조일 때만 접근 타선을 일찍 대기시킨다',()=>{const make=()=>({time:0,hazards:[],contacts:[{id:'tug',kind:'tug',cx:0,cz:0,rx:260,rz:230,phase:0,direction:1,cruise:4,radius:17,x:260,z:0,heading:Math.PI,speed:4}]});const a=make(),b=make(),own={x:260,z:200,speed:5,heading:0};stepTraffic(a,.05,{...own,assisted:true});stepTraffic(b,.05,own);assert.equal(a.contacts[0].speed,0);assert(b.contacts[0].speed>0);});

test('교차 항로가 외해까지 이어지며 위치와 궤적은 연속적이다',()=>{const w=createTraffic({layout:'open'},[],42);assert(w.contacts.filter(c=>c.rx).length>=20);assert(w.contacts.some(c=>Math.hypot(c.x,c.z)>3200));for(let i=0;i<2600;i++){const old=w.contacts.map(c=>({x:c.x,z:c.z}));stepTraffic(w,.05);w.contacts.forEach((c,j)=>{if(c.rx)assert(Math.hypot(c.x-old[j].x,c.z-old[j].z)<1);});}assert(w.contacts.filter(c=>c.rx).every(c=>c.trail.length===40));});
