import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1440,height:960}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
const url=process.env.VOYAGE_URL||'http://127.0.0.1:5197/?trafficSeed=42';
await page.goto(url);await page.locator('#start-training').click();await page.locator('#training-begin').click();
const stored=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('yoonseul-save')).training);
let run=(await stored()).run;expect(run.question.context.distance).toBeGreaterThan(100);await page.locator('#training-number').fill('999');await page.locator('#training-answer').click();await expect(page.locator('.quiz-feedback')).toContainText('다시 생각');await page.locator('#training-number').fill(String(run.question.answer));await page.locator('#training-answer').click();await page.locator('#training-sail').click();await expect(page.locator('#panel-title')).toHaveText('항해도와 해역');await page.locator('#close-panel').click();await page.locator('#training-chip').click();run=(await stored()).run;expect(run.phase).toBe(1);await page.locator('#training-number').fill(String(run.question.answer));await page.locator('#training-answer').click();await page.locator('#close-panel').click();await page.locator('#mission-action').click();await expect(page.locator('#mission-stage')).toContainText('미션');await page.waitForTimeout(3800);await page.locator('#training-chip').click();await page.locator('#training-sail').click();await page.locator('#close-panel').click();await page.locator('#training-chip').click();expect((await stored()).run.phase).toBe(2);console.log('Plan and real loading passed');await page.locator('[data-training-answer="0"]').click();await page.locator('#training-sail').click();await page.locator('#throttle').fill('35');await page.locator('#throttle').dispatchEvent('input');await page.locator('#ocean canvas').click({position:{x:100,y:400}});for(let i=0;i<3;i++)await page.locator('#steering-wheel').press('ArrowRight');await page.waitForTimeout(700);await expect(page.locator('#rudder-value')).toContainText('우현');await page.waitForTimeout(1400);await page.locator('#center-wheel').click();await expect.poll(async()=>(await stored()).run.phase,{timeout:15000}).toBe(3);await page.locator('#training-chip').click();await page.locator('[data-training-answer="1"]').click();await page.locator('#training-sail').click();
const radar=page.locator('#radar'),rect=await radar.boundingBox();
for(const [x,y] of [[.5,.4],[.55,.45],[.45,.45],[.6,.5],[.4,.5],[.5,.55],[.55,.55],[.5,.35],[.6,.4],[.4,.4],[.65,.5],[.35,.5]]){await radar.click({position:{x:rect.width*x,y:rect.height*y}});if(await radar.getAttribute('data-tracked'))break;await page.waitForTimeout(150);}
await expect.poll(async()=>(await stored()).run.phase,{timeout:20000}).toBe(4);console.log('Helm and continuous radar passed');await page.locator('#training-chip').click();await page.locator('[data-training-answer="0"]').click();await page.locator('#training-sail').click();await page.locator('#throttle').fill('20');await page.locator('#throttle').dispatchEvent('input');await expect.poll(async()=>{const damage=Number(await page.locator('#ocean canvas').getAttribute('data-damage'));if(damage>0){console.log('Weather practice contact; exercising repair recovery',damage);if(!await page.locator('#damage-panel').isVisible())await page.locator('#damage-open').click();for(let i=0;i<14&&await page.locator('#repair-tap').isEnabled();i++){await page.locator('#repair-tap').click();await page.waitForTimeout(170);}await page.locator('#throttle').fill('20');await page.locator('#throttle').dispatchEvent('input');}return (await stored()).run.phase;},{timeout:90000,intervals:[1000]}).toBe(5);console.log('Weather and actual speed reduction passed');
await page.locator('#training-chip').click();await page.locator('[data-training-answer="0"]').click();await page.locator('#training-sail').click();await page.locator('#mission-action').click();await page.locator('#time-speed').click();
await expect.poll(async()=>{const damage=Number(await page.locator('#ocean canvas').getAttribute('data-damage'));if(damage>0){console.log('Arrival contact; repair and resume',damage);if(!await page.locator('#damage-panel').isVisible())await page.locator('#damage-open').click();for(let i=0;i<14&&await page.locator('#repair-tap').isEnabled();i++){await page.locator('#repair-tap').click();await page.waitForTimeout(170);}}const action=await page.locator('#mission-action').textContent();if(action==='자동 항해')await page.locator('#mission-action').click();return action;},{timeout:180000,intervals:[1000]}).toBe('하역 시작').catch(async e=>{console.log('Arrival state',await page.locator('#mission-nav').textContent(),await page.locator('#throttle-value').textContent(),await page.locator('#speed').textContent(),await page.locator('#ocean canvas').getAttribute('data-damage'));await page.screenshot({path:'/tmp/training-arrival-failure.png'});throw e;});await page.locator('#mission-action').click();await expect.poll(async()=>(await stored()).run?.status,{timeout:15000}).toBe('review');
await page.locator('#training-chip').click();const review=(await stored()).run.review[0];await page.locator('#training-number').fill(String(review.answer));await page.locator('#training-answer').click();await expect.poll(async()=>(await stored()).log.length).toBe(1);expect((await stored()).xp).toBeGreaterThan(0);
await expect(page.locator('#ocean canvas')).toHaveAttribute('data-model','blender');await page.screenshot({path:'/tmp/training-voyage.png'});
// End-to-end checkpoint and resume preserve actual completed actions and wrong-answer review.
await page.reload();await page.locator('#start').click();await page.locator('#menu').click();await page.locator('[data-panel="training"]').click();expect((await stored()).run).toBe(null);expect((await stored()).log.length).toBe(1);await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/training-mobile.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);console.log({plan:'numeric with wrong-answer review',cargo:'real mission loading and GM review',helm:'actual turn and center',completion:'all six stages, wrong-answer review, saved XP',model:'Blender GLB loaded',errors});await browser.close();expect(errors).toEqual([]);
