export class SeaAudio{
 constructor(){this.active=false;this.volume=.65;this.musicEnabled=true;this.musicVolume=.25;this.ambientHorns=true;this.nextHorn=12;this.lastHorn=-100;this.chord=-1;}
 async toggle(){if(!this.ctx)this.init();await this.ctx.resume();this.active=!this.active;this.master.gain.setTargetAtTime(this.active?this.volume:0,this.ctx.currentTime,.3);return this.active;}
 init(){const ctx=this.ctx=new AudioContext();this.master=ctx.createGain();this.master.gain.value=0;this.master.connect(ctx.destination);const buffer=ctx.createBuffer(1,ctx.sampleRate*6,ctx.sampleRate);const data=buffer.getChannelData(0);let brown=0;for(let i=0;i<data.length;i++){brown=(brown+.03*(Math.random()*2-1))/1.03;data[i]=brown*4;}
 const noise=ctx.createBufferSource();noise.buffer=buffer;noise.loop=true;this.filter=ctx.createBiquadFilter();this.filter.type='lowpass';this.filter.frequency.value=650;this.surf=ctx.createGain();this.surf.gain.value=.45;noise.connect(this.filter).connect(this.surf).connect(this.master);noise.start();
 const windNoise=ctx.createBufferSource();windNoise.buffer=buffer;windNoise.loop=true;this.wind=ctx.createBiquadFilter();this.wind.type='bandpass';this.wind.frequency.value=1400;this.wind.Q.value=.4;const wg=this.windGain=ctx.createGain();wg.gain.value=.3;windNoise.connect(this.wind).connect(wg).connect(this.master);windNoise.start();
 this.engine=ctx.createOscillator();this.engine.type='sine';this.engine.frequency.value=45;this.engineGain=ctx.createGain();this.engineGain.gain.value=0;this.engine.connect(this.engineGain).connect(this.master);this.engine.start();this.harmonic=ctx.createOscillator();this.harmonic.type='triangle';this.harmonicGain=ctx.createGain();this.harmonicGain.gain.value=0;this.harmonic.connect(this.harmonicGain).connect(this.master);this.harmonic.start();
 this.music=ctx.createGain();this.music.gain.value=this.musicEnabled?this.musicVolume:0;this.music.connect(this.master);this.pad=[];for(let i=0;i<4;i++){const voice=ctx.createOscillator(),gain=ctx.createGain();voice.type=i===0?'triangle':'sine';voice.frequency.value=[130.81,164.81,196,293.66][i];gain.gain.value=i===0?.035:.05;voice.connect(gain).connect(this.music);voice.start();this.pad.push(voice);}
 this.hornBus=ctx.createGain();this.hornBus.gain.value=2;this.hornBus.connect(this.master);const impulse=ctx.createBuffer(2,ctx.sampleRate*1.8,ctx.sampleRate);for(let ch=0;ch<2;ch++){const values=impulse.getChannelData(ch);for(let i=0;i<values.length;i++)values[i]=(Math.random()*2-1)*Math.pow(1-i/values.length,3)*.35;}this.reverb=ctx.createConvolver();this.reverb.buffer=impulse;const wet=ctx.createGain();wet.gain.value=.28;this.hornBus.connect(this.reverb).connect(wet).connect(this.master);
 this.nextHorn=ctx.currentTime+12;}
 async soundHorn(length=74){if(!this.active||!this.ctx)return false;await this.ctx.resume();const now=this.ctx.currentTime;if(now-this.lastHorn<4)return false;this.lastHorn=now;this.duckUntil=now+3.5;this.playHorn(length>65?73.42:length>35?110:164.81,false,0);return true;}
 playHorn(base,distant=false,pan=0){const ctx=this.ctx,now=ctx.currentTime,duration=distant?2:3.2,envelope=ctx.createGain(),filter=ctx.createBiquadFilter(),panner=ctx.createStereoPanner();filter.type='lowpass';filter.frequency.value=distant?650:1800;panner.pan.value=pan;envelope.gain.setValueAtTime(0,now);envelope.gain.linearRampToValueAtTime(distant?.05:.42,now+.28);envelope.gain.setValueAtTime(distant?.05:.42,now+duration-.8);envelope.gain.exponentialRampToValueAtTime(.0001,now+duration);envelope.connect(filter).connect(panner).connect(this.hornBus);let ended=0;for(const [ratio,level] of [[1,.6],[1.498,.25],[2,.12]]){const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sawtooth';osc.frequency.setValueAtTime(base*ratio*.985,now);osc.frequency.exponentialRampToValueAtTime(base*ratio,now+.35);gain.gain.value=level;osc.connect(gain).connect(envelope);osc.start(now);osc.stop(now+duration+.1);osc.onended=()=>{osc.disconnect();gain.disconnect();if(++ended===3){envelope.disconnect();filter.disconnect();panner.disconnect();}};}}
 setMusic(enabled){this.musicEnabled=enabled;if(this.ctx)this.music.gain.setTargetAtTime(enabled?this.musicVolume:0,this.ctx.currentTime,.5);}
 setMusicVolume(value){this.musicVolume=Math.max(0,Math.min(1,value));this.setMusic(this.musicEnabled);}
 setAmbientHorns(enabled){this.ambientHorns=enabled;if(this.ctx)this.nextHorn=this.ctx.currentTime+12;}

 update(t,speed,wind,yacht,throttle=0,ambience=true){if(!this.ctx)return;const now=this.ctx.currentTime,velocity=Math.abs(speed),pace=Math.min(1,velocity/15),rpm=Math.min(1,Math.abs(throttle)*.6+pace*.4);
 const chords=[[130.81,164.81,196,293.66],[87.31,130.81,164.81,220],[110,164.81,196,261.63],[98,146.83,196,220]],chord=Math.floor(now/18)%4;if(chord!==this.chord){this.chord=chord;this.pad.forEach((voice,i)=>voice.frequency.setTargetAtTime(chords[chord][i],now,1.8));}
 if(this.active&&ambience&&this.ambientHorns&&now>=this.nextHorn){this.playHorn(65.41+(chord%2)*16.99,true,chord%2?.65:-.65);this.nextHorn=now+48+chord*7;}else if(!ambience||!this.active)this.nextHorn=Math.max(this.nextHorn,now+8);
 const duck=now<(this.duckUntil||0)?.32:1;this.music.gain.setTargetAtTime(this.musicEnabled?this.musicVolume*duck:0,now,.12);
 this.surf.gain.setTargetAtTime((.27+.1*Math.sin(t*.45)+wind*.012+pace*.22)*duck,now,.3);
 this.filter.frequency.setTargetAtTime(500+Math.sin(t*.4)*120+wind*20+pace*1100,now,.3);
 this.wind.frequency.setTargetAtTime(900+wind*35+pace*1900,now,.4);this.windGain.gain.setTargetAtTime((.15+wind*.009+pace*.3)*duck,now,.4);
 this.engine.frequency.setTargetAtTime(32+rpm*68,now,.25);this.engineGain.gain.setTargetAtTime(yacht?0:Math.min(.22,rpm*.22)*duck,now,.25);
 this.harmonic.frequency.setTargetAtTime(64+rpm*136,now,.25);this.harmonicGain.gain.setTargetAtTime(yacht?0:rpm*.06*duck,now,.25);}
 setVolume(v){this.volume=v;if(this.ctx)this.master.gain.setTargetAtTime(this.active?v:0,this.ctx.currentTime,.1);}
}
