import {harborRegions,harborPorts} from './harbor-data.js';
export const ships = [
 {id:'yacht',kind:'yacht',category:'leisure',name:'세일링 요트',en:'Serein 38',type:'곡면 선체 · 티크 갑판 · 세일 리깅',length:17,beam:4.6,mass:1,maxSpeed:13,accel:1.6,turn:0.48,draft:1.8,color:0xe5e6df,cargo:'섬 여행',reward:1200,bridgeY:3,bridgeZ:.24,deck:2.5,features:['티크 갑판','마스트와 스테이','선미 콕핏']},
 {id:'container',kind:'container',category:'cargo',name:'컨테이너선',en:'Blue Horizon',type:'선미 브릿지와 규격화된 컨테이너 셀',length:74,beam:12,mass:5,maxSpeed:22,accel:.7,turn:.19,draft:8,color:0x233e4b,cargo:'컨테이너 운송',reward:4800,bridgeY:12,bridgeZ:.33,deck:3.8,features:['컨테이너 셀 가이드','선미 거주구','라싱 브리지']},
 {id:'tanker',kind:'tanker',category:'cargo',name:'원유 운반선',en:'Amber Tide',type:'배관이 흐르는 낮고 긴 탱크 갑판',length:82,beam:14,mass:7,maxSpeed:16,accel:.45,turn:.12,draft:11,color:0x85392e,cargo:'원유 운송',reward:6200,bridgeY:12,bridgeZ:.34,deck:3.8,features:['화물 매니폴드','갑판 배관','탱크 돔과 통기구']},
 {id:'bulk',kind:'bulk',category:'cargo',name:'벌크선',en:'Terra Maris',type:'대형 해치 커버와 갑판 크레인',length:76,beam:12.8,mass:6,maxSpeed:18,accel:.6,turn:.15,draft:9,color:0x294a40,cargo:'곡물 운송',reward:5200,bridgeY:11,bridgeZ:.34,deck:3.6,features:['해치 커버','갑판 크레인','곡물 화물창']},
 {id:'chemical',kind:'chemical',category:'cargo',name:'케미컬 탱커',en:'Silver Current',type:'독립 탱크와 촘촘한 화물 배관',length:62,beam:10.5,mass:4,maxSpeed:19,accel:.8,turn:.22,draft:7,color:0x50636c,cargo:'화학제품 운송',reward:5600,bridgeY:10,bridgeZ:.33,deck:3.3,features:['독립 탱크 구획','스테인리스 배관','작업용 캣워크']},
 {id:'carcarrier',kind:'carcarrier',category:'cargo',name:'카캐리어 · PCTC',en:'Aurora Drive',type:'자동차를 싣는 다층 차량 운반선',length:80,beam:14.5,mass:6,maxSpeed:19,accel:.55,turn:.14,draft:8.5,color:0xc66630,cargo:'자동차 운송',reward:6500,bridgeY:18,bridgeZ:-.32,deck:4.3,features:['높은 차량갑판','개폐식 선미 램프','차량 승하선'],source:'https://www.walleniusmarine.com/our-services/ship-design-newbuilding/ship-design/hero-class-pctc/',reference:'HERO급 PCTC 구조 참고'},
 {id:'ferry',kind:'ferry',category:'passenger',name:'카페리 · Ro-Pax',en:'Hallyeo Islander',type:'사람과 자동차가 함께 떠나는 항해',length:70,beam:13,mass:4.5,maxSpeed:22,accel:.8,turn:.23,draft:5.8,color:0xe8e9e1,cargo:'여객·차량 수송',reward:4200,bridgeY:15,bridgeZ:-.31,deck:3.4,features:['여객 라운지','선미 차량 램프','구명정과 산책갑판'],source:'https://stenaline.com/about-us/our-ships/stena-estrid/',reference:'Stena E-Flexer 계열 배치 참고'},
 {id:'cruise',kind:'cruise',category:'passenger',name:'크루즈 여객선',en:'Ocean Reverie',type:'발코니와 산책갑판이 이어지는 바다의 호텔',length:100,beam:17,mass:8,maxSpeed:21,accel:.5,turn:.12,draft:8.2,color:0xf0eee4,cargo:'크루즈 기항',reward:6800,bridgeY:21,bridgeZ:-.33,deck:4,features:['계단형 객실 데크','수영장과 선베드','구명정·레이더 돔']},
 {id:'lng',kind:'lng',category:'cargo',name:'LNG 운반선',en:'Polar Sphere',type:'구형 독립 탱크를 가진 Moss형 운반선',length:84,beam:14,mass:6.5,maxSpeed:20,accel:.5,turn:.14,draft:9.8,color:0x334d66,cargo:'LNG 운송',reward:7200,bridgeY:15,bridgeZ:.36,deck:3.8,features:['4기 구형 탱크','탱크 상부 작업대','가스 배관'],source:'https://www.mol.co.jp/en/various-vessels/lng_carrier/',reference:'MOL의 Moss형 LNG선 설명 참고'},
 {id:'tug',kind:'tug',category:'work',name:'항만 예인선',en:'Harbour Guardian',type:'두꺼운 방현재와 낮고 넓은 선체',length:28,beam:10,mass:2,maxSpeed:12,accel:2,turn:.62,draft:4.4,color:0x25373b,cargo:'항만 보급',reward:2200,bridgeY:8,bridgeZ:-.1,deck:2.5,features:['선수 고무 방현재','예인 윈치','소방 모니터'],source:'https://www.damen.com/vessels/tugs/asd-tugs/asd-tug-2813',reference:'Damen ASD Tug 2813 구조 참고'},
 {id:'research',kind:'research',category:'work',name:'해양 조사선',en:'Haeyang Explorer',type:'관측 장비와 연구실을 싣고 떠나는 탐사',length:58,beam:11,mass:3.5,maxSpeed:15,accel:1,turn:.28,draft:5.5,color:0x235e79,cargo:'관측 장비 운송',reward:3900,bridgeY:12,bridgeZ:-.2,deck:3.5,features:['선미 A프레임','관측 장비 갑판','위성 통신 돔'],source:'https://www.kordi.re.kr/lab/sub05_01.do',reference:'KIOST 연구선 장비 구성 참고'},
 {id:'maersk',kind:'container',category:'cargo',name:'머스크 참고형',en:'Nordic Pioneer',type:'선수 브릿지형 컨테이너선 · 비공식 창작선',length:108,beam:17,mass:9,maxSpeed:21,accel:.45,turn:.11,draft:12,color:0x68aabd,cargo:'원양 컨테이너 운송',reward:8200,bridgeY:18,bridgeZ:-.36,deck:5,brand:'MAERSK',features:['머스크 계열 청색 도장','선수 브릿지','후방 컨테이너 갑판'],source:'https://www.maersk.com/news/articles/2024/01/26/maersk-names-first-vessel-of-its-large-methanol-enabled-fleet-ane-maersk',reference:'Ane Mærsk의 선수 브릿지 배치 참고'},
 {id:'ckline',kind:'container',category:'cargo',name:'천경해운 참고형',en:'Sky Coast',type:'동아시아 피더 컨테이너선 · 비공식 창작선',length:60,beam:9.4,mass:3.8,maxSpeed:18,accel:.85,turn:.24,draft:6.5,color:0x263f52,cargo:'근해 컨테이너 운송',reward:4400,bridgeY:10,bridgeZ:.34,deck:3.2,brand:'CK LINE',features:['천경해운 참고 도장','컴팩트한 선미 거주구','피더 컨테이너 갑판'],source:'https://www.ckline.com/en/service/ship/?svslcod=SKH1',reference:'SKY HOPE의 선종·선체 비례 참고'},
 {id:'fishing',kind:'fishing',category:'leisure',name:'바다 낚싯배',en:'Little Tide',type:'작은 선실과 열린 낚시 갑판',length:14,beam:4.5,mass:1.1,maxSpeed:15,accel:1.8,turn:.5,draft:1.2,color:0x36aeb1,cargo:'연안 보급',reward:1200,bridgeY:4,bridgeZ:-.16,deck:1.4,features:['낚시 힐링 모드','낚싯대와 어창','물고기 도감']},
 {id:'jetski',kind:'jetski',category:'leisure',name:'수상오토바이',en:'Wave Runner',type:'곡면 차체와 스포츠 라이더',length:3.6,beam:1.4,mass:.6,maxSpeed:42,accel:3.8,turn:.95,draft:.3,color:0x22b8c1,cargo:'바다 여행',reward:500,bridgeY:1.4,bridgeZ:0,deck:.45,features:['부표 타임 트라이얼','민첩한 코너링','개인 최고 기록']},
];
// Game cruise speed: keep the lower lever range precise; open water gets more pace.
for(const ship of ships){ship.referenceSpeed=ship.maxSpeed;ship.maxSpeed=Math.round(ship.maxSpeed*1.35);}
export const regions = [
 {id:'five',name:'서해 5도',en:'West Sea Islands',label:'백령도 앞바다',lat:37.96,lon:124.68,color:0x176777,seed:12,wave:0.9,depth:35,wind:7.2,ports:['백령도','대청도','소청도','연평도','소연평도'],desc:'다섯 섬 사이, 느리게 흐르는 시간',layout:'islands'},
 {id:'west',name:'서해',en:'West Sea',label:'태안 · 안면도',lat:36.55,lon:126.24,color:0x1f727a,seed:34,wave:0.65,depth:26,wind:5.4,ports:['태안항','안면도','군산항'],desc:'낮은 섬과 금빛 노을의 바다',layout:'islands'},
 {id:'south',name:'남해',en:'South Sea',label:'통영 · 한려수도',lat:34.79,lon:128.38,color:0x127e82,seed:78,wave:0.55,depth:48,wind:4.8,ports:['통영항','비진도','욕지도','거제항'],desc:'푸른 섬을 따라 이어지는 항로',layout:'islands'},
 {id:'east',name:'동해',en:'East Sea',label:'울릉도 앞바다',lat:37.47,lon:130.89,color:0x125582,seed:61,wave:1.45,depth:280,wind:9.1,ports:['울릉도','독도 해역','동해항'],desc:'깊고 푸른 물결, 탁 트인 수평선',layout:'open'},
 {id:'han',name:'한강',en:'Han River',label:'여의도 · 반포',lat:37.52,lon:126.94,color:0x366f77,seed:24,wave:0.16,depth:5,wind:3.1,ports:['여의나루','반포나루','잠실나루'],desc:'도시의 일상에서 잠시 멀어지는 길',layout:'river'},
 {id:'nakdong',name:'낙동강',en:'Nakdong River',label:'을숙도 · 낙동강 하구',lat:35.1,lon:128.94,color:0x387f7b,seed:92,wave:0.22,depth:6,wind:3.8,ports:['을숙도','삼락나루','화명나루'],desc:'갈대와 강바람 사이의 쉼',layout:'river'},
];
regions.push(...harborRegions);
for(const r of regions){r.country??='KR';}
export const weatherPresets={calm:{name:'잔잔한 바다',wave:0.45,wind:0.55},breeze:{name:'산들바람',wave:1,wind:1},rough:{name:'거친 물결',wave:2.4,wind:1.8}};
export function portLocations(region){if(region.layout==='harbor')return harborPorts(region);return region.ports.map((name,i)=>({id:region.id+'-'+i,regionId:region.id,name,x:region.layout==='river'?(i%2?1:-1)*225:Math.sin(i*1.35)*780,z:-300-i*530,berth:(i+1)+'번 작업 수역'}));}
