import * as T from 'three';
import {waveHeight} from './physics.js';
import {hullContacts,advanceDroplet} from './hydrodynamics.js';
let textures=null,users=0;
function acquireTextures(){users++;if(textures)return textures;
 const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d'),image=ctx.createImageData(128,128);
 const hash=(x,y)=>{const v=Math.sin(x*127.1+y*311.7)*43758.5453;return v-Math.floor(v);};
 const noise=(x,y)=>{const ix=Math.floor(x),iy=Math.floor(y),fx=x-ix,fy=y-iy,a=fx*fx*(3-2*fx),b=fy*fy*(3-2*fy);return T.MathUtils.lerp(T.MathUtils.lerp(hash(ix,iy),hash(ix+1,iy),a),T.MathUtils.lerp(hash(ix,iy+1),hash(ix+1,iy+1),a),b);};
 for(let y=0;y<128;y++)for(let x=0;x<128;x++){const r=Math.hypot((x-64)/64,(y-64)/64),cloud=noise(x*.08,y*.08)*.6+noise(x*.23,y*.23)*.3+noise(x*.7,y*.7)*.1;const mask=Math.max(0,1-r*r),lace=T.MathUtils.smoothstep(cloud,.28,.65);image.data.set([224,244,238,Math.round(255*mask*lace)],(y*128+x)*4);}ctx.putImageData(image,0,0);
 const foam=new T.CanvasTexture(c);foam.colorSpace=T.SRGBColorSpace;foam.wrapS=T.RepeatWrapping;
 const d=document.createElement('canvas');d.width=d.height=32;const dc=d.getContext('2d'),g=dc.createRadialGradient(16,16,1,16,16,16);g.addColorStop(0,'#ffffff');g.addColorStop(.35,'#ffffffbb');g.addColorStop(1,'#ffffff00');dc.fillStyle=g;dc.fillRect(0,0,32,32);const spray=new T.CanvasTexture(d);textures={foam,spray};return textures;
}
const patchVertex=`attribute float fade; varying vec2 vUv; varying float vFade; void main(){vUv=uv;vFade=fade;gl_Position=projectionMatrix*modelViewMatrix*instanceMatrix*vec4(position,1.0);}`;
const patchFragment=`uniform sampler2D map; varying vec2 vUv; varying float vFade; void main(){vec4 c=texture2D(map,vUv);gl_FragColor=vec4(.95,1.0,.98,c.a*vFade);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}`;
const sprayVertex=`attribute float size;attribute float opacity;uniform float scale;varying float vAlpha;void main(){vAlpha=opacity;vec4 mv=modelViewMatrix*vec4(position,1.0);gl_PointSize=clamp(size*scale/max(1.0,-mv.z),1.0,32.0);gl_Position=projectionMatrix*mv;}`;
const sprayFragment=`uniform sampler2D map;varying float vAlpha;void main(){gl_FragColor=vec4(.88,.96,.95,texture2D(map,gl_PointCoord).a*vAlpha);\n#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}`;
export class FoamWake{
 constructor(scene,{detail='full'}={}){
  this.scene=scene;this.detail=detail;this.budget=detail==='light'?.22:1;this.history=[];this.patches=[];this.drops=[];this.carry=new Float32Array(12);this.seed=29;this.lastTime=null;this.impact=0;this.slam=0;this.previousBow=null;
  const tex=acquireTextures();this.texture=tex.foam;this.sprayTexture=tex.spray;
  this.meshes=[];for(const side of [-1,0,1]){const geo=new T.BufferGeometry(),pos=new Float32Array(100*6),uv=new Float32Array(100*4),colors=new Float32Array(100*8),indices=[];for(let i=0;i<100;i++){uv.set([i*.13,0,i*.13,1],i*4);if(i<99){const j=i*2;indices.push(j,j+1,j+2,j+1,j+3,j+2);}}geo.setAttribute('position',new T.BufferAttribute(pos,3).setUsage(T.DynamicDrawUsage));geo.setAttribute('uv',new T.BufferAttribute(uv,2));geo.setAttribute('color',new T.BufferAttribute(colors,4).setUsage(T.DynamicDrawUsage));geo.setIndex(indices);const mesh=new T.Mesh(geo,new T.MeshBasicMaterial({map:tex.foam,vertexColors:true,transparent:true,depthWrite:false,side:T.DoubleSide,opacity:.7}));mesh.frustumCulled=false;mesh.renderOrder=2;scene.add(mesh);this.meshes.push({mesh,side});}
  this.maxPatches=detail==='light'?44:innerWidth<700?180:300;this.maxDrops=detail==='light'?56:innerWidth<700?320:620;
  const patchGeo=new T.PlaneGeometry(1,1);patchGeo.setAttribute('fade',new T.InstancedBufferAttribute(new Float32Array(this.maxPatches),1).setUsage(T.DynamicDrawUsage));
  this.surface=new T.InstancedMesh(patchGeo,new T.ShaderMaterial({uniforms:{map:{value:tex.foam}},vertexShader:patchVertex,fragmentShader:patchFragment,transparent:true,depthWrite:false,side:T.DoubleSide}),this.maxPatches);this.surface.instanceMatrix.setUsage(T.DynamicDrawUsage);this.surface.frustumCulled=false;this.surface.renderOrder=3;this.surface.count=0;scene.add(this.surface);this.dummy=new T.Object3D();
  const sprayGeo=new T.BufferGeometry();for(const [name,size]of [['position',3],['size',1],['opacity',1]])sprayGeo.setAttribute(name,new T.BufferAttribute(new Float32Array(this.maxDrops*size),size).setUsage(T.DynamicDrawUsage));
  this.spray=new T.Points(sprayGeo,new T.ShaderMaterial({uniforms:{map:{value:tex.spray},scale:{value:innerHeight*.72}},vertexShader:sprayVertex,fragmentShader:sprayFragment,transparent:true,depthWrite:false}));this.spray.frustumCulled=false;this.spray.renderOrder=4;sprayGeo.setDrawRange(0,0);scene.add(this.spray);
 }
 random(){this.seed=(Math.imul(this.seed,1664525)+1013904223)>>>0;return this.seed/4294967296;}
 reset(){this.history=[];this.patches=[];this.drops=[];this.carry.fill(0);this.propCarry=0;this.lastTime=null;this.lastPosition=null;this.impact=0;this.slam=0;this.previousBow=null;this.surface.count=0;this.spray.geometry.setDrawRange(0,0);for(const {mesh}of this.meshes)mesh.visible=false;}
 dispose(){for(const m of [...this.meshes.map(v=>v.mesh),this.surface,this.spray]){m.removeFromParent();m.geometry.dispose();m.material.dispose();}if(--users===0){textures.foam.dispose();textures.spray.dispose();textures=null;}}
 patch(x,z,t,size,energy=1,vx=0,vz=0){for(let i=this.patches.length-1;i>=Math.max(0,this.patches.length-36);i--){const p=this.patches[i];if(t-p.born<.5&&Math.hypot(p.x-x,p.z-z)<1.5){p.energy=Math.min(.95,p.energy+energy*.15);p.size=Math.max(p.size,size);return;}}if(this.patches.length>=this.maxPatches)this.patches.shift();this.patches.push({x,z,born:t,size,energy,angle:this.random()*Math.PI*2,life:5+this.random()*7,vx,vz});}
 droplet(c,s,t,force=false){if(this.drops.length>=this.maxDrops){if(force)this.drops.shift();else return;}const energy=c.energy,r=this.random();this.drops.push({x:c.x+c.nx*.3,y:c.y+.12,z:c.z+c.nz*.3,vx:c.nx*(.8+energy*2.5)+Math.sin(s.heading)*(s.speed||0)*.15,vz:c.nz*(.8+energy*2.5)-Math.cos(s.heading)*(s.speed||0)*.15,vy:1+energy*(1.3+r*2.2),age:0,life:1.1+energy*.45,size:.08+r*.18});}
 update(s,spec,t,strength){
  let dt=this.lastTime===null?1/60:Math.max(0,Math.min(.05,t-this.lastTime));this.lastTime=t;
  const moved=this.lastPosition?Math.hypot(s.x-this.lastPosition.x,s.z-this.lastPosition.z):0;
  if(moved>Math.max(500,spec.length*5)){this.reset();this.lastTime=t;dt=0;}
  this.lastPosition={x:s.x,z:s.z};const speed=moved>.0001?s.speed||0:0,pace=T.MathUtils.clamp(Math.abs(speed)/15,0,1.5),cs=Math.cos(s.heading),sn=Math.sin(s.heading);
  const contacts=hullContacts({...s,speed},spec,t,strength),peak=Math.max(...contacts.map(c=>c.entry));this.impact=T.MathUtils.lerp(this.impact,peak,1-Math.exp(-dt*8));this.slam*=Math.exp(-dt*3);
  const bow=contacts[0];if(this.previousBow!==null&&this.previousBow>.25&&bow.clearance<=.25&&bow.closing>1&&Math.abs(speed)>2){this.slam=Math.min(1,bow.closing*.2);for(const c of contacts.slice(0,4)){this.patch(c.x+c.nx,c.z+c.nz,t,1+spec.beam*.2,.95,c.nx*2,c.nz*2);for(let j=0;j<Math.ceil(18*this.budget*this.slam);j++)this.droplet({...c,energy:c.energy+this.slam},s,t,true);}}this.previousBow=bow.clearance;
  for(let k=0;k<contacts.length;k++){const c=contacts[k],rate=(c.entry*13+c.flow*10)*this.budget;this.carry[k]+=rate*dt;let count=Math.min(5,Math.floor(this.carry[k]));this.carry[k]-=count;while(count-->0){this.patch(c.x+c.nx*.4,c.z+c.nz*.4,t,.65+spec.beam*.10+c.energy*.8,Math.min(.9,.3+c.energy*.4),c.nx*(.3+c.energy*.4),c.nz*(.3+c.energy*.4));if(c.energy>.15)for(let j=0;j<(this.detail==='light'?2:5);j++)this.droplet(c,{...s,speed},t);}}
  this.propCarry=(this.propCarry||0)+dt*this.budget*(pace*11+(!s.anchored&&moved>.0001?Math.abs(s.throttle||0)*9:0));while(this.propCarry>=1){this.propCarry--;const width=(this.random()-.5)*spec.beam*.65,back=spec.length*.48;this.patch(s.x-sn*back+cs*width,s.z+cs*back+sn*width,t,spec.beam*(.3+this.random()*.2),.7,-sn*pace*2,cs*pace*2);}
  const last=this.history[0];if(Math.abs(speed)>.15&&(!last||moved>0&&Math.hypot(last.x-s.x,last.z-s.z)>2+pace*2)){this.history.unshift({x:s.x,z:s.z,h:s.heading+(speed<0?Math.PI:0),born:t,pace});if(this.history.length>100)this.history.pop();}this.history=this.history.filter(q=>t-q.born<22);
  for(const {mesh,side}of this.meshes){mesh.visible=this.history.length>2;const p=mesh.geometry.attributes.position,color=mesh.geometry.attributes.color;let distance=0;for(let i=0;i<100;i++){const q=this.history[Math.min(i,this.history.length-1)];if(!q)continue;if(i>0&&i<this.history.length)distance+=Math.hypot(q.x-this.history[i-1].x,q.z-this.history[i-1].z);const age=t-q.born,width=spec.beam*(side===0?.45:.20)+distance*.035,offset=side*(spec.beam*.35+distance*.19),alpha=i<this.history.length?Math.max(0,1-age/22)*(1-i/100)*Math.min(1,q.pace)*.8:0;for(let e=0;e<2;e++){const across=offset+(e-.5)*width,x=q.x-Math.sin(q.h)*spec.length*.45+Math.cos(q.h)*across,z=q.z+Math.cos(q.h)*spec.length*.45+Math.sin(q.h)*across;p.setXYZ(i*2+e,x,waveHeight(x,z,t,strength)+.10,z);color.setXYZW(i*2+e,.86,.97,.94,alpha);}}p.needsUpdate=color.needsUpdate=true;}
  const survivors=[];for(const p of this.drops){if(dt>0&&advanceDroplet(p,dt,t,strength)){if(this.random()<.2)this.patch(p.x,p.z,t,.4+p.size*3,.28,p.vx*.08,p.vz*.08);}else if(p.age<p.life)survivors.push(p);}this.drops=survivors;
  const attributes=this.spray.geometry.attributes;this.drops.forEach((p,i)=>{attributes.position.setXYZ(i,p.x,p.y,p.z);attributes.size.setX(i,p.size);attributes.opacity.setX(i,Math.min(1,p.age*15)*Math.max(0,1-p.age/p.life)*.85);});for(const a of Object.values(attributes))a.needsUpdate=true;this.spray.geometry.setDrawRange(0,this.drops.length);this.spray.material.uniforms.scale.value=innerHeight*.72;
  this.patches=this.patches.filter(p=>t-p.born<p.life);const fades=this.surface.geometry.attributes.fade;this.patches.forEach((p,i)=>{const age=t-p.born;p.x+=p.vx*dt;p.z+=p.vz*dt;p.vx*=Math.exp(-dt*.5);p.vz*=Math.exp(-dt*.5);this.dummy.position.set(p.x,waveHeight(p.x,p.z,t,strength)+.12,p.z);this.dummy.rotation.set(-Math.PI/2,0,p.angle);const spread=p.size*(1+age*.18);this.dummy.scale.set(spread*1.5,spread,1);this.dummy.updateMatrix();this.surface.setMatrixAt(i,this.dummy.matrix);fades.setX(i,p.energy*Math.min(1,age*9)*Math.pow(1-age/p.life,1.4));});this.surface.count=this.patches.length;this.surface.instanceMatrix.needsUpdate=true;fades.needsUpdate=true;
 }
}
