import * as T from 'three';
import {waveHeight} from './physics.js';
// World-space ribbons keep the wake behind the ship through a turn.
export class FoamWake{
 constructor(scene){this.history=[];this.intensity=0;const c=document.createElement('canvas');c.width=128;c.height=64;const ctx=c.getContext('2d'),image=ctx.createImageData(128,64);let seed=17;for(let y=0;y<64;y++)for(let x=0;x<128;x++){seed=(seed*1664525+1013904223)>>>0;const a=(seed/4294967296)*Math.sin(y/64*Math.PI);const i=(y*128+x)*4;image.data.set([220,241,233,Math.round(a*190)],i);}ctx.putImageData(image,0,0);this.texture=new T.CanvasTexture(c);this.texture.wrapS=this.texture.wrapT=T.RepeatWrapping;this.texture.repeat.set(3,1);this.meshes=[];for(let side=-1;side<=1;side++){const geo=new T.BufferGeometry(),pos=new Float32Array(100*6),uv=new Float32Array(100*4),indices=[];for(let i=0;i<100;i++){uv.set([i/99,0,i/99,1],i*4);if(i<99){let j=i*2;indices.push(j,j+1,j+2,j+1,j+3,j+2);}}geo.setAttribute('position',new T.BufferAttribute(pos,3));geo.setAttribute('uv',new T.BufferAttribute(uv,2));geo.setIndex(indices);const m=new T.Mesh(geo,new T.MeshBasicMaterial({map:this.texture,transparent:true,opacity:side===0?.25:.5,depthWrite:false,side:T.DoubleSide}));m.frustumCulled=false;scene.add(m);this.meshes.push({mesh:m,side});}
 const dot=document.createElement('canvas');dot.width=dot.height=32;const dc=dot.getContext('2d'),gradient=dc.createRadialGradient(16,16,0,16,16,16);gradient.addColorStop(0,'#ffffff');gradient.addColorStop(.3,'#ffffffaa');gradient.addColorStop(1,'#ffffff00');dc.fillStyle=gradient;dc.fillRect(0,0,32,32);this.sprayTexture=new T.CanvasTexture(dot);const sprayGeo=new T.BufferGeometry();sprayGeo.setAttribute('position',new T.BufferAttribute(new Float32Array(96*3),3));this.spray=new T.Points(sprayGeo,new T.PointsMaterial({map:this.sprayTexture,color:0xe0f4f1,size:1.2,transparent:true,opacity:0,depthWrite:false}));this.spray.frustumCulled=false;scene.add(this.spray);}

 dispose(){for(const {mesh} of this.meshes){mesh.removeFromParent();mesh.geometry.dispose();mesh.material.dispose();}this.texture.dispose();this.spray.removeFromParent();this.spray.geometry.dispose();this.spray.material.dispose();this.sprayTexture.dispose();}
 reset(){this.history=[];this.intensity=0;this.spray.visible=false;}
 update(s,spec,t,strength){const pace=T.MathUtils.clamp(Math.abs(s.speed)/15,0,1);this.intensity=T.MathUtils.lerp(this.intensity,pace,.08);const last=this.history[0];if(!last||Math.hypot(last.x-s.x,last.z-s.z)>2+pace*2){this.history.unshift({x:s.x,z:s.z,h:s.heading});if(this.history.length>100)this.history.pop();}for(const {mesh,side} of this.meshes){mesh.visible=this.history.length>2&&this.intensity>.015;mesh.material.opacity=(side===0?.2:.35)+this.intensity*.35;const p=mesh.geometry.attributes.position;for(let i=0;i<100;i++){const q=this.history[Math.min(i,this.history.length-1)];if(!q)continue;const width=spec.beam*(.42+pace*.15)+i*.18,offset=side*(spec.beam*.43+i*.55),stern=spec.length*.43;for(let edge=0;edge<2;edge++){const across=offset+(edge-.5)*width;const x=q.x-Math.sin(q.h)*stern+Math.cos(q.h)*across,z=q.z+Math.cos(q.h)*stern+Math.sin(q.h)*across;p.setXYZ(i*2+edge,x,waveHeight(x,z,t,strength)+.18,z);}}p.needsUpdate=true;}
 this.spray.visible=s.speed>2;this.spray.material.opacity=pace*.6;this.spray.material.size=.5+pace;const p=this.spray.geometry.attributes.position,cs=Math.cos(s.heading),sn=Math.sin(s.heading);for(let i=0;i<96;i++){const age=(t*(2+pace)+i*.618033)%1,side=i%2?1:-1,x=side*(spec.beam*.28+age*(1+pace*4)),z=-spec.length*.42+age*(4+pace*8),wx=s.x+cs*x-sn*z,wz=s.z+sn*x+cs*z;p.setXYZ(i,wx,waveHeight(wx,wz,t,strength)+.3+Math.sin(age*Math.PI)*(1+pace*2),wz);}p.needsUpdate=true;}
}
