import {clamp} from './physics.js';
export function helmMarkup(portrait){return `<div class="helm hud">
<div class="helm-reading"><button class="officer" id="officer" aria-label="당직 항해사와 항해 수첩">${portrait}</button><div class="speed-readout"><b id="speed">0.0</b><span>kn</span></div><div class="heading-readout"><b id="heading">000°</b><span>선수 방위</span></div><button id="motion-readout" aria-label="롤링 피칭과 복원력 보기"><span>ROLL <b id="roll">0.0°</b></span><span>PITCH <b id="pitch">0.0°</b></span><i id="stability-dot"></i></button><button id="anchor" aria-label="출항"><span class="anchor-icon">⚓</span><span class="anchor-label">출항</span></button></div>
<div class="helm-controls">
<div class="wheel-station"><div class="instrument-label">조타기 <output id="rudder-value">중앙</output></div><div id="steering-wheel" role="slider" tabindex="0" aria-label="조타기: 드래그로 돌리기, 좌우 화살표로 조타, Home으로 중앙" aria-valuemin="-35" aria-valuemax="35" aria-valuenow="0">
<svg id="wheel-art" viewBox="0 0 160 160" aria-hidden="true"><defs><linearGradient id="wheel-metal" x2="1" y2="1"><stop stop-color="#e3e8e9"/><stop offset=".45" stop-color="#637a85"/><stop offset=".65" stop-color="#e0e4e0"/><stop offset="1" stop-color="#344d5b"/></linearGradient><radialGradient id="wheel-hub"><stop stop-color="#526673"/><stop offset="1" stop-color="#182e3b"/></radialGradient></defs><circle cx="80" cy="80" r="64" fill="none" stroke="#091720" stroke-width="18"/><circle cx="80" cy="80" r="64" fill="none" stroke="#425766" stroke-width="12"/><circle cx="80" cy="80" r="64" fill="none" stroke="#192c38" stroke-width="8"/><g fill="url(#wheel-metal)" stroke="#344c58"><path d="m68 70-47-18-5 11 51 28Z"/><path d="m92 70 47-18 5 11-51 28Z"/><path d="m69 91 5 51h12l5-51Z"/></g><circle cx="80" cy="80" r="23" fill="url(#wheel-metal)"/><circle cx="80" cy="80" r="19" fill="url(#wheel-hub)"/><path d="M80 68v23m-9-9c0 12 18 12 18 0m-15-9h12" fill="none" stroke="#d6bf89" stroke-width="2"/><path d="M75 15h10" stroke="#e8cf91" stroke-width="5" stroke-linecap="round"/></svg></div><button id="center-wheel">중앙 정렬</button></div>
<div class="radar-station"><div class="instrument-label">레이더 <button id="radar-range" aria-label="레이더 탐지 범위 변경">800 m</button></div><canvas id="radar" width="320" height="320" role="img" title="북쪽이 위 · 녹색은 해안 · 마름모는 항구 · 점선은 목적지" aria-label="북쪽이 위인 레이더: 녹색 해안, 마름모 항구, 삼각형 내 선박, 점선 목적지"></canvas><div class="radar-caption"><span>△ 내 배</span><span>◇ 항구</span><button id="autopilot" aria-label="자동 항해">자동</button></div></div>
<div class="engine-station"><label class="instrument-label" for="throttle">속도 레버</label><div class="engine-track"><div class="engine-stops"><span>전진</span><span>중립</span><span>후진</span></div><input id="throttle" type="range" min="-30" max="100" value="0" step="1" aria-label="속도 레버: 위로 올려 전진, 아래로 내려 후진" aria-orientation="vertical"/></div><output id="throttle-value">정지</output></div>
</div><div id="control-tip">레버를 위로 올리면 출항 · 휠을 돌리면 조타</div></div>`;}
export function bindWheel(element,onChange){let value=0,pointer=null,lastAngle=0;
 const angle=e=>{const r=element.getBoundingClientRect();return Math.atan2(e.clientX-r.left-r.width/2,-(e.clientY-r.top-r.height/2));};
 const apply=v=>{value=clamp(v,-1,1);onChange(value);};
 element.addEventListener('pointerdown',e=>{if(pointer!==null)return;e.preventDefault();pointer=e.pointerId;lastAngle=angle(e);element.setPointerCapture(e.pointerId);element.classList.add('turning');});
 element.addEventListener('pointermove',e=>{if(e.pointerId!==pointer)return;const a=angle(e),delta=Math.atan2(Math.sin(a-lastAngle),Math.cos(a-lastAngle));lastAngle=a;apply(value+delta/(Math.PI*.75));});
 const release=e=>{if(e.pointerId!==pointer)return;pointer=null;element.classList.remove('turning');};
 element.addEventListener('pointerup',release);element.addEventListener('pointercancel',release);element.addEventListener('lostpointercapture',release);
 element.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home'].includes(e.key)){e.preventDefault();e.stopPropagation();apply(e.key==='Home'?0:value+(e.key==='ArrowRight'?1:-1)*.1);}});
 return v=>{value=clamp(v,-1,1);element.style.setProperty('--wheel-angle',`${value*135}deg`);element.setAttribute('aria-valuenow',String(Math.round(value*35)));element.setAttribute('aria-valuetext',Math.abs(value)<.02?'중앙':`${value>0?'우현':'좌현'} ${Math.round(Math.abs(value)*35)}도`);};
}
export function drawRadar(canvas,state,obstacles,ports,target,t,range=800,river=false,route=[]){
 const c=canvas.getContext('2d'),cx=160,r=143,scale=r/range;c.clearRect(0,0,320,320);c.save();c.beginPath();c.arc(cx,cx,r,0,Math.PI*2);c.clip();c.fillStyle='#071f22';c.fillRect(0,0,320,320);
 c.strokeStyle='#416f683e';c.lineWidth=1;for(const radius of [r/3,2*r/3,r]){c.beginPath();c.arc(cx,cx,radius,0,Math.PI*2);c.stroke();}c.beginPath();c.moveTo(cx,0);c.lineTo(cx,320);c.moveTo(0,cx);c.lineTo(320,cx);c.stroke();
 const project=p=>[cx+(p.x-state.x)*scale,cx+(p.z-state.z)*scale];
 c.fillStyle='#548c74';for(const o of obstacles){if(o.radarHidden)continue;if(o.radarRect){const q=o.radarRect,[x,y]=project(q);c.fillRect(x-q.w*scale/2,y-q.d*scale/2,q.w*scale,q.d*scale);continue;}const [x,y]=project(o);c.beginPath();c.arc(x,y,o.radius*scale,0,Math.PI*2);c.fill();}if(river){const left=cx+(-310-state.x)*scale,right=cx+(310-state.x)*scale;c.fillRect(-10000,0,left+10000,320);c.fillRect(right,0,10000,320);}
 for(const p of ports){const [x,y]=project(p);c.strokeStyle='#f0d09a';c.lineWidth=2;c.beginPath();c.moveTo(x,y-5);c.lineTo(x+5,y);c.lineTo(x,y+5);c.lineTo(x-5,y);c.closePath();c.stroke();}
 if(target){c.strokeStyle='#ffcf87';c.lineWidth=2;c.setLineDash([5,6]);c.beginPath();c.moveTo(cx,cx);for(const p of route.length?route:[target]){const [x,y]=project(p);c.lineTo(x,y);}c.stroke();c.setLineDash([]);const [tx,ty]=project(target);c.beginPath();c.arc(tx,ty,10+Math.sin(t*3)*2,0,Math.PI*2);c.stroke();const next=route[0]||target,[x,y]=project(next),dx=x-cx,dy=y-cx,d=Math.hypot(dx,dy);if(d>r-20){const nx=dx/d,ny=dy/d,px=cx+nx*(r-13),py=cx+ny*(r-13);c.fillStyle='#ffdf92';c.beginPath();c.moveTo(px+nx*8,py+ny*8);c.lineTo(px-nx*7-ny*7,py-ny*7+nx*7);c.lineTo(px-nx*7+ny*7,py-ny*7-nx*7);c.closePath();c.fill();}else{c.fillStyle='#ffdf92';c.beginPath();c.arc(x,y,4,0,Math.PI*2);c.fill();}}

 const a=t*.6;for(let i=0;i<20;i++){c.fillStyle=`rgba(142,225,171,${.055*(1-i/20)})`;c.beginPath();c.moveTo(cx,cx);c.arc(cx,cx,r,a-i*.018,a-(i+1)*.018,true);c.closePath();c.fill();}c.strokeStyle='#9ce5b78c';c.beginPath();c.moveTo(cx,cx);c.lineTo(cx+Math.cos(a)*r,cx+Math.sin(a)*r);c.stroke();
 c.save();c.translate(cx,cx);c.rotate(state.heading);c.strokeStyle='#dcefe5';c.setLineDash([3,6]);c.beginPath();c.moveTo(0,-14);c.lineTo(0,-50);c.stroke();c.setLineDash([]);c.fillStyle='#edf9ed';c.beginPath();c.moveTo(0,-10);c.lineTo(6,7);c.lineTo(0,4);c.lineTo(-6,7);c.closePath();c.fill();c.restore();c.restore();c.fillStyle='#a9c9bc';c.font='15px sans-serif';c.textAlign='center';c.fillText('N',160,13);c.fillText('S',160,318);c.fillText('W',8,166);c.fillText('E',312,166);
 canvas.dataset.position=`${state.x.toFixed(1)},${state.z.toFixed(1)}`;
}
