// Fictional arcade activities: real-time clocks, ordered checkpoints and gentle fishing.
export const FISH=[{name:'고등어',min:22,max:38},{name:'전갱이',min:18,max:32},{name:'참돔',min:25,max:55},{name:'농어',min:35,max:75}];
export function newFishing(random=Math.random){return {phase:'ready',clock:0,wait:4+random()*5,tension:.3,progress:0,held:false,catch:null};}
export function castFishing(f,random=Math.random){Object.assign(f,newFishing(random),{phase:'waiting'});}
export function strikeFishing(f){if(f.phase==='bite'){f.phase='reeling';f.clock=0;return true;}return false;}
export function stepFishing(f,dt,random=Math.random){dt=Math.min(.05,Math.max(0,dt));f.clock+=dt;if(f.phase==='waiting'&&f.clock>=f.wait){f.phase='bite';f.clock=0;}else if(f.phase==='bite'&&f.clock>4){f.phase='escaped';f.held=false;}else if(f.phase==='reeling'){f.tension=Math.max(0,Math.min(1,f.tension+(f.held?.26:-.22)*dt+Math.sin(f.clock*2.7)*dt*.055));if(f.held&&f.tension<.87)f.progress=Math.min(1,f.progress+dt*.16);if(f.tension>=1){f.phase='escaped';f.held=false;}else if(f.progress>=1){const fish=FISH[Math.min(FISH.length-1,Math.floor(random()*FISH.length))];f.catch={name:fish.name,length:Math.round(fish.min+random()*(fish.max-fish.min))};f.phase='caught';f.held=false;return f.catch;}}return null;}
export function makeCourse(center){return [[0,0],[0,-180],[130,-310],[300,-270],[390,-90],[280,100],[100,130],[0,0]].map(([x,z])=>({x:x+center.x,z:z+center.z}));}
export function newRace(center){return {gates:makeCourse(center),next:1,elapsed:0,countdown:3,phase:'countdown',previous:{...center},penalty:0};}
export function stepRace(r,position,dt){if(r.phase==='finished')return false;dt=Math.min(.05,Math.max(0,dt));if(r.phase==='countdown'){r.countdown-=dt;r.previous={x:position.x,z:position.z};if(r.countdown<=0)r.phase='racing';return false;}r.elapsed+=dt;const g=r.gates[r.next],a=r.previous,dx=position.x-a.x,dz=position.z-a.z,len=dx*dx+dz*dz,u=len?Math.max(0,Math.min(1,((g.x-a.x)*dx+(g.z-a.z)*dz)/len)):0,d=Math.hypot(a.x+dx*u-g.x,a.z+dz*u-g.z);r.previous={x:position.x,z:position.z};if(d<29){r.next++;if(r.next===r.gates.length){r.phase='finished';return true;}}return false;}
export function restoreLeisure(value){return {fish:Array.isArray(value?.fish)?value.fish.filter(f=>FISH.some(s=>s.name===f.name)&&Number.isFinite(f.length)&&f.length>=18&&f.length<=75).slice(-40):[],best:Number.isFinite(value?.best)&&value.best>0?value.best:null};}
