import {courseFeatures} from './race-course.js';
import * as THREE from 'three';
import {waveHeight} from './physics.js';
export class LeisureScene{
 constructor(scene){this.group=new THREE.Group();scene.add(this.group);this.markers=[];}
 clear(){for(const c of [...this.group.children]){c.traverse(o=>{o.geometry?.dispose();if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material]){m.map?.dispose();m.dispose();}});this.group.remove(c);}this.markers=[];this.bobber=null;}
 race(r){this.clear();for(let i=1;i<r.gates.length;i++){const gate=r.gates[i],prev=r.gates[i-1],angle=Math.atan2(gate.x-prev.x,-(gate.z-prev.z)),g=new THREE.Group();g.position.set(gate.x,0,gate.z);g.rotation.y=-angle;for(const x of [-29,29]){const b=new THREE.Mesh(new THREE.CylinderGeometry(.8,2,5,16),new THREE.MeshStandardMaterial({color:i===1?0xffce68:0xe9f4ed,roughness:.35}));b.position.set(x,2,0);g.add(b);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.9,.35,8,24),new THREE.MeshStandardMaterial({color:0x17bcca}));ring.rotation.x=Math.PI/2;ring.position.set(x,.3,0);g.add(ring);}const canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;const ctx=canvas.getContext('2d');ctx.fillStyle='#073a50';ctx.beginPath();ctx.arc(64,64,58,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f7e6b5';ctx.font='bold 70px sans-serif';ctx.textAlign='center';ctx.fillText(i===7?'FIN':String(i),64,89);const sign=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(canvas),depthTest:false}));sign.position.y=13;sign.scale.set(9,9,1);sign.visible=i!==7;g.add(sign);this.group.add(g);this.markers.push(g);}this.buildTrack(r);}
 buildTrack(r){
const features=courseFeatures(r.gates);r.features=features;
const material=c=>new THREE.MeshStandardMaterial({color:c,roughness:.4,metalness:.15});
const add=(geo,mat,x,y,z)=>{const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);this.group.add(m);return m;};
const floats=[[],[]];for(const rail of features.rails){const {a,b,nx,nz}=rail;for(const side of [-1,1]){const points=[];const count=Math.ceil(Math.hypot(b.x-a.x,b.z-a.z)/9);for(let i=0;i<=count;i++){const u=i/count,x=a.x+(b.x-a.x)*u+nx*side*38,z=a.z+(b.z-a.z)*u+nz*side*38;points.push(new THREE.Vector3(x,.45,z));floats[i%2].push([x,.6,z]);}this.group.add(new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),count, .16,5,false),material(0xe2f2e5)));}}
for(let i=0;i<2;i++){const mesh=new THREE.InstancedMesh(new THREE.CylinderGeometry(.8,.8,2,10),material(i?0xf4f7ee:0x1ecbd2),floats[i].length),o=new THREE.Object3D();floats[i].forEach((p,j)=>{o.position.set(...p);o.rotation.z=Math.PI/2;o.updateMatrix();mesh.setMatrixAt(j,o.matrix);});this.group.add(mesh);}for(const b of features.barriers){add(new THREE.CylinderGeometry(b.radius,b.radius,1.5,32),material(0xf39c45),b.x,.75,b.z);const ring=add(new THREE.TorusGeometry(b.radius,.45,8,32),material(0xffffff),b.x,1.6,b.z);ring.rotation.x=Math.PI/2;}
for(const ramp of features.ramps){const g=new THREE.Group();g.position.set(ramp.x,0,ramp.z);g.rotation.y=-ramp.heading;this.group.add(g);const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute([-6,.2,9,6,.2,9,-6,3,-9,6,.2,9,6,3,-9,-6,3,-9],3));geo.computeVertexNormals();const m=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:0x16bbc9,side:THREE.DoubleSide,roughness:.4}));g.add(m);for(const x of [-5.8,5.8]){const edge=new THREE.Mesh(new THREE.BoxGeometry(.35,.25,18.3),material(0xf2f5ec));edge.position.set(x,1.6,0);edge.rotation.x=.155;g.add(edge);}for(let i=0;i<3;i++){const arrow=new THREE.Mesh(new THREE.ConeGeometry(1.2,2,3),material(0xffffff));arrow.rotation.x=-Math.PI/2;arrow.position.set(0,1.1+i*.6,4-i*4);g.add(arrow);}}
const finish=r.gates.at(-1),previous=r.gates.at(-2),g=new THREE.Group();g.position.set(finish.x,0,finish.z);g.rotation.y=-Math.atan2(finish.x-previous.x,-(finish.z-previous.z));this.group.add(g);for(const x of [-30,30]){const pole=new THREE.Mesh(new THREE.CylinderGeometry(.8,1.2,19,16),material(0xeaf7f0));pole.position.set(x,9.5,0);g.add(pole);}const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=192;const c=canvas.getContext('2d');c.fillStyle='#f5faf5';c.fillRect(0,0,1024,192);for(let x=0;x<32;x++)for(let y=0;y<2;y++)if((x+y)%2===0){c.fillStyle='#103a4d';c.fillRect(x*32,y*32,32,32);c.fillRect(x*32,128+y*32,32,32);}c.fillStyle='#12394b';c.font='bold 64px sans-serif';c.textAlign='center';c.fillText('FINISH',512,119);const tex=new THREE.CanvasTexture(canvas);tex.colorSpace=THREE.SRGBColorSpace;const banner=new THREE.Mesh(new THREE.PlaneGeometry(62,9),new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide}));banner.position.y=17;g.add(banner);
 }
 fishing(){this.clear();this.bobber=new THREE.Mesh(new THREE.SphereGeometry(.28,16,12),new THREE.MeshStandardMaterial({color:0xffb75f,emissive:0xe77520,emissiveIntensity:.25}));this.group.add(this.bobber);this.line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]),new THREE.LineBasicMaterial({color:0xe6f2e9,transparent:true,opacity:.8}));this.group.add(this.line);this.ripple=new THREE.Mesh(new THREE.RingGeometry(.6,.68,40),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.5,side:THREE.DoubleSide}));this.ripple.rotation.x=-Math.PI/2;this.group.add(this.ripple);this.fish=new THREE.Group();const body=new THREE.Mesh(new THREE.SphereGeometry(1,24,16),new THREE.MeshStandardMaterial({color:0x9fd3cb,metalness:.65,roughness:.25}));body.scale.set(.85,.3,.22);this.fish.add(body);const tail=new THREE.Mesh(new THREE.ConeGeometry(.35,.5,3),new THREE.MeshStandardMaterial({color:0x398a96,side:THREE.DoubleSide}));tail.rotation.z=-Math.PI/2;tail.position.x=-.9;this.fish.add(tail);for(const side of [-1,1]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.055,10,8),new THREE.MeshStandardMaterial({color:0x122935}));eye.position.set(.6,.07,side*.17);this.fish.add(eye);}this.fish.visible=false;this.group.add(this.fish);}
 update(activity,state,t,wave){if(activity?.type==='race'){this.markers.forEach((m,i)=>{m.visible=i===6||i+1>=activity.run.next;m.position.y=waveHeight(m.position.x,m.position.z,t,wave)*.5;m.children[0].material.color.set(i+1===activity.run.next?0xffbf4f:0xe8f4ee);});}else if(activity?.type==='fishing'&&this.bobber){const f=activity.run;this.fish.visible=f.phase==='caught';this.fish.position.set(state.x+Math.cos(state.heading)*5,(state.heave||0)+2.5+Math.sin(t*3)*.3,state.z+Math.sin(state.heading)*5);this.fish.rotation.y=t*.8;const visible=['waiting','bite','reeling'].includes(f.phase);this.group.visible=true;this.bobber.visible=this.line.visible=this.ripple.visible=visible;const x=state.x+Math.cos(state.heading)*9,z=state.z+Math.sin(state.heading)*9,y=waveHeight(x,z,t,wave)+(f.phase==='bite'?Math.sin(t*14)*.4:.1);this.bobber.position.set(x,y,z);this.ripple.position.set(x,y+.05,z);this.ripple.scale.setScalar(1+(t%1)*2);const p=this.line.geometry.attributes.position;p.setXYZ(0,state.x+Math.cos(state.heading)*3,(state.heave||0)+3.5,state.z+Math.sin(state.heading)*3);p.setXYZ(1,x,y,z);p.needsUpdate=true;this.line.geometry.computeBoundingSphere();}}
}
