import * as THREE from 'three';
import {waveHeight} from './physics.js';
export class LeisureScene{
 constructor(scene){this.group=new THREE.Group();scene.add(this.group);this.markers=[];}
 clear(){for(const c of [...this.group.children]){c.traverse(o=>{o.geometry?.dispose();if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material]){m.map?.dispose();m.dispose();}});this.group.remove(c);}this.markers=[];this.bobber=null;}
 race(r){this.clear();for(let i=1;i<r.gates.length;i++){const gate=r.gates[i],prev=r.gates[i-1],angle=Math.atan2(gate.x-prev.x,-(gate.z-prev.z)),g=new THREE.Group();g.position.set(gate.x,0,gate.z);g.rotation.y=-angle;for(const x of [-29,29]){const b=new THREE.Mesh(new THREE.CylinderGeometry(.8,2,5,16),new THREE.MeshStandardMaterial({color:i===1?0xffce68:0xe9f4ed,roughness:.35}));b.position.set(x,2,0);g.add(b);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.9,.35,8,24),new THREE.MeshStandardMaterial({color:0x17bcca}));ring.rotation.x=Math.PI/2;ring.position.set(x,.3,0);g.add(ring);}const canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;const ctx=canvas.getContext('2d');ctx.fillStyle='#073a50';ctx.beginPath();ctx.arc(64,64,58,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f7e6b5';ctx.font='bold 70px sans-serif';ctx.textAlign='center';ctx.fillText(i===7?'終':String(i),64,89);const sign=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(canvas),depthTest:false}));sign.position.y=13;sign.scale.set(14,14,1);g.add(sign);this.group.add(g);this.markers.push(g);}}
 fishing(){this.clear();this.bobber=new THREE.Mesh(new THREE.SphereGeometry(.28,16,12),new THREE.MeshStandardMaterial({color:0xffb75f,emissive:0xe77520,emissiveIntensity:.25}));this.group.add(this.bobber);this.line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]),new THREE.LineBasicMaterial({color:0xe6f2e9,transparent:true,opacity:.8}));this.group.add(this.line);this.ripple=new THREE.Mesh(new THREE.RingGeometry(.6,.68,40),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.5,side:THREE.DoubleSide}));this.ripple.rotation.x=-Math.PI/2;this.group.add(this.ripple);this.fish=new THREE.Group();const body=new THREE.Mesh(new THREE.SphereGeometry(1,24,16),new THREE.MeshStandardMaterial({color:0x9fd3cb,metalness:.65,roughness:.25}));body.scale.set(.85,.3,.22);this.fish.add(body);const tail=new THREE.Mesh(new THREE.ConeGeometry(.35,.5,3),new THREE.MeshStandardMaterial({color:0x398a96,side:THREE.DoubleSide}));tail.rotation.z=-Math.PI/2;tail.position.x=-.9;this.fish.add(tail);for(const side of [-1,1]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.055,10,8),new THREE.MeshStandardMaterial({color:0x122935}));eye.position.set(.6,.07,side*.17);this.fish.add(eye);}this.fish.visible=false;this.group.add(this.fish);}
 update(activity,state,t,wave){if(activity?.type==='race'){this.markers.forEach((m,i)=>{m.visible=i+1>=activity.run.next;m.position.y=waveHeight(m.position.x,m.position.z,t,wave)*.5;m.children[0].material.color.set(i+1===activity.run.next?0xffbf4f:0xe8f4ee);});}else if(activity?.type==='fishing'&&this.bobber){const f=activity.run;this.fish.visible=f.phase==='caught';this.fish.position.set(state.x+Math.cos(state.heading)*5,(state.heave||0)+2.5+Math.sin(t*3)*.3,state.z+Math.sin(state.heading)*5);this.fish.rotation.y=t*.8;const visible=['waiting','bite','reeling'].includes(f.phase);this.group.visible=true;this.bobber.visible=this.line.visible=this.ripple.visible=visible;const x=state.x+Math.cos(state.heading)*9,z=state.z+Math.sin(state.heading)*9,y=waveHeight(x,z,t,wave)+(f.phase==='bite'?Math.sin(t*14)*.4:.1);this.bobber.position.set(x,y,z);this.ripple.position.set(x,y+.05,z);this.ripple.scale.setScalar(1+(t%1)*2);const p=this.line.geometry.attributes.position;p.setXYZ(0,state.x+Math.cos(state.heading)*3,(state.heave||0)+3.5,state.z+Math.sin(state.heading)*3);p.setXYZ(1,x,y,z);p.needsUpdate=true;this.line.geometry.computeBoundingSphere();}}
}
