import {immersedHeave} from './immersion.js';
import {FoamWake} from './foam.js';
import * as T from 'three';
import {makeShip,disposeVessel} from './vessels.js';
import {ships} from './data.js';
import {waveHeight} from './physics.js';
const metal=color=>new T.MeshStandardMaterial({color,roughness:.48,metalness:.25});
function mesh(group,geo,color,x=0,y=0,z=0){const m=new T.Mesh(geo,metal(color));m.position.set(x,y,z);m.userData.privateMaterial=true;group.add(m);return m;}
function box(g,x,y,z,w,h,d,c){return mesh(g,new T.BoxGeometry(w,h,d),c,x,y,z);}
function line(g,points,color=0xb7b5a2){const m=new T.Line(new T.BufferGeometry().setFromPoints(points.map(p=>new T.Vector3(...p))),new T.LineBasicMaterial({color,transparent:true,opacity:.8}));m.userData.privateMaterial=true;g.add(m);return m;}
function fishingBoat(){const g=new T.Group(),shape=new T.Shape();shape.moveTo(0,-13);shape.bezierCurveTo(-4,-10,-4.5,3,-3,10);shape.quadraticCurveTo(0,12,3,10);shape.bezierCurveTo(4.5,3,4,-10,0,-13);const hull=new T.ExtrudeGeometry(shape,{depth:3.3,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.7,bevelThickness:.6,curveSegments:24});hull.scale(1,-1,1);const body=mesh(g,hull,0x183e58);body.rotation.x=-Math.PI/2;body.position.y=-.9;box(g,0,2.6,0,6.7,.5,16,0xd6cbbb);box(g,0,4.6,-4,5,4,5,0xe9e7db);box(g,0,7,-4,6,.45,6,0xeae7d7);box(g,0,5.5,-6.6,4,1.5,.12,0x204354);box(g,0,5.5,-1.4,3.8,1.4,.12,0x204354);box(g,1.6,4,-1.3,1.3,2.5,.15,0xaab8b3);for(const x of [-2.6,2.6])box(g,x,5.5,-4,.12,1.5,3.8,0x264d59);
 for(const x of [-3.1,3.1]){line(g,[[x,3,-8],[x,4.4,-8],[x,4.4,9],[x,3,9]]);for(let z=-7;z<10;z+=2)line(g,[[x,3,z],[x,4.4,z]]);}
 box(g,0,9,-3,.18,6,.18,0xc9c9bb);line(g,[[0,11,-3],[-3,8,5],[3,8,5],[0,11,-3]]);for(const x of [-2.2,2.2]){box(g,x,5,5,.3,5,.3,0x9ca59c);const reel=mesh(g,new T.CylinderGeometry(1.2,1.2,3,20),0x576c62,0,4.2,6);reel.rotation.z=Math.PI/2;}
 for(let i=0;i<7;i++)mesh(g,new T.TorusGeometry(.65,.22,8,16),0x122b32,3.6,1.7,-6+i*2);
 for(const [x,c] of [[-2.8,0xe64c41],[2.8,0x52dc96]]){const light=mesh(g,new T.SphereGeometry(.25,8,8),c,x,7,-4);light.material.emissive.set(c);light.material.emissiveIntensity=2;}
 return g;}
function whale(){const g=new T.Group();const skin=new T.MeshPhysicalMaterial({color:0x243e49,roughness:.27,metalness:.08,clearcoat:1,clearcoatRoughness:.18});const body=new T.Mesh(new T.SphereGeometry(1,40,24),skin);body.scale.set(2.4,2.2,10);body.position.y=-.8;body.userData.privateMaterial=true;g.add(body);const jaw=mesh(g,new T.SphereGeometry(1,24,16),0x7a9298,0,-1.5,-3);jaw.scale.set(1.8,.9,6);
 function fin(x,y,z,sx,sy,sz,angle){const f=mesh(g,new T.SphereGeometry(1,20,12),0x263f47,x,y,z);f.scale.set(sx,sy,sz);f.rotation.z=angle;return f;}fin(-3,-1,0,4,.24,1.2,-.35);fin(3,-1,0,4,.24,1.2,.35);const tail=new T.Group();tail.position.z=9;g.add(tail);const dorsalShape=new T.Shape();dorsalShape.moveTo(0,0);dorsalShape.quadraticCurveTo(-.5,2.8,1,3);dorsalShape.quadraticCurveTo(.4,1,3,0);dorsalShape.closePath();const dorsal=mesh(g,new T.ExtrudeGeometry(dorsalShape,{depth:.25,bevelEnabled:true,bevelSize:.15,bevelThickness:.15,bevelSegments:3,steps:1,curveSegments:16}),0x263f47,0,1,2);dorsal.rotation.y=Math.PI/2;for(const x of [-2.2,2.2]){const f=mesh(tail,new T.SphereGeometry(1,20,12),0x2b444b,x,-.2,1);f.scale.set(3,.25,1.3);f.rotation.y=x*.1;}g.userData.tail=tail;
 const positions=new Float32Array(60*3);for(let i=0;i<60;i++){const a=i*2.4,h=i/60;positions[i*3]=Math.cos(a)*h;positions[i*3+1]=h*10;positions[i*3+2]=Math.sin(a)*h-5;}const spray=new T.Points(new T.BufferGeometry(),new T.PointsMaterial({color:0xe2f3f5,size:.7,transparent:true,opacity:.5,depthWrite:false}));spray.geometry.setAttribute('position',new T.BufferAttribute(positions,3));spray.userData.privateMaterial=true;g.add(spray);g.userData.spray=spray;return g;}
function pilotBoat(coastguard=false){const cabinColor=coastguard?0xe8eee9:0xe8762e;const g=new T.Group(),shape=new T.Shape();shape.moveTo(0,-14);shape.bezierCurveTo(-4,-11,-4,5,-3,11);shape.lineTo(3,11);shape.bezierCurveTo(4,5,4,-11,0,-14);const hull=new T.ExtrudeGeometry(shape,{depth:3,bevelEnabled:true,bevelSegments:3,bevelSize:.6,bevelThickness:.4,steps:1});hull.scale(1,-1,1);const h=mesh(g,hull,0x253f50);h.rotation.x=-Math.PI/2;h.position.y=-.8;box(g,0,2.5,0,7,.45,20,0xcec6b4);box(g,0,4.5,-3,5.6,3.8,8,cabinColor);box(g,0,5.2,-7.1,5,1.6,.15,0x143345);for(const side of [-1,1]){box(g,side*2.85,5.2,-3,.12,1.6,6.8,0x173b4c);line(g,[[side*3.3,3,-10],[side*3.3,4,-10],[side*3.3,4,10],[side*3.3,3,10]]);for(let z=-8;z<=10;z+=3)box(g,side*3.5,1.8,z,.55,.7,2,0x101f27);}box(g,0,8,-3,.15,4,.15,0xc3c5b9);box(g,0,9,-3,3,.25,.5,0xe4e6de);const canopy=box(g,0,7.4,-4,6,.7,6,cabinColor);canopy.material.emissive.set(0x291409);const cv=document.createElement('canvas');cv.width=256;cv.height=64;const ctx=cv.getContext('2d');ctx.fillStyle=coastguard?'#1d5287':'#f5762e';ctx.fillRect(0,0,256,64);ctx.fillStyle='white';ctx.font='bold 44px sans-serif';ctx.textAlign='center';ctx.fillText(coastguard?'KCG':'PILOT',128,49);const tex=new T.CanvasTexture(cv);tex.colorSpace=T.SRGBColorSpace;for(const side of [-1,1]){const sign=new T.Mesh(new T.PlaneGeometry(6,1.5),new T.MeshBasicMaterial({map:tex,side:T.DoubleSide}));sign.position.set(side*3.2,4,-1);sign.rotation.y=side*Math.PI/2;sign.userData.privateMaterial=true;if(side===1)sign.userData.ownedTexture=tex;g.add(sign);}return g;}
function shark(){const g=new T.Group();const body=mesh(g,new T.SphereGeometry(1,28,16),0x3e5660,0,-.8,0);body.scale.set(1.25,1.15,5.8);const belly=mesh(g,new T.SphereGeometry(1,24,12),0x9caeae,0,-1.35,-.8);belly.scale.set(.95,.55,4.5);const shape=new T.Shape();shape.moveTo(0,0);shape.lineTo(0,3.6);shape.quadraticCurveTo(1.3,3.2,2.8,0);shape.closePath();const dorsal=mesh(g,new T.ExtrudeGeometry(shape,{depth:.22,bevelEnabled:true,bevelSize:.12,bevelThickness:.1,bevelSegments:2,steps:1}),0x314851,0,-.15,0);dorsal.rotation.y=Math.PI/2;for(const side of [-1,1]){const fin=mesh(g,new T.SphereGeometry(1,16,8),0x3d545e,side*1.6,-.9,-1);fin.scale.set(2,.15,1);fin.rotation.y=side*.6;}const tail=new T.Group();tail.position.z=5;g.add(tail);const f=mesh(tail,new T.SphereGeometry(1,16,12),0x314851,0,.2,0);f.scale.set(.2,2.4,1);f.rotation.x=.35;g.userData.tail=tail;return g;}
function coastguardBoat(){const g=pilotBoat(true);g.scale.setScalar(1.15);const canvas=document.createElement('canvas');canvas.width=512;canvas.height=100;const ctx=canvas.getContext('2d');ctx.fillStyle='#f2f5ee';ctx.fillRect(0,0,512,100);ctx.fillStyle='#194f86';ctx.font='bold 45px sans-serif';ctx.textAlign='center';ctx.fillText('해양경찰 · 구조',256,68);const texture=new T.CanvasTexture(canvas);texture.colorSpace=T.SRGBColorSpace;for(const side of [-1,1]){const sign=new T.Mesh(new T.PlaneGeometry(10,2),new T.MeshBasicMaterial({map:texture,side:T.DoubleSide}));sign.position.set(side*3.8,3.1,3);sign.rotation.y=side*Math.PI/2;sign.userData.privateMaterial=true;if(side===1)sign.userData.ownedTexture=texture;g.add(sign);}const lights=[];for(const [x,color]of [[-1,0x278dff],[1,0xff4e4e]]){const l=mesh(g,new T.SphereGeometry(.5,12,8),color,x,8.3,-3);l.material.emissive.set(color);lights.push(l);}g.userData.beacons=lights;return g;}
export class LivingSea{
 constructor(scene){this.scene=scene;this.wakes=new Map();this.group=new T.Group();scene.add(this.group);this.models=new Map();}
 setWorld(world){for(const w of this.wakes.values())w.foam.dispose();this.wakes.clear();disposeVessel(this.group);this.models.clear();this.syncContacts(world);this.addHazards(world);}
 syncContacts(world){const ids=new Set([...world.contacts,...world.hazards].map(c=>c.id));for(const [id,m] of this.models)if(!ids.has(id)){m.removeFromParent();disposeVessel(m);this.models.delete(id);this.wakes.get(id)?.foam.dispose();this.wakes.delete(id);}
 for(const c of world.contacts){if(this.models.has(c.id))continue;let m,spec;if(c.kind==='coastguard'){m=coastguardBoat();spec={length:30,beam:9};}else if(c.kind==='whale')m=whale();else if(c.kind==='shark')m=shark();else if(c.kind==='pilot'){m=pilotBoat();spec={length:26,beam:8};}else if(c.kind==='fishing'){m=fishingBoat();spec={length:26,beam:8};}else{const kind=c.modelKind||(c.kind==='towing'?'tug':c.kind==='cargo'?'container':c.kind);const source=ships.find(s=>s.kind===kind)||ships[1];m=makeShip(source,false);const scale=c.local?(c.kind==='cargo'?.85:c.kind==='ferry'?.65:.95):c.id.startsWith('outer-')?(['container','bulk','tanker','carcarrier'].includes(kind)?1.1:kind==='ferry'?.85:.9):kind==='container'||kind==='ferry'?.45:.9;m.scale.setScalar(scale);spec={...source,length:source.length*scale,beam:source.beam*scale,draft:source.draft*scale};}
 if(c.kind==='towing'){const assembly=new T.Group();assembly.add(m);m=assembly;line(m,[[0,2,13],[0,.7,55],[0,2,78]],0xd6b88b);box(m,0,1,95,17,5,38,0x394b50);box(m,0,4,95,16,1,37,0x8a8e7c);for(let i=0;i<4;i++)box(m,0,6,84+i*7,12,3,5,0x8b6d4b);for(const x of [-8.6,8.6])for(let z=81;z<112;z+=6)mesh(m,new T.TorusGeometry(1,.3,8,12),0x172d31,x,2,z);}
 if(c.status==='fishing'||c.status==='restricted'){const signals=new T.Group();m.add(signals);signals.position.set(0,14,0);if(c.status==='fishing'){for(const y of [0,1.5]){const cone=mesh(signals,new T.ConeGeometry(.7,1.5,12),0x121b20,0,y,0);cone.rotation.z=y===0?0:Math.PI;}}else{for(const y of [0,4])mesh(signals,new T.SphereGeometry(.65,12,8),0x121b20,0,y,0);mesh(signals,new T.OctahedronGeometry(.9),0x121b20,0,2,0);}const gear=new T.Group();m.add(gear);line(gear,[[0,9,8],[0,4,15],[0,-8,18]],0xe0c38e);mesh(gear,new T.CylinderGeometry(1,1.5,3,12),0xc99b51,0,-5,18);m.userData.gear=gear;}
 if(spec)this.wakes.set(c.id,{foam:new FoamWake(this.scene,{detail:'light'}),spec});this.models.set(c.id,m);this.group.add(m);}

 }
 addHazards(world){for(const h of world.hazards){const g=new T.Group();g.position.set(h.x,0,h.z);if(h.kind==='workzone'){for(let i=0;i<12;i++){const a=i*Math.PI/6,x=Math.cos(a)*h.radius,z=Math.sin(a)*h.radius;mesh(g,new T.SphereGeometry(1.6,12,8),0xe9b24a,x,1,z);box(g,x,3,z,.2,4,.2,0xddc99b);}const ring=line(g,Array.from({length:65},(_,i)=>[Math.cos(i*Math.PI/32)*h.radius,.4,Math.sin(i*Math.PI/32)*h.radius]),0xc5a66b);ring.material.opacity=.35;}else if(h.kind==='net'){for(const x of [-60,60]){mesh(g,new T.SphereGeometry(1.5,12,10),0xe7a64a,x,1,0);box(g,x,4,0,.15,6,.15,0x9ea49b);box(g,x+1.2,6,0,2.4,1.3,.08,0xe58a43);}for(let x=-60;x<=60;x+=6){mesh(g,new T.SphereGeometry(.5,8,6),0xf6c774,x,.8,0);line(g,[[x,.7,0],[x,-5,0]],0x67877d);}for(const y of [.5,-1,-3,-5])line(g,[[-60,y,0],[60,y,0]],0x819888);}else{for(let i=0;i<6;i++){const log=mesh(g,new T.CylinderGeometry(.6,.9,12,10),0x716147,(i-3)*2,.2,i%2*3);log.rotation.z=Math.PI/2;log.rotation.y=i*.4;}}this.group.add(g);this.models.set(h.id,g);}}
 update(world,t,strength){for(const c of world.contacts){const m=this.models.get(c.id);if(!m)continue;const wake=this.wakes.get(c.id);wake?.foam.update(c,wake.spec,t,strength);m.position.set(c.x,waveHeight(c.x,c.z,t,strength)+(c.depth||0),c.z);const sn=Math.sin(c.heading),cs=Math.cos(c.heading),L=wake?.spec.length||20,B=wake?.spec.beam||5;const pitch=(waveHeight(c.x+sn*L*.35,c.z-cs*L*.35,t,strength)-waveHeight(c.x-sn*L*.35,c.z+cs*L*.35,t,strength))/(L*.7),roll=(waveHeight(c.x+cs*B*.5,c.z+sn*B*.5,t,strength)-waveHeight(c.x-cs*B*.5,c.z-sn*B*.5,t,strength))/B;m.rotation.set(T.MathUtils.clamp(pitch,-.22,.22),-c.heading,T.MathUtils.clamp(roll,-.3,.3),'YXZ');if(wake?.spec.draft)m.position.y=immersedHeave({x:c.x,z:c.z,heading:c.heading,pitch:m.rotation.x,roll:-m.rotation.z,heave:m.position.y},wake.spec,(x,z)=>waveHeight(x,z,t,strength));if(m.userData.beacons)m.userData.beacons.forEach((l,i)=>l.material.emissiveIntensity=Math.sin(t*9+i*Math.PI)>0?5:.15);if(m.userData.gear)m.userData.gear.rotation.x=Math.sin(t*.35)*.12;if(c.kind==='shark')m.userData.tail.rotation.y=Math.sin(t*3)*.35;if(c.kind==='whale'){m.userData.tail.rotation.x=Math.sin(t*1.4)*.2;m.userData.spray.visible=c.depth>-.1&&world.time%16<2.5;}}}
}
