import {FoamWake} from './foam.js';
import * as T from 'three';
import {makeShip,disposeVessel} from './vessels.js';
import {ships} from './data.js';
import {waveHeight} from './physics.js';
const metal=color=>new T.MeshStandardMaterial({color,roughness:.48,metalness:.25});
function mesh(group,geo,color,x=0,y=0,z=0){const m=new T.Mesh(geo,metal(color));m.position.set(x,y,z);m.userData.privateMaterial=true;group.add(m);return m;}
function box(g,x,y,z,w,h,d,c){return mesh(g,new T.BoxGeometry(w,h,d),c,x,y,z);}
function line(g,points,color=0xb7b5a2){const m=new T.Line(new T.BufferGeometry().setFromPoints(points.map(p=>new T.Vector3(...p))),new T.LineBasicMaterial({color,transparent:true,opacity:.8}));m.userData.privateMaterial=true;g.add(m);return m;}
function fishingBoat(){const g=new T.Group(),shape=new T.Shape();shape.moveTo(0,-13);shape.bezierCurveTo(-4,-10,-4.5,3,-3,10);shape.quadraticCurveTo(0,12,3,10);shape.bezierCurveTo(4.5,3,4,-10,0,-13);const hull=new T.ExtrudeGeometry(shape,{depth:3.3,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.7,bevelThickness:.6,curveSegments:24});hull.scale(1,-1,1);const body=mesh(g,hull,0x183e58);body.rotation.x=-Math.PI/2;body.position.y=-.9;box(g,0,2.6,0,6.7,.5,16,0xd6cbbb);box(g,0,4.6,-4,5,4,5,0xe9e7db);box(g,0,7,-4,6,.45,6,0xeae7d7);box(g,0,5.5,-6.6,4,1.5,.12,0x204354);box(g,0,5.5,-1.4,3.8,1.4,.12,0x204354);box(g,1.6,4,-1.3,1.3,2.5,.15,0xaab8b3);for(const x of [-2.6,2.6])box(g,x,5.5,-4,.12,1.5,3.8,0x264d59);
 for(const x of [-3.1,3.1]){line(g,[[x,3,-8],[x,4.4,-8],[x,4.4,9],[x,3,9]]);for(let z=-7;z<10;z+=2)line(g,[[x,3,z],[x,4.4,z]]);}
 box(g,0,9,-3,.18,6,.18,0xc9c9bb);line(g,[[0,11,-3],[-3,8,5],[3,8,5],[0,11,-3]]);for(const x of [-2.2,2.2]){box(g,x,5,5,.3,5,.3,0x9ca59c);const reel=mesh(g,new T.CylinderGeometry(1.2,1.2,3,20),0x576c62,0,4.2,6);reel.rotation.z=Math.PI/2;}
 for(let i=0;i<7;i++)mesh(g,new T.TorusGeometry(.65,.22,8,16),0x122b32,3.6,1.7,-6+i*2);
 for(const [x,c] of [[-2.8,0xe64c41],[2.8,0x52dc96]]){const light=mesh(g,new T.SphereGeometry(.25,8,8),c,x,7,-4);light.material.emissive.set(c);light.material.emissiveIntensity=2;}
 return g;}
function whale(){const g=new T.Group();const skin=new T.MeshPhysicalMaterial({color:0x243e49,roughness:.27,metalness:.08,clearcoat:1,clearcoatRoughness:.18});const body=new T.Mesh(new T.SphereGeometry(1,40,24),skin);body.scale.set(2.4,2.2,10);body.position.y=-.8;body.userData.privateMaterial=true;g.add(body);const jaw=mesh(g,new T.SphereGeometry(1,24,16),0x7a9298,0,-1.5,-3);jaw.scale.set(1.8,.9,6);
 function fin(x,y,z,sx,sy,sz,angle){const f=mesh(g,new T.SphereGeometry(1,20,12),0x263f47,x,y,z);f.scale.set(sx,sy,sz);f.rotation.z=angle;return f;}fin(-3,-1,0,4,.24,1.2,-.35);fin(3,-1,0,4,.24,1.2,.35);const tail=new T.Group();tail.position.z=9;g.add(tail);const dorsalShape=new T.Shape();dorsalShape.moveTo(0,0);dorsalShape.quadraticCurveTo(-.5,2.8,1,3);dorsalShape.quadraticCurveTo(.4,1,3,0);dorsalShape.closePath();const dorsal=mesh(g,new T.ExtrudeGeometry(dorsalShape,{depth:.25,bevelEnabled:true,bevelSize:.15,bevelThickness:.15,bevelSegments:3,steps:1,curveSegments:16}),0x263f47,0,1,2);dorsal.rotation.y=Math.PI/2;for(const x of [-2.2,2.2]){const f=mesh(tail,new T.SphereGeometry(1,20,12),0x2b444b,x,-.2,1);f.scale.set(3,.25,1.3);f.rotation.y=x*.1;}g.userData.tail=tail;
 const positions=new Float32Array(60*3);for(let i=0;i<60;i++){const a=i*2.4,h=i/60;positions[i*3]=Math.cos(a)*h;positions[i*3+1]=h*10;positions[i*3+2]=Math.sin(a)*h-5;}const spray=new T.Points(new T.BufferGeometry(),new T.PointsMaterial({color:0xe2f3f5,size:.7,transparent:true,opacity:.5,depthWrite:false}));spray.geometry.setAttribute('position',new T.BufferAttribute(positions,3));spray.userData.privateMaterial=true;g.add(spray);g.userData.spray=spray;return g;}
export class LivingSea{
 constructor(scene){this.scene=scene;this.wakes=new Map();this.group=new T.Group();scene.add(this.group);this.models=new Map();}
 setWorld(world){for(const w of this.wakes.values())w.foam.dispose();this.wakes.clear();disposeVessel(this.group);this.models.clear();for(const c of world.contacts){let m;if(c.kind==='whale')m=whale();else if(c.kind==='fishing')m=fishingBoat();else{const spec=ships.find(s=>s.kind===(c.kind==='ferry'?'ferry':'container'));m=makeShip(spec);m.scale.setScalar(.6);}if(c.kind!=='whale'){const spec=c.kind==='fishing'?{length:26,beam:8}:ships.find(s=>s.kind===(c.kind==='ferry'?'ferry':'container'));this.wakes.set(c.id,{foam:new FoamWake(this.scene),spec:c.kind==='fishing'?spec:{length:spec.length*.6,beam:spec.beam*.6}});}this.models.set(c.id,m);this.group.add(m);}
 for(const h of world.hazards){const g=new T.Group();g.position.set(h.x,0,h.z);if(h.kind==='net'){for(const x of [-60,60]){mesh(g,new T.SphereGeometry(1.5,12,10),0xe7a64a,x,1,0);box(g,x,4,0,.15,6,.15,0x9ea49b);box(g,x+1.2,6,0,2.4,1.3,.08,0xe58a43);}for(let x=-60;x<=60;x+=6){mesh(g,new T.SphereGeometry(.5,8,6),0xf6c774,x,.8,0);line(g,[[x,.7,0],[x,-5,0]],0x67877d);}for(const y of [.5,-1,-3,-5])line(g,[[-60,y,0],[60,y,0]],0x819888);}else{for(let i=0;i<6;i++){const log=mesh(g,new T.CylinderGeometry(.6,.9,12,10),0x716147,(i-3)*2,.2,i%2*3);log.rotation.z=Math.PI/2;log.rotation.y=i*.4;}}this.group.add(g);this.models.set(h.id,g);}}
 update(world,t,strength){for(const c of world.contacts){const m=this.models.get(c.id);if(!m)continue;const wake=this.wakes.get(c.id);wake?.foam.update(c,wake.spec,t,strength);m.position.set(c.x,waveHeight(c.x,c.z,t,strength)+(c.depth||0),c.z);m.rotation.set(Math.sin(t*1.1+c.x)*.025,-c.heading,Math.sin(t*.8+c.z)*.045,'YXZ');if(c.kind==='whale'){m.userData.tail.rotation.x=Math.sin(t*1.4)*.2;m.userData.spray.visible=c.depth>-.1&&world.time%16<2.5;}}}
}
