import './style.css';
import {ships,regions,weatherPresets} from './data.js';
import {createVessel,stepVessel,waveHeight,canDock,applyBoundary,clamp} from './physics.js';
import {OceanScene} from './scene.js';
import {SeaAudio} from './audio.js';
const $=s=>document.querySelector(s);
let saved={};try{saved=JSON.parse(localStorage.getItem('yoonseul-save')||'{}');}catch{}
let credits=Number.isFinite(saved.credits)&&saved.credits>=0?saved.credits:0,totalDistance=Number.isFinite(saved.distance)?saved.distance:0,deliveries=Number.isFinite(saved.deliveries)?saved.deliveries:0;
let simSpeed=1;
let region=regions.find(r=>r.id===saved.region)||regions[0],spec=ships.find(s=>s.id===saved.ship)||ships[1];if(region.layout==='river'&&spec.draft>region.depth)spec=ships[0];
let state=createVessel(),weather='breeze',timeMode='sunset',started=false,paused=false,zen=false,autopilot=false,mission=null,ports=[],keys={},tab='fleet',lastCollision=-100;
const audio=new SeaAudio();
const icons={ship:'♧',anchor:'⚓',sound:'♫',camera:'▣',map:'⌁'};
$('#app').innerHTML=`
 <div id="ocean" aria-label="3D 항해 화면"></div><div class="vignette"></div>
 <header class="topbar"><a class="brand" href="#" aria-label="윤슬 홈"><span class="brand-icon">≋</span><span>윤슬<small>Korean Blue Voyage</small></span></a><div class="top-location"><span class="live-dot"></span><span id="region-title"></span><span class="divider"></span><span id="weather-title">산들바람</span></div><div class="top-actions"><span class="balance"><span>항해 수익</span><b id="credits">₩ 0</b></span><button id="sound" aria-label="바다 소리 켜기" title="바다 소리">♫ <span>소리 켜기</span></button><button id="settings" aria-label="환경 설정">⚙</button></div></header>
 <section class="place-title hud"><span id="sea-en"></span><h1 id="place-name"></h1><p id="coordinates"></p></section>
 <nav class="side-tools hud" aria-label="항해 메뉴"><button data-panel="fleet" class="selected"><span>♧</span>선박</button><button data-panel="chart"><span>⌁</span>해역</button><button data-panel="jobs"><span>▤</span>의뢰</button><button id="zen"><span>◉</span>물멍</button><button id="photo"><span>▣</span>사진</button></nav>
 <aside class="voyage hud"><div class="section-label">오늘의 항해 <span>↗</span></div><h2 id="ship-name"></h2><p id="ship-type"></p><div class="voyage-rule"></div><div class="voyage-row"><span>항해 거리</span><strong id="distance">0.00 <small>nm</small></strong></div><div class="voyage-row"><span>수심</span><strong id="depth"></strong></div><div class="voyage-row"><span>바람</span><strong id="wind"></strong></div><button class="mission-link" id="mission-button">가까운 항구에서 의뢰 시작 <span>↗</span></button><div id="mission-status"></div></aside>
 <div class="horizon-note hud"><span class="line"></span>어디로든, 당신의 속도로.</div>
 <section class="instruments hud"><div class="speed-block"><span class="instrument-label">대수속력</span><div><b id="speed">0.0</b><span>knots</span></div></div><div class="heading-block"><div class="compass-scale"><span>W</span><span>NW</span><strong>N</strong><span>NE</span><span>E</span></div><div class="compass-pointer">▾</div><div class="heading-value"><b id="heading">000°</b><span>선수 방위</span></div></div><div class="throttle-block"><label for="throttle">엔진 출력 <strong id="throttle-value">0%</strong></label><input id="throttle" type="range" min="-30" max="100" value="0"/><div><span>후진</span><span>정지</span><span>전진</span></div></div><button id="anchor" class="instrument-button" title="Space">⚓<span>닻 내리기</span></button><button id="autopilot" class="instrument-button" title="P">⌁<span>자동 항해</span></button></section>
 <section class="minimap hud"><div class="map-top"><span>항해도</span><span id="map-range">반경 2 km</span></div><canvas id="map" width="260" height="180" aria-label="선박 위치와 항구가 표시된 항해도"></canvas><div class="map-bottom"><span>△ 내 선박</span><span>◌ 항구</span><button id="chart-open">확대 ↗</button></div></section>
 <footer class="controls-help hud"><span><kbd>W</kbd><kbd>S</kbd> 출력</span><span><kbd>A</kbd><kbd>D</kbd> 조타</span><span><kbd>C</kbd> 시점</span><span><kbd>Space</kbd> 닻</span><span>드래그로 둘러보기</span><button id="time-speed">항해 1×</button><button id="pause">Ⅱ 일시정지</button></footer>
 <div class="touch-controls hud"><button data-key="a" aria-label="좌현 조타">◀</button><button data-key="s" aria-label="감속">−</button><button data-key="w" aria-label="가속">＋</button><button data-key="d" aria-label="우현 조타">▶</button></div>
 <button id="exit-zen" hidden>◉ 항해 화면으로 돌아가기</button><div id="toast" role="status"></div>
 <div id="welcome" class="welcome"><div class="welcome-content"><span class="welcome-kicker">한국의 바다를, 나의 속도로</span><h2>잠시, 바다에<br/>머물러도 좋아요.</h2><p>물결에 몸을 맡기고 섬 사이를 항해하세요.<br/>목적지가 없어도 괜찮은, 당신만의 바다.</p><button id="start">항해 시작하기 <span>↗</span></button><small>무료 플레이 · 로그인 없이 · 이어지는 항해 기록</small></div><div class="welcome-bottom">서해의 섬에서 동해의 수평선까지<span>파도 · 바람 · 그리고 당신</span></div></div>
 <dialog id="panel"><div class="panel-head"><div><span id="panel-eyebrow">나만의 항해</span><h2 id="panel-title">선박 선택</h2></div><button id="close-panel" aria-label="닫기">✕</button></div><div id="panel-body"></div></dialog>
 <div id="error" hidden></div>`;
let ocean;
try{ocean=new OceanScene($('#ocean'));ocean.setShip(spec);ports=ocean.setRegion(region);}catch(error){$('#error').hidden=false;$('#error').textContent='3D 화면을 시작할 수 없습니다. 하드웨어 가속을 켠 Chrome 또는 Edge에서 다시 열어 주세요.';console.error(error);}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function save(){try{localStorage.setItem('yoonseul-save',JSON.stringify({credits,distance:totalDistance+state.distance,deliveries,ship:spec.id,region:region.id}));}catch{}}
function refresh(){
 $('#region-title').textContent=region.name;$('#sea-en').textContent=region.en;$('#place-name').textContent=region.label;$('#ship-name').textContent=spec.en;$('#ship-type').textContent=spec.name+' / '+spec.type;$('#credits').textContent='₩ '+credits.toLocaleString('ko-KR');$('#depth').textContent=region.depth+' m';$('#wind').textContent=(region.wind*weatherPresets[weather].wind).toFixed(1)+' m/s ↙';$('#weather-title').textContent=weatherPresets[weather].name;
}
function reset(){totalDistance+=state.distance;state=createVessel();mission=null;autopilot=false;$('#autopilot').classList.remove('active');$('#anchor').classList.remove('active');$('#anchor span').textContent='닻 내리기';$('#throttle').value=0;$('#mission-status').textContent='';refresh();save();}
function panel(name){tab=name;$('#panel').showModal();renderPanel();}
function renderPanel(){
 const body=$('#panel-body');$('#panel-title').textContent={fleet:'어떤 배로 떠날까요?',chart:'다음 바다를 골라보세요',jobs:'항해에 작은 목적을',settings:'바다의 분위기'}[tab];
 if(tab==='fleet')body.innerHTML=`<p class="panel-intro">배마다 다른 무게와 속도, 다른 항해의 감각.<br/>모든 선박을 자유롭게 이용할 수 있어요.</p><div class="fleet-list">${ships.map(s=>`<button class="ship-card ${spec.id===s.id?'chosen':''}" data-ship="${s.id}"><div class="ship-silhouette ${s.id}"><i></i><i></i><i></i><i></i></div><div><span>${s.name}</span><h3>${s.en}</h3><p>${s.type}</p><small>${s.maxSpeed} knots <em>·</em> 전장 ${s.length} m <em>·</em> 흘수 ${s.draft} m</small></div><b>${spec.id===s.id?'탑승 중':'선택 ↗'}</b></button>`).join('')}</div><p class="fine">선박 교체 시 현재 항해와 의뢰가 초기화됩니다. 강에서는 요트로 항해할 수 있어요.</p>`;
 if(tab==='chart')body.innerHTML=`<p class="panel-intro">서해 5도부터 깊은 동해, 그리고 도시의 강까지.</p><div class="region-list">${regions.map(r=>`<button data-region="${r.id}" class="region-card ${r.id===region.id?'chosen':''}"><span>${r.en}</span><h3>${r.name}</h3><p>${r.desc}</p><small>${r.ports.join(' · ')}</small><b>${r.id===region.id?'현재 해역':'이곳으로 이동 ↗'}</b></button>`).join('')}</div><p class="fine">실제 지명에서 영감을 받은 축약 해역입니다. 해역 간 이동은 메뉴로 이루어지며, 실제 해도·항로·수심을 재현하지 않습니다. 강 선택 시 요트로 전환됩니다.</p>`;
 if(tab==='jobs')body.innerHTML=`<div class="ledger"><span>누적 운송 수익<strong>₩ ${credits.toLocaleString('ko-KR')}</strong></span><span>완료한 항해<strong>${deliveries} 회</strong></span></div><p class="panel-intro">의뢰를 받고 표시된 항구로 이동하세요.<br/>항구 95 m 이내에서 2.7 knots 아래로 감속하면 정산할 수 있어요.</p>${mission?`<div class="job-card"><span>진행 중인 의뢰</span><h3>${mission.name}까지 ${spec.cargo}</h3><p>보상 ₩ ${mission.reward.toLocaleString('ko-KR')}</p><button id="job-auto">목적지로 자동 항해</button><button id="job-complete">도착 확인 · 정산</button><button id="job-cancel" class="secondary">의뢰 취소</button></div>`:ports.map((p,i)=>`<div class="job-card"><span>${spec.cargo}</span><h3>${p.name}에 다녀오기</h3><p>${Math.round(Math.hypot(state.x-p.x,state.z-p.z))} m · 보상 ₩ ${(spec.reward+i*500).toLocaleString('ko-KR')}</p><button data-job="${i}">의뢰 수락 ↗</button></div>`).join('')}<p class="fine">수익은 게임 안의 가상 재화입니다. 기록은 현재 브라우저에 저장됩니다.</p>`;
 if(tab==='settings')body.innerHTML=`<p class="panel-intro">오늘 마음에 드는 바다를 만들어보세요.</p><h3>시간</h3><div class="segmented">${[['day','한낮'],['sunset','노을'],['night','밤바다']].map(([id,n])=>`<button data-time="${id}" class="${timeMode===id?'chosen':''}">${n}</button>`).join('')}</div><h3>바람과 파도</h3><div class="segmented">${Object.entries(weatherPresets).map(([id,w])=>`<button data-weather="${id}" class="${weather===id?'chosen':''}">${w.name}</button>`).join('')}</div><h3>바다 소리</h3><label class="volume">음량 <input id="volume" type="range" min="0" max="100" value="${audio.volume*100}"></label><h3>시점</h3><div class="segmented"><button id="camera-follow" class="${ocean?.cameraMode===0?'chosen':''}">선박 따라가기</button><button id="camera-bridge" class="${ocean?.cameraMode===1?'chosen':''}">선상에서 보기</button></div><p class="fine">W/S 출력 · A/D 조타 · Space 닻 · C 시점 · P 자동 항해 · H 물멍 · Esc 닫기<br/>파도, 부력, 관성, 바람과 해류를 간략화한 게임 물리입니다.</p>`;
 body.querySelectorAll('[data-ship]').forEach(b=>b.onclick=()=>{const next=ships.find(s=>s.id===b.dataset.ship);if(region.layout==='river'&&next.draft>region.depth){toast('이 배는 강의 수심보다 흘수가 깊어요. 바다 해역을 먼저 선택하세요.');return;}spec=next;ocean?.setShip(spec);reset();renderPanel();toast(spec.name+'에 승선했습니다.');});
 body.querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>{region=regions.find(r=>r.id===b.dataset.region);if(region.layout==='river'&&spec.draft>region.depth){spec=ships[0];ocean?.setShip(spec);}ports=ocean?.setRegion(region)||[];reset();renderPanel();toast(region.name+' 항해를 시작합니다.');});
 body.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.job);mission={...ports[i],reward:spec.reward+i*500};renderPanel();$('#mission-status').textContent=mission.name+' · 항해 중';toast('의뢰를 수락했습니다. P 키로 자동 항해할 수 있어요.');});
 body.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{timeMode=b.dataset.time;ocean?.setTime(timeMode);renderPanel();});body.querySelectorAll('[data-weather]').forEach(b=>b.onclick=()=>{weather=b.dataset.weather;refresh();renderPanel();});
 if($('#volume'))$('#volume').oninput=e=>audio.setVolume(e.target.value/100);
 if($('#job-auto'))$('#job-auto').onclick=()=>{setAuto(true);$('#panel').close();};if($('#job-complete'))$('#job-complete').onclick=settle;if($('#job-cancel'))$('#job-cancel').onclick=()=>{mission=null;setAuto(false);$('#mission-status').textContent='';renderPanel();};
 if($('#camera-follow'))$('#camera-follow').onclick=()=>{ocean.cameraMode=0;renderPanel();};if($('#camera-bridge'))$('#camera-bridge').onclick=()=>{ocean.cameraMode=1;ocean.orbit=0;renderPanel();};
}
function settle(){if(!mission)return;if(!canDock(state,mission)){toast('목적지 95 m 이내에서 2.7 knots 미만으로 감속하세요.');return;}credits+=mission.reward;deliveries++;state.throttle=0;state.anchored=true;$('#anchor').classList.add('active');$('#anchor span').textContent='닻 올리기';toast('운송 완료! ₩ '+mission.reward.toLocaleString('ko-KR')+' 수익을 얻었습니다.');mission=null;setAuto(false);$('#mission-status').textContent='운송 완료 · 잠시 쉬어가세요';refresh();save();if($('#panel').open)renderPanel();}
function setAuto(value){autopilot=value;$('#autopilot').classList.toggle('active',autopilot);if(autopilot){state.anchored=false;$('#anchor').classList.remove('active');$('#anchor span').textContent='닻 내리기';toast(mission?'목적지로 자동 항해합니다.':'현재 방위를 유지하며 항해합니다.');}}
function toggleAnchor(){state.anchored=!state.anchored;if(state.anchored){state.throttle=0;setAuto(false);}$('#anchor').classList.toggle('active',state.anchored);$('#anchor span').textContent=state.anchored?'닻 올리기':'닻 내리기';toast(state.anchored?'닻을 내렸습니다. 파도에 잠시 머물러 보세요.':'닻을 올렸습니다.');}
function toggleZen(){zen=!zen;document.body.classList.toggle('zen',zen);$('#exit-zen').hidden=!zen;}
function togglePause(){paused=!paused;$('#pause').textContent=paused?'▶ 항해 계속':'Ⅱ 일시정지';}
$('#start').onclick=async()=>{started=true;$('#welcome').classList.add('dismissed');state.throttle=.35;try{const on=await audio.toggle();$('#sound').innerHTML=on?'♫ <span>소리 켜짐</span>':'♫ <span>소리 켜기</span>';$('#sound').setAttribute('aria-label',on?'바다 소리 끄기':'바다 소리 켜기');}catch{toast('소리 버튼을 눌러 바다 소리를 켜세요.');}};
$('#sound').onclick=async()=>{try{const on=await audio.toggle();$('#sound').innerHTML='♫ <span>'+(on?'소리 켜짐':'소리 켜기')+'</span>';$('#sound').setAttribute('aria-label',on?'바다 소리 끄기':'바다 소리 켜기');}catch{toast('이 브라우저에서 오디오를 시작할 수 없습니다.');}};
$('#settings').onclick=()=>panel('settings');document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>panel(b.dataset.panel));$('#close-panel').onclick=()=>$('#panel').close();$('#panel').addEventListener('click',e=>{if(e.target===$('#panel')){const r=$('#panel').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#panel').close();}});
$('#anchor').onclick=toggleAnchor;$('#autopilot').onclick=()=>setAuto(!autopilot);$('#zen').onclick=toggleZen;$('#exit-zen').onclick=toggleZen;$('#photo').onclick=()=>{ocean?.screenshot();toast('바다의 순간을 저장했습니다.');};$('#mission-button').onclick=()=>panel('jobs');$('#chart-open').onclick=()=>panel('chart');$('#throttle').oninput=e=>{state.throttle=Number(e.target.value)/100;setAuto(false);};$('#pause').onclick=togglePause;$('#time-speed').onclick=()=>{simSpeed=simSpeed===1?5:simSpeed===5?20:1;$('#time-speed').textContent='항해 '+simSpeed+'×';};
window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select,[contenteditable=true]')||$('#panel').open)return;const k=e.key.toLowerCase();if(['w','a','s','d',' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys[k]=true;if(e.repeat)return;if(k===' ')toggleAnchor();if(k==='p')setAuto(!autopilot);if(k==='h')toggleZen();if(k==='c'&&ocean){ocean.cameraMode=1-ocean.cameraMode;ocean.orbit=0;}if(k==='escape'&&zen)toggleZen();});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);window.addEventListener('blur',()=>keys={});
for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.key]=false;}
window.addEventListener('pagehide',save);setInterval(save,15000);
const map=$('#map').getContext('2d');
function drawMap(){const w=260,h=180,scale=.066;map.clearRect(0,0,w,h);map.strokeStyle='rgba(166,214,212,.12)';map.lineWidth=1;for(let x=0;x<w;x+=26){map.beginPath();map.moveTo(x,0);map.lineTo(x,h);map.stroke();}for(let y=0;y<h;y+=26){map.beginPath();map.moveTo(0,y);map.lineTo(w,y);map.stroke();}const project=p=>[w/2+(p.x-state.x)*scale,h/2+(p.z-state.z)*scale];map.fillStyle='#4d7670';for(const o of ocean?.obstacles||[]){const [x,y]=project(o);map.beginPath();map.ellipse(x,y,o.radius*scale,o.radius*scale*.8,0,0,Math.PI*2);map.fill();}if(region.layout==='river'){map.fillRect(0,0,w/2+(-310-state.x)*scale,h);const x=w/2+(310-state.x)*scale;map.fillRect(x,0,w-x,h);}
 if(mission){const [x,y]=project(mission);map.setLineDash([3,4]);map.strokeStyle='#e7be7d';map.beginPath();map.moveTo(w/2,h/2);map.lineTo(x,y);map.stroke();map.setLineDash([]);}
 for(const p of ports){const [x,y]=project(p);map.strokeStyle='#a9dcd1';map.beginPath();map.arc(x,y,4,0,Math.PI*2);map.stroke();map.font='10px sans-serif';map.fillStyle='#d1e1dc';map.fillText(p.name,x+8,y+3);}map.save();map.translate(w/2,h/2);map.rotate(state.heading);map.beginPath();map.moveTo(0,-8);map.lineTo(5,6);map.lineTo(0,3);map.lineTo(-5,6);map.closePath();map.fillStyle='#f4d19a';map.fill();map.restore();map.fillStyle='#c3d7d5';map.font='11px sans-serif';map.fillText('N ↑',w-29,16);}
let last=performance.now(),t=0,uiTimer=0;
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;const active=started&&!paused&&!$('#panel').open&&!document.hidden;if(!paused)t+=dt;
 const wp=weatherPresets[weather],wind=region.wind*wp.wind,strength=region.wave*wp.wave;
 if(active){for(let substep=0;substep<simSpeed;substep++){let input={throttle:(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0),steer:(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0)};if(input.steer||input.throttle)setAuto(false);
 if(autopilot){state.throttle=.65;if(mission){const dist=Math.hypot(mission.x-state.x,mission.z-state.z);const desired=Math.atan2(mission.x-state.x,-(mission.z-state.z));const diff=Math.atan2(Math.sin(desired-state.heading),Math.cos(desired-state.heading));input.steer=clamp(diff*2,-1,1);const stopping=state.speed/(spec.accel*.18)+85;if(dist<stopping)state.throttle=.08;if(dist<80){state.throttle=0;state.anchored=true;if(canDock(state,mission))settle();}}}
 stepVessel(state,spec,{wind,river:region.layout==='river'},dt,input);if(applyBoundary(state,region,ocean?.obstacles||[])&&t-lastCollision>3){lastCollision=t;setAuto(false);state.throttle=0;toast('해안에 닿았습니다. 후진해서 안전한 수로로 이동하세요.');}
 }}
 if(!paused)ocean?.update(state,t,dt,strength);audio.update(t,paused?0:state.speed,wind,spec.id==='yacht');
 uiTimer+=dt;if(uiTimer>.12){uiTimer=0;$('#speed').textContent=(Math.abs(state.speed)/.5144).toFixed(1);$('#heading').textContent=String(((Math.round(state.heading*180/Math.PI)%360)+360)%360).padStart(3,'0')+'°';$('#throttle-value').textContent=Math.round(state.throttle*100)+'%';if(document.activeElement!==$('#throttle'))$('#throttle').value=Math.round(state.throttle*100);$('#distance').innerHTML=(state.distance/1852).toFixed(2)+' <small>nm</small>';$('#coordinates').textContent=(region.lat-state.z/111320).toFixed(4)+'° N / '+(region.lon+state.x/(111320*Math.cos(region.lat*Math.PI/180))).toFixed(4)+'° E';if(mission)$('#mission-status').textContent=mission.name+'까지 '+Math.round(Math.hypot(state.x-mission.x,state.z-mission.z))+' m';drawMap();}
}
refresh();requestAnimationFrame(animate);
