import {SOUND_SIGNALS} from './sound-signals.js';
import {bindRaceSteering} from './race-controls.js';
import {stopAtCircles,stopAtBoundary} from './collision.js';
import {stepRaceFeatures,resolveRaceCollision} from './race-course.js';
import {newFishing,castFishing,strikeFishing,stepFishing,newRace,stepRace,restoreLeisure} from './leisure.js';
import {LeisureScene} from './leisure-scene.js';
import {TRAINING_STEPS,trainingQuestion,newTraining,answerTraining,advanceTraining,practiceTraining,trainingScore,restoreTrainingBook} from './training-voyage.js';
import {SOURCES,courses,practices,restoreAcademy,answerCourse,startPractice,stepPractice} from './academy.js';
import {applyImpact,repairTap,repairByCrew,rescueRoute,recoveryPose,restorePropulsion} from './damage.js';
import {WEATHER,createWeather,stepWeather} from './weather.js';
import {lessons,RULES_URL,restoreSchool,beginWatch,observeWatch,stepWatch,watchHint} from './watch-school.js';
import {contactSolution,towEnd} from './traffic.js';
import {stepTraffic,trafficAdvisory} from './traffic.js';
import {tripSnapshot,restoreTrip} from './trip-save.js';
import {countries,seaGate} from './harbor-data.js';
import {makeMission,localMission,missionTarget,bearingTo,recommendedDestinations} from './missions.js';
import {loadAtlas,drawAtlas} from './atlas.js';
import './style.css';
import {ships,regions,portLocations} from './data.js';
import {createVessel,stepVessel,canDock,applyBoundary,clamp} from './physics.js';
import {emptyCargo,cargoUnits,cargoPreset,stability,stepAttitude,canHandleCargo,liquidShip,BAY_NAMES} from './stability.js';
import {OceanScene} from './scene.js';
import {SeaAudio} from './audio.js';
import {planRoute} from './navigation.js';
import {officerPortrait} from './bridge.js';
import {helmMarkup,bindWheel,drawRadar} from './helm.js';
import {drawStability,lessonText} from './education.js';
const $=s=>document.querySelector(s);
let saved={};try{saved=JSON.parse(localStorage.getItem('yoonseul-save')||'{}')||{};}catch{}
let credits=Number.isFinite(saved.credits)&&saved.credits>=0?saved.credits:0;
let totalDistance=Number.isFinite(saved.distance)?saved.distance:0,deliveries=Number.isFinite(saved.deliveries)?saved.deliveries:0;
let region=regions.find(r=>r.id===(saved.mode?saved.region:'busan'))||regions.find(r=>r.id==='busan'),spec=ships.find(s=>s.id===saved.ship)||ships.find(s=>s.id==='container');
if(region.layout==='river'&&spec.draft>region.depth)spec=ships.find(s=>s.id==='yacht');
let state=createVessel(),cargo=emptyCargo(),simSpeed=3,weather='dynamic',timeMode='sunset';
let started=false,paused=false,zen=false,autopilot=false,mission=null,handling=null,ports=[],keys={},tab='menu',lastCollision=-100;
let fleetFilter='all',helmTarget=0,radarRange=3200,gameMode=saved.mode==='free'?'free':'mission',mapFilter='all',completedMission=null,routeKey='',routeChecked=-10;
let route=[],t=0,lesson=null,info=stability(spec,cargo),ocean;
let rescueCall=null,damageNotice=false,recoveryPending=false,recoveryRetryAt=0,voyagePace=3;
let school=restoreSchool(saved.school),watchTask=null,quizFeedback={},trafficReplanAt=-100;
let academy=restoreAcademy(saved.academy),academyGrade=4,academyOpen='',academyFeedback={},academyTask=null;
let trainingBook=restoreTrainingBook(saved.training),trainingFeedback='';
let activity=null,leisureView,leisureBook=restoreLeisure(saved.leisure?.courseVersion===3?saved.leisure:{fish:saved.leisure?.fish});
const audio=new SeaAudio(),weatherState=createWeather();
$('#app').innerHTML=`
<button id="sail-toggle" class="hud" hidden aria-pressed="false">돛 펼치기</button><div id="ocean" aria-label="3D 항해 화면"></div><div class="vignette"></div>
<header class="topbar hud"><a class="brand" href="#" aria-label="윤슬"><span>≋</span> 윤슬</a><div class="location"><span id="region-title"></span><small id="place-name"></small></div><div class="top-actions"><button id="signal-toggle" aria-label="고동과 VHF 소리" aria-expanded="false" aria-controls="signal-panel">♪</button><button id="instruments-toggle" aria-pressed="false" aria-label="상세 계기와 조타 표시">계기</button><button id="camera-toggle" aria-label="1인칭 브릿지로 전환">1인칭 브릿지</button><button id="menu" aria-label="항해 메뉴 열기"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg><span>메뉴</span></button></div></header>
<section id="signal-panel" hidden aria-label="고동과 VHF 소리"><div class="signal-heading"><strong>바다 소리</strong><button id="signal-close" aria-label="소리 메뉴 닫기">×</button></div><div class="signal-options">${Object.entries(SOUND_SIGNALS).map(([id,cue])=>`<button data-signal="${id}">${cue.name}</button>`).join('')}</div><div class="signal-footer"><span id="signal-status" role="status">눌러서 바로 듣기</span><button id="signal-stop">정지</button></div></section><div id="voyage-hint" class="hud"><small id="mission-stage"></small><span id="mission-status">출항 준비 완료</span><div class="mission-next"><span id="mission-nav"></span><button id="mission-action" hidden></button></div></div>
<button id="weather-readout" class="hud" aria-label="날씨와 해상 상태 설정"></button><div id="sea-watch" class="hud" role="status" hidden></div><div id="watch-task" class="hud" hidden><span id="watch-task-text"></span><button id="watch-observe">표적 확인</button><button id="watch-details" aria-label="항해 실습 수첩 열기">수첩 ↗</button></div>${helmMarkup(officerPortrait)}
<div class="keyboard-hint hud">W / S 레버 &nbsp; A / D 조타 &nbsp; C 시점 &nbsp; Space 출항·정박 <button id="time-speed">항해 3×</button><button id="pause">일시정지</button></div>
<button id="training-chip" class="hud" hidden aria-label="승선 실습 항차 열기"></button><button id="exit-zen" hidden>항해 화면으로</button><div id="toast" role="status"></div>
<div id="race-steering" class="hud" role="group" aria-label="레이싱 방향 조작"><button id="race-left" aria-label="왼쪽으로 조향, 누르는 동안 회전"><span aria-hidden="true">❮</span><small>왼쪽</small></button><button id="race-right" aria-label="오른쪽으로 조향, 누르는 동안 회전"><span aria-hidden="true">❯</span><small>오른쪽</small></button></div><section id="leisure-hud" class="hud" hidden aria-label="바다 놀이"><div class="leisure-top"><span id="leisure-label"></span><button id="leisure-more" aria-expanded="false">더보기</button><button id="leisure-exit" aria-label="홈 화면으로 돌아가기">홈</button></div><strong id="leisure-status"></strong><p id="leisure-detail"></p><div id="fishing-gauges" hidden><label>줄 장력 <meter id="line-tension" min="0" max="1" low=".18" high=".8" optimum=".5"></meter></label><label>끌어올리기 <progress id="fish-progress" max="1"></progress></label></div><button id="leisure-action"></button><details id="fish-journal"><summary>나의 어획 기록</summary><div id="fish-journal-list"></div></details><div id="catch-choice" hidden><button id="fish-release">기록하고 놓아주기</button><button id="fish-keep">어획 기록에 담기</button></div></section>
<div id="leisure-launchers" class="hud"><button data-leisure="fishing">낚시하며 쉬기</button><button data-leisure="race">파도 위 레이싱</button></div><div id="welcome"><div class="welcome-content"><span class="welcome-kicker">윤슬</span><h1>바다로.</h1><p>오늘은 어떤 바다를 만나볼까요.</p><div class="welcome-modes"><button data-start-mode="mission">미션 항해</button><button data-start-mode="free">자유 항해</button></div><button id="start">첫 화물 미션 시작 <span>↗</span></button><button id="start-training">항해 배우기</button><div class="welcome-play"><button data-leisure="fishing"><b>낚시하며 쉬기</b><span>입질을 기다리는 작은 어선</span></button><button data-leisure="race"><b>파도 위 레이싱</b><span>수상오토바이 타임 트라이얼</span></button></div><small>한국 · 중국 · 일본 / 24개 해역 · 75개 작업 수역</small></div></div>
<dialog id="panel"><div class="panel-head"><button id="panel-back" aria-label="항해 메뉴로">‹</button><h2 id="panel-title"></h2><button id="close-panel" aria-label="닫기">✕</button></div><div id="panel-body"></div></dialog>
<section id="damage-panel" class="hud" hidden aria-label="선체 손상과 복구"><div class="damage-head"><strong id="damage-title">선체 손상</strong><button id="damage-close" aria-label="손상 안내 접기">✕</button></div><progress id="hull-health" max="100" value="100" aria-label="선체 내구도"></progress><p id="damage-status" role="status"></p><div class="damage-actions"><button id="repair-tap">🔧 응급 수리 +8%</button><button id="call-rescue">해양경찰 요청</button><button id="incident-guide">사고 대응 배우기</button></div><small>수리 후 안전 수역에서 자동 전진 · 게임용 복구</small></section><button id="damage-open" class="hud" hidden>선체 상태</button>
<div id="rescue" hidden><h2>배가 크게 기울었습니다</h2><p>높거나 편중된 화물을 낮고 고르게 배치해 보세요.<br/>이 게임의 복원력 모델은 큰 각도의 실제 거동을 재현하지 않습니다.</p><button id="recover">항구로 복귀 · 안전하게 다시 적재</button></div><div id="error" hidden></div>`;
try{ocean=new OceanScene($('#ocean'));ocean.setShip(spec);ports=ocean.setRegion(region);leisureView=new LeisureScene(ocean.scene);}catch(error){$('#error').hidden=false;$('#error').textContent='3D 화면을 시작할 수 없습니다. 하드웨어 가속을 켠 Chrome 또는 Edge에서 다시 열어 주세요.';console.error(error);}
function atBerth(){return canHandleCargo(state,ports);}
function spawnAtPort(){state.x=ports[0]?.x||0;state.z=(ports[0]?.z||0)+46;state.anchored=true;syncAnchor();}
function save(){try{localStorage.setItem('yoonseul-save',JSON.stringify({leisure:{...leisureBook,courseVersion:3},school,academy,training:trainingBook,credits,distance:totalDistance+state.distance,deliveries,ship:spec.id,region:region.id,mode:gameMode,trip:tripSnapshot(region,spec,state,cargo,mission,completedMission)}));}catch{}}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function refresh(){routeKey='';info=stability(spec,cargo);$('#region-title').textContent=region.name;$('#place-name').textContent=region.label;syncCamera();syncAnchor();}
function syncAnchor(){$('#anchor').classList.toggle('active',state.anchored);$('#anchor .anchor-label').textContent=state.anchored?'출항':'정박';$('#anchor').setAttribute('aria-label',state.anchored?'출항: 닻을 올리고 전진':'정박: 닻을 내려 멈추기');}
function commandThrottle(value){if(activity?.type==='fishing'&&['waiting','bite','reeling'].includes(activity.run.phase))return toast('채비를 회수한 뒤 이동하세요.');if(activity?.type==='race'&&activity.run.phase!=='racing')return;if(rescueCall)return toast('구조 작업 중입니다. 수리를 기다려 주세요.');if(handling||state.capsized){toast(handling?'화물 작업이 끝나면 출항할 수 있어요.':'항구로 복귀한 뒤 다시 출항하세요.');return;}state.throttle=clamp(value,-.3,1);if(Math.abs(state.throttle)>.025){if(state.anchored){state.anchored=false;syncAnchor();toast('닻을 올렸습니다. 출항합니다.');}if(paused){paused=false;$('#pause').textContent='일시정지';}}setAuto(false);}
function finishRecovery(){
 const pose=recoveryPose(state,spec,routingObstacles(),(x,z)=>ocean.groundHeight(x,z),ocean.world.contacts,region.layout==='river');
 if(!pose){recoveryPending=true;state.anchored=true;state.throttle=0;syncAnchor();return false;}
 restorePropulsion(state,pose);recoveryPending=false;helmTarget=0;keys={};setWheel(0);setAuto(false);simSpeed=Math.max(3,voyagePace);paused=false;$('#pause').textContent='일시정지';$('#time-speed').textContent=`항해 ${simSpeed}×`;syncAnchor();routeKey='';ocean.rescueTarget=null;setCamera(0);ocean.orbit=-.38;ocean.cameraSnap=true;damageNotice=false;save();toast('복구 완료 · 안전 수역에서 전진 65%로 항해를 재개합니다.');return true;
}
function recordImpact(speed){if(activity?.type==='race'&&activity.run.phase==='racing'){if(t-(activity.hitAt??-10)>2){activity.run.penalty+=3;activity.hitAt=t;toast('접촉으로 정지했습니다 · +3초. 조타와 후진 레버로 벗어나세요.');}state.speed=0;state.throttle=0;return;}const previousDamage=state.damage;const loss=applyImpact(state,speed,t);if(!loss)return;if(!previousDamage)voyagePace=simSpeed;if(trainingBook.run)trainingBook.run.incidents++;if(zen)toggleZen();damageNotice=true;simSpeed=1;audio.collision?.();setAuto(false);toast(`선체 손상 +${Math.round(loss)} · 기관 정지, 인명·침수·복원성 확인 후 지원을 요청하세요.`);save();}
$('#repair-tap').onclick=()=>{if(rescueCall)return;if(paused){paused=false;$('#pause').textContent='일시정지';}if(Math.abs(state.speed)>1.4){state.throttle=0;state.anchored=true;syncAnchor();toast('게임 정지 보조 작동 · 멈춘 뒤 응급 수리를 누르세요.');return;}if(repairTap(state,t)){syncAnchor();if(!state.damage)finishRecovery();save();}};
$('#incident-guide').onclick=()=>{academyGrade=3;academyOpen='3-emergency';openPanel('academy');};
$('#damage-close').onclick=()=>damageNotice=false;$('#damage-open').onclick=()=>damageNotice=true;
$('#call-rescue').onclick=()=>{if(rescueCall||!state.damage)return;if(paused){paused=false;$('#pause').textContent='일시정지';}const path=rescueRoute(state,ocean.obstacles,(x,z)=>region.layout==='river'&&Math.abs(x)>260?10:ocean.groundHeight(x,z));if(!path){toast('구조정 접근 수로가 없습니다. 응급 수리를 완료하면 안전 수역으로 자동 복구됩니다.');return;}setAuto(false);simSpeed=1;state.speed=0;state.throttle=0;state.anchored=true;syncAnchor();const c={id:'coastguard-rescue',kind:'coastguard',name:'해양경찰 구조정 · 접근 중',...path[0],rescuePath:path,radius:18,heading:0,speed:16,status:'responding',trail:[]};ocean.world.contacts=ocean.world.contacts.filter(v=>v.id!==c.id);ocean.world.contacts.push(c);ocean.living.syncContacts(ocean.world);rescueCall=c;ocean.rescueTarget=c;damageNotice=true;setCamera(0);ocean.orbit=Math.atan2(c.x-state.x,-(c.z-state.z))-state.heading+.35;ocean.lookPitch=.18;ocean.cameraSnap=true;toast('게임 속 구조정이 출동했습니다. 청색 표적을 확인하세요.');};
function commandSteer(value){if(handling||state.capsized)return;helmTarget=value;setAuto(false);}
const setWheel=bindWheel($('#steering-wheel'),commandSteer);
const raceSteering=bindRaceSteering([$('#race-left'),$('#race-right')],value=>{if(activity?.type==='race')commandSteer(value);},()=>activity?.type==='race'&&activity.run.phase==='racing'&&!paused&&!$('#panel').open);
$('#center-wheel').onclick=()=>{commandSteer(0);setWheel(0);};
$('#weather-readout').onclick=()=>openPanel('settings');
$('#radar').onclick=e=>{
 if(!ocean?.world||watchTask)return;const rect=e.currentTarget.getBoundingClientRect(),x=((e.clientX-rect.left)/rect.width*320-160)*radarRange/143+state.x,z=((e.clientY-rect.top)/rect.height*320-160)*radarRange/143+state.z;
 const nearest=ocean.world.contacts.filter(c=>!['whale','shark'].includes(c.kind)&&Math.hypot(c.x-state.x,c.z-state.z)<=radarRange).sort((a,b)=>Math.hypot(a.x-x,a.z-z)-Math.hypot(b.x-x,b.z-z))[0];
 ocean.world.trackedId=nearest&&Math.hypot(nearest.x-x,nearest.z-z)<radarRange*.13?nearest.id:null;
};
$('#radar-range').onclick=()=>{radarRange=({400:800,800:1600,1600:3200,3200:6400,6400:400})[radarRange];$('#radar-range').textContent=radarRange+' m';};

function syncCamera(){const bridge=ocean?.cameraMode===1;document.body.classList.toggle('bridge-view',bridge);$('#camera-toggle').textContent=bridge?'3인칭 선박':'1인칭 브릿지';$('#camera-toggle').setAttribute('aria-label',bridge?'3인칭 선박으로 전환':'1인칭 브릿지로 전환');}
function setCamera(mode){ocean?.setCamera(mode);syncCamera();}
function reset(){endLeisure();if(ocean)ocean.rescueTarget=null;if(ocean?.world){ocean.world.contacts=ocean.world.contacts.filter(c=>c.kind!=='coastguard');ocean.living.syncContacts(ocean.world);}rescueCall=null;damageNotice=false;cancelTraining();academyTask=null;recoveryPending=false;voyagePace=3;trafficReplanAt=-100;watchTask=null;if(ocean?.world)ocean.world.trackedId=null;totalDistance+=state.distance;state=createVessel();helmTarget=0;setWheel(0);cargo=emptyCargo();mission=null;handling=null;lesson=null;autopilot=false;simSpeed=3;$('#time-speed').textContent='항해 3×';$('#autopilot').classList.remove('active');spawnAtPort();completedMission=null;if(gameMode==='mission')mission=localMission(region,state,spec);$('#rescue').hidden=true;refresh();save();}
function openPanel(name){if(activity?.type==='fishing')activity.run.held=false;if(name==='chart'||name==='cargo')tickTraining(0,name);tab=name;keys={};raceSteering.reset();if(!$('#panel').open)$('#panel').showModal();renderPanel();}
function closePanel(){$('#panel').close();keys={};}
function bind(selector,event,fn){const el=$(selector);if(el)el[event]=fn;}
function jobTarget(){return missionTarget(mission,region);}
function setMode(mode){endLeisure();if(trainingBook.run&&mode!==gameMode)cancelTraining();if(handling)return toast('화물 작업이 끝난 뒤 모드를 바꿀 수 있어요.');gameMode=mode;setAuto(false);route=[];routeKey='';completedMission=null;mission=mode==='mission'?localMission(region,state,spec):null;save();if($('#panel').open)renderPanel();syncWelcomeModes();}
function syncWelcomeModes(){document.querySelectorAll('[data-start-mode]').forEach(b=>b.classList.toggle('chosen',b.dataset.startMode===gameMode));$('#start').innerHTML=(gameMode==='mission'?(mission&&mission.phase!=='loading'?'미션 이어하기':completedMission?'다음 항해 시작':'첫 화물 미션 시작'):'자유롭게 승선하기')+'';}
function acceptContract(destination,index=0){if(handling)return toast('진행 중인 화물 작업을 마쳐 주세요.');endLeisure();cancelTraining();const nearest=localMission(region,state,spec).origin;const originIndex=ports.findIndex(p=>p.id===nearest.id);mission=makeMission(region,destination,Math.max(0,originIndex),index,spec);gameMode='mission';completedMission=null;setAuto(false);route=[];routeKey='';save();renderPanel();toast('금색 표시에서 화물을 싣고 레이더 항로를 따라가세요.');}
function crossSea(){if(rescueCall)return toast('구조 작업을 마친 뒤 해역을 이동하세요.');if(!mission||mission.destinationRegion===region.id||mission.phase==='loading'||!state.anchored||!canDock(state,jobTarget()))return;const next=regions.find(r=>r.id===mission.destinationRegion);if(!next)return;region=next;if(trainingBook.run)trainingBook.run.region=region.id;trafficReplanAt=-100;watchTask=null;ports=ocean.setRegion(region);const gate=seaGate(region);state.x=gate.x;state.z=gate.z;state.heading=Math.PI;state.speed=0;state.throttle=0;state.anchored=true;helmTarget=0;mission.phase='sailing';route=[];routeKey='';autopilot=false;ocean.cameraSnap=true;refresh();save();toast('외해 구간 압축 이동 · '+region.name+' 입항 수역입니다. 레이더로 부두를 찾아가세요.');}
function routingObstacles(){return (ocean?.obstacles||[]).map(o=>o.hazard?{...o,radius:o.radius+65}:o);}
function updateRoute(){if(!mission){route=[];ocean?.setDestination(null);return;}const target=jobTarget(),key=region.id+mission.phase+target.name;if(key!==routeKey||(t-routeChecked>3&&route.length&&Math.hypot(state.x-route[0].x,state.z-route[0].z)>2000)){route=planRoute(state,target,routingObstacles(),spec.beam*.5+50)||[];routeKey=key;routeChecked=t;}while(route.length>1&&Math.hypot(state.x-route[0].x,state.z-route[0].z)<45)route.shift();ocean?.setDestination(target);}

const escapeText=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function trainingContext(dt=0){const st=stability(spec,cargo),target=mission?(mission.destinationRegion===region.id?mission:seaGate(region)):ports[0];return {...st,state,wind:weatherState.wind,grade:trainingBook.run?.grade||academyGrade,region:region.id,ship:spec.id,distance:target?Math.hypot(target.x-state.x,target.z-state.z):0,deliveries,manual:!autopilot,stable:st.status==='안정',tracked:ocean?.world.contacts.find(c=>c.id===ocean.world.trackedId),dt};}
function cancelTraining(){if(trainingBook.run?.weatherBefore){weather=trainingBook.run.weatherBefore;}trainingBook.run=null;trainingFeedback='';}
function finishTraining(){const run=trainingBook.run;if(!run||run.status!=='complete')return;const score=trainingScore(run);trainingBook.xp+=score;trainingBook.log.unshift({score,date:new Date().toISOString().slice(0,10),grade:run.grade,firstTry:run.firstTry,incidents:run.incidents});trainingBook.log=trainingBook.log.slice(0,8);cancelTraining();save();toast(`실습 항차 완료 · ${score} XP · 복기 기록을 확인하세요.`);}
function tickTraining(dt,event){const run=trainingBook.run;if(!run)return;if(run.region!==region.id||run.ship!==spec.id){cancelTraining();return;}if(practiceTraining(run,trainingContext(dt),event)){if(run.phase===4&&run.weatherBefore){weather=run.weatherBefore;run.weatherBefore=null;}advanceTraining(run,trainingContext());trainingFeedback='';save();toast(run.status==='review'?'항차 실습 완료 · 틀렸던 문제를 다시 확인하세요.':'실습 단계 완료 · 다음 상황 판단을 열어보세요.');finishTraining();}}
function trainingMarkup(){const run=trainingBook.run,step=run&&TRAINING_STEPS[run.phase],q=run&&(run.status==='review'?run.review[0]:run.question);return `<div class="academy-intro"><p class="fine">승선 실습 항차</p><h3>판단하고, 운항하고,<br>결과로 배우기.</h3><p>거리와 시간을 계산하고 화물을 확인한 뒤 직접 조타·관측·감속해 목적지에 인도하세요.</p><div class="log-row"><span>항차 경험 ${trainingBook.xp} XP</span><span>완료 ${trainingBook.log.length}회</span></div></div>
 <ol class="training-route">${TRAINING_STEPS.map((s,i)=>`<li class="${run?(i<run.phase?'done':i===run.phase?'current':''):''}"><b>${i+1}</b><span>${s.name}<small>${s.subject}</small></span></li>`).join('')}</ol>
 ${run?`<div class="training-current"><small>${run.status==='review'?'항차 마무리 · 오답 재확인':step?.subject||''}</small><h3>${run.status==='review'?'다시 풀어 내 것으로':step?.name||''}</h3>${run.status==='question'||run.status==='review'?`<p>${escapeText(q.prompt)}</p><details class="science-note"><summary>생각하는 데 도움이 필요해요</summary><p>${escapeText(q.hint)}</p></details>${q.kind==='number'?`<label class="training-number">계산 결과 (${q.unit})<input id="training-number" inputmode="decimal" type="number" step="0.01" placeholder="숫자를 입력하세요"><button id="training-answer">판단 확인</button></label>`:`<div class="quiz-options">${q.options.map((o,i)=>`<button data-training-answer="${i}">${o}</button>`).join('')}</div>`}`:`<p>${step.action}</p><div class="training-instruments"><span>속력 <b>${(Math.abs(state.speed)/.5144).toFixed(1)} kn</b></span><span>GM <b>${stability(spec,cargo).gm.toFixed(2)} m</b></span><span>진행 <b>${run.seconds.toFixed(0)}초</b></span></div><button class="training-primary" id="training-sail">${run.phase===0?'항해도 확인':run.phase===1?'화물·복원력 열기':'직접 운항하기'}</button>`}${trainingFeedback?`<p class="quiz-feedback" role="status">${escapeText(trainingFeedback)}</p>`:''}<button id="training-cancel" class="fine">실습 항차 종료 · 기존 운송 미션 유지</button></div>`:`<div class="academy-practice"><strong>6단계 실습 · 학습용 항차</strong><p>현재 운송 미션으로 시작합니다. 기상 단계에서는 바람과 파도가 강해지고, 감속을 마치면 원래 날씨로 돌아갑니다. 운송 보상과 별도로 최대 90 XP를 받습니다.</p><label>문제 난이도 <select id="training-grade">${[4,3,2,1].map(g=>`<option value="${g}">${g}급 연계</option>`).join('')}</select></label><button id="training-begin">실습 항차 시작</button></div>`}
 ${trainingBook.log.length?`<h3>최근 항차 복기</h3>${trainingBook.log.map(l=>`<div class="school-log"><b>${l.date} · ${l.score} XP</b><p>첫 판단 정답 ${l.firstTry}/6 · 실습 6/6 · 접촉 ${l.incidents}회</p><small>${l.incidents?'다음 항차에서는 미리 감속하고 주변 여유를 확보하세요.':'다음에는 다른 선박으로 같은 원리를 적용해 보세요.'}</small></div>`).join('')}`:''}
 <p class="fine">해사고 항해과의 항해·레이더·선박 운용·선화 운송 학습에 연결한 창작 실습입니다. 실제 기출 복제나 학교 교육과정 전체, 공인 해기사 훈련을 대체하지 않습니다. 배속과 조작 목표는 게임 기준입니다.</p><a class="fleet-source" href="https://www.jne.go.kr/upload/sse/na/bbs_377/ntt_5070060/doc_856224bd-9672-4a30-b919-c89abbf5790a1692a9285b32574.pdf" target="_blank" rel="noreferrer">교육과정 참고 · 선박 운항 pp.260–262 ↗</a>`;}
function bindTraining(body){bind('#training-begin','onclick',()=>{if(handling)return toast('화물 작업을 마친 뒤 시작하세요.');endLeisure();academyGrade=Number($('#training-grade').value);gameMode='mission';if(!mission)mission=localMission(region,state,spec);trainingBook.run=newTraining(trainingContext());trainingFeedback='';save();renderPanel();});
 const answer=value=>{const run=trainingBook.run;if(!run)return;const result=answerTraining(run,value);if(!result)return;trainingFeedback=`${result.correct?'판단 확인.':'다시 생각해 보세요.'} ${result.explain}`;if(result.correct&&run.phase===4&&run.status==='practice'){run.weatherBefore=weather;weather='rough';}finishTraining();save();renderPanel();};
 body.querySelectorAll('[data-training-answer]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.trainingAnswer)));bind('#training-answer','onclick',()=>answer($('#training-number').value));bind('#training-number','onkeydown',e=>{if(e.key==='Enter')answer(e.target.value);});
 if(trainingBook.run)requestAnimationFrame(()=>$('#panel').open&&tab==='training'&&$('.training-current')?.scrollIntoView({block:'start'}));bind('#training-cancel','onclick',()=>{cancelTraining();save();renderPanel();});bind('#training-sail','onclick',()=>{const phase=trainingBook.run.phase;if(phase===0)openPanel('chart');else if(phase===1)openPanel('cargo');else closePanel();});}
function academyMarkup(){const list=courses.filter(c=>c.grade===academyGrade),xp=academy.passed.length*10+academy.practiced.length*20;
 return `<div class="academy-intro"><p class="fine">항해 수첩 · 개념을 이해하고 직접 운항하기</p><h3>오늘의 항해가<br>내일의 실력이 되도록.</h3><p>문제를 풀고 실제 조타·감속·레이더·적재 실습을 완료하세요.</p><div class="log-row"><span>학습 ${xp} XP</span><span>개념 ${academy.passed.length}/16 · 실습 ${academy.practiced.length}/16</span></div></div>
 <div class="academy-grades" role="group" aria-label="학습 급수">${[4,3,2,1].map(g=>`<button data-grade="${g}" aria-pressed="${g===academyGrade}">${g}급<small>${{4:'기초 조작',3:'당직 판단',2:'응용 운용',1:'종합 판단'}[g]}</small></button>`).join('')}</div>
 <p class="fine">상선 항해사 1~4급 시험은 항해·운용·법규·영어·상선전문으로 구성됩니다. 아래 급수별 난이도 배치는 게임 자체 구성입니다. 공식 기출·전 범위 대비·면허 평가 과정은 아닙니다.</p>
 ${academyTask?`<div class="academy-practice"><strong>진행 중 · ${practices[academyTask.kind].title}</strong><p>${practices[academyTask.kind].text}</p><button id="academy-return">항해로 돌아가기</button><button id="academy-cancel">실습 취소</button></div>`:''}
 ${list.map(c=>`<details class="lesson-card" data-course="${c.id}" ${academyOpen===c.id?'open':''}><summary>${academy.passed.includes(c.id)?'✓':'○'} ${c.title}<small>${c.subject}${academy.practiced.includes(c.id)?' · 실습 완료':''}</small></summary><p>${c.question}</p><div class="quiz-options">${c.options.map((o,i)=>`<button data-course-answer="${c.id}" data-choice="${i}">${o}</button>`).join('')}</div>${academyFeedback[c.id]?`<p class="quiz-feedback" role="status">${academyFeedback[c.id]}</p>`:''}${academy.passed.includes(c.id)?`<div class="academy-practice"><strong>승선 실습 · ${practices[c.practice].title}</strong><p>${practices[c.practice].text}</p><button data-practice="${c.id}">${academy.practiced.includes(c.id)?'다시 연습':'실습 시작 · +20 XP'}</button></div>`:''}<a href="${SOURCES[c.source][1]}" target="_blank" rel="noreferrer">${SOURCES[c.source][0]} ↗</a></details>`).join('')}
 <p class="fine">정답은 처음 +10 XP, 실습 완료는 처음 +20 XP. 오답은 해설을 읽고 재도전할 수 있습니다. 기록은 이 브라우저에 저장됩니다.</p><a class="fleet-source" href="${SOURCES.exam[1]}" target="_blank" rel="noreferrer">공식 시험 과목 확인 ↗</a><button class="school-entry" data-panel="school"><span>당직 항해 실습</span><small>COLREG · 주변 선박 안전 통과</small></button>`;
}
function bindAcademy(body){
 body.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>{academyGrade=Number(b.dataset.grade);academyOpen='';renderPanel();});
 body.querySelectorAll('[data-course-answer]').forEach(b=>b.onclick=()=>{const id=b.dataset.courseAnswer,c=courses.find(c=>c.id===id),ok=answerCourse(academy,id,Number(b.dataset.choice));academyOpen=id;academyFeedback[id]=`${ok?'정답 · 개념 확인 완료.':'다시 생각해 보세요.'} ${c.explain}`;save();renderPanel();});
 body.querySelectorAll('[data-practice]').forEach(b=>b.onclick=()=>{const c=courses.find(c=>c.id===b.dataset.practice);academyTask=startPractice(c.id,state,stability(spec,cargo).gm);closePanel();toast(practices[c.practice].text);});
 bind('#academy-return','onclick',closePanel);bind('#academy-cancel','onclick',()=>{academyTask=null;renderPanel();});
}
function updateAcademy(dt,cargoChanged=false){if(!academyTask)return;const tracked=ocean.world.contacts.find(c=>c.id===ocean.world.trackedId);if(stepPractice(academyTask,state,{gm:stability(spec,cargo).gm,tracked,dt,manual:!autopilot,cargoChanged})){const id=academyTask.id,fresh=!academy.practiced.includes(id);if(fresh)academy.practiced.push(id);academyTask=null;save();toast(`실습 완료${fresh?' · +20 XP':''} · 해기사 학습 수첩에 기록했습니다.`);}}
function schoolMarkup(){const nearby=(ocean?.world?.contacts||[]).filter(c=>!['whale','shark','coastguard'].includes(c.kind)).map(c=>contactSolution(c,state,spec.beam)).sort((a,b)=>a.distance-b.distance);
 return `<div class="school-hero"><small>WATCHKEEPER / 항해 입문</small><h3>바다에서 만나고,<br>수첩에서 이해하기.</h3><p>항로에서 만나는 표적을 선택 → 700 m 안에서 표적 확인 → 직접 조타해 안전하게 통과하세요. 일부러 배에 접근할 필요는 없습니다.</p><div class="log-row"><span>안전 통과 <b>${school.log.filter(r=>r.success).length}회</b></span><span>개념 학습 <b>${school.passed.length} / ${lessons.length}</b></span></div></div>
 ${watchTask?`<div class="job-card"><small>진행 중인 관측</small><h3>${escapeText(watchTask.name)}</h3><p>확인 ${watchTask.observed?'완료':'대기'} · 직접 항해 ${Math.round(watchTask.travel)} m</p><button id="watch-cancel">관측 종료</button></div>`:''}
 <h3>주변에서 실습할 표적</h3><p class="fine">선택한 배는 레이더에서 청록색 원으로 표시됩니다. 1×로 관측을 시작합니다. 안전 거리가 줄면 먼저 감속·회피하세요.</p><div class="school-contacts">${nearby.slice(0,8).map(c=>`<button data-watch="${c.id}"><span>${c.name}<small>${watchHint(c)}</small></span><b>${Math.round(c.distance)} m ↗</b></button>`).join('')||'<p>이 해역에는 실습 표적이 없습니다. 항해도에서 바다 항만으로 이동하세요.</p>'}</div>
 <details class="science-note"><summary>실습 기록 기준과 시뮬레이션 범위</summary><p class="fine">게임 기준: 250 m 이상에서 확인, 350 m 안을 통과한 뒤 460 m 밖으로 이격, 직접 항해 120 m 이상, 선체 여유 35 m 이상, 접촉·자동 항해 없이 6분(항해 시간) 이내. 이 수치는 게임 평가용이며 법정 안전거리나 COLREG 적합 판정이 아닙니다. 타선 위치·작업 정보는 관측 보조 표시이며 실제 레이더가 선종·작업을 자동 식별한다는 뜻이 아닙니다. 타선은 임의 순환과 겹침 방지 정지를 사용하며 완전한 국제해상충돌예방규칙 AI가 아닙니다. 등화의 가시 범위·전 신호 체계, 수로·통항분리·제한시계 항법은 재현하지 않습니다. 공인 훈련·자격 평가를 대신하지 않는 입문 게임입니다.</p></details>
 <h3>항해 상황을 읽는 6가지 연습</h3>${lessons.map(l=>`<details class="lesson-card"><summary>${school.passed.includes(l.id)?'✓':'○'} ${l.title}<small>${l.rule}</small></summary><p>${l.question}</p><div class="quiz-options">${l.options.map((o,i)=>`<button data-quiz="${l.id}" data-answer="${i}">${o}</button>`).join('')}</div>${quizFeedback[l.id]?`<p class="quiz-feedback" role="status">${quizFeedback[l.id]}</p>`:''}<a href="${RULES_URL}" target="_blank" rel="noreferrer">국제규칙 원문 확인 ↗</a></details>`).join('')}
 <h3>최근 관측 복기</h3>${school.log.length?school.log.map(r=>`<div class="school-log"><b>${r.success?'✓ 안전 통과':'↻ 다시 연습'} · ${escapeText(r.name)}</b><p>최소 선체 여유 ${r.minClearance} m · 직접 항해 ${r.travel} m</p><small>${escapeText(r.reason||'저장된 관측 기록')}</small></div>`).join(''):'<p class="fine">첫 관측을 시작하면 여기에 결과가 남습니다. 기록은 이 브라우저에 저장됩니다.</p>'}
 <p class="fine">항법 설명은 국제규칙 기준입니다. USCG 문서의 미국 Inland 예외는 적용하지 않았습니다. 실제 운항에는 최신 해도·항행통보·현지 항만 규정이 필요합니다.</p><a class="fleet-source" href="https://www.imo.org/en/ourwork/safety/pages/preventing-collisions.aspx" target="_blank" rel="noreferrer">IMO 항법 설명과 참고 자료 ↗</a>`;
}
function bindSchool(body){body.querySelectorAll('[data-watch]').forEach(b=>b.onclick=()=>{const c=ocean.world.contacts.find(c=>c.id===b.dataset.watch);if(!c)return;watchTask=beginWatch(c,state);ocean.world.trackedId=c.id;simSpeed=1;$('#time-speed').textContent='항해 1×';$('#pace-toggle').textContent='1× 항해';setAuto(false);closePanel();toast('청록색 레이더 표적을 관측하고 표적 확인을 누르세요.');});bind('#watch-cancel','onclick',()=>{watchTask=null;ocean.world.trackedId=null;renderPanel();});body.querySelectorAll('[data-quiz]').forEach(b=>b.onclick=()=>{const l=lessons.find(l=>l.id===b.dataset.quiz),correct=Number(b.dataset.answer)===l.answer;if(correct&&!school.passed.includes(l.id))school.passed.push(l.id);quizFeedback[l.id]=`${correct?'정답입니다.':'다시 생각해 보세요.'} ${l.explain}`;save();const open=[...body.querySelectorAll('details[open]')].map(e=>e.querySelector('summary').textContent.replace(/^[✓○] /,''));renderPanel();body.querySelectorAll('details').forEach(e=>{if(open.includes(e.querySelector('summary').textContent.replace(/^[✓○] /,'')))e.open=true;});});}
function updateWatchUI(){const el=$('#watch-task'),c=watchTask&&ocean?.world?.contacts.find(c=>c.id===watchTask.id);el.hidden=!c;if(!c)return;const s=contactSolution(c,state,spec.beam);$('#watch-task-text').textContent=`${c.name} · ${s.bearing.toFixed(0)}° / ${Math.round(s.distance)} m · CPA ${Math.round(s.cpa)} m · ${s.rawTcpa>0?`TCPA ${Math.round(s.rawTcpa)}초`:'이격/정지'}${watchTask.observed?' · 확인 ✓':''}`;$('#watch-observe').disabled=watchTask.observed||s.distance>700;$('#watch-observe').textContent=watchTask.observed?'확인 ✓':s.distance>700?'700 m 안에서 확인':'표적 확인';}
$('#watch-details').onclick=()=>openPanel('school');
$('#watch-observe').onclick=()=>{if(watchTask&&observeWatch(watchTask,ocean.world.contacts.find(c=>c.id===watchTask.id),state))toast('관측 기록. 레이더와 바깥 경계를 계속하며 직접 조타하세요.');};
function renderPanel(){
 const body=$('#panel-body');$('#panel-title').textContent={menu:'항해 수첩',fleet:'승선할 배',chart:'항해도와 해역',jobs:'운송 의뢰',cargo:'선적 · 하역 · 복원력',settings:'항해 환경',school:'항해 실습 수첩',academy:'해기사 학습 항해',training:'승선 실습 항차'}[tab];$('#panel-back').hidden=tab==='menu';
 if(tab==='menu')body.innerHTML=`<div class="mode-switch"><button data-mode="mission" class="${gameMode==='mission'?'chosen':''}">미션 항해</button><button data-mode="free" class="${gameMode==='free'?'chosen':''}">자유 항해</button></div><div class="menu-play"><button data-leisure="fishing">낚시하며 쉬기</button><button data-leisure="race">파도 위 레이싱</button></div><div class="officer-intro">${officerPortrait}<div><small>당직 항해사</small><h3>${spec.en}</h3><p>${spec.name} · ${region.name}</p></div></div><button class="school-entry" data-panel="training"><span>승선 실습 항차</span><small>계획 → 선적 → 당직 → 입항 · 상황 판단과 실습</small></button><button class="school-entry" data-panel="academy"><span>해기사 학습 항해</span><small>4급~1급 · 해사영어 · 선화운송 · 선박운용</small></button><button class="school-entry" data-panel="school"><span>당직 항해 실습</span><small>타선 관측 · 안전 통과 · COLREG 퀴즈 ↗</small></button><div class="menu-grid"><button data-panel="fleet"><span>⚓</span>선박 선택<small>15척의 서로 다른 실루엣</small></button><button data-panel="chart"><span>⌁</span>항해도<small>한국 · 중국 · 일본</small></button><button data-panel="cargo"><span>▦</span>화물 · 복원력<small>싣고, 기울고, 돌아오고</small></button><button data-panel="jobs"><span>▤</span>운송 의뢰<small>선적부터 하역까지</small></button></div><div class="log-row"><span>항해 수익 <b id="credits">₩ ${credits.toLocaleString('ko-KR')}</b></span><span>운송 ${deliveries}회</span></div><div class="menu-actions"><button id="settings">환경 설정</button><button id="sound">${audio.active?'소리 끄기':'소리 켜기'}</button><button id="zen">물멍 모드</button><button id="photo">사진 저장</button><button id="menu-pause">${paused?'항해 계속':'일시정지'}</button><button id="menu-speed">항해 ${simSpeed}×</button></div>`;
 if(tab==='school')body.innerHTML=schoolMarkup();
 if(tab==='academy')body.innerHTML=academyMarkup();
 if(tab==='training')body.innerHTML=trainingMarkup();
 if(tab==='fleet')body.innerHTML=`<div class="fleet-feature"><img src="${import.meta.env.BASE_URL}fleet/${spec.id}.${['fishing','jetski'].includes(spec.id)?'svg':'webp'}" alt="${spec.name} 3D 모델 적재 예시"><small>${spec.name}${spec.brand?' · 선사 참고 도장':''}</small><h3>${spec.en}</h3><p>${spec.type}</p><div class="fleet-tags">${spec.features.map(f=>`<span>${f}</span>`).join('')}</div><div class="fleet-specs"><span>게임 전장 <b>${spec.length} m</b></span><span>폭 <b>${spec.beam} m</b></span><span>게임 최고 속력 <b>${spec.maxSpeed} kn</b></span></div><div class="fleet-preview-actions"><button id="fleet-inspect">3D로 둘러보기</button><button id="fleet-bridge" class="secondary">브릿지 승선</button></div><button id="fleet-load" class="fleet-load">기본 화물 싣고 살펴보기</button>${spec.source?`<a class="fleet-source" href="${spec.source}" target="_blank" rel="noreferrer">${spec.reference} ↗</a>`:''}</div><p class="fleet-note">실제 선종을 참고한 게임용 축소 모델입니다. 선사 도장은 비공식 창작 표현이며 실제 선박의 정밀 복제·공식 제휴 모델은 아닙니다. 위 이미지는 적재 예시입니다.</p><div class="fleet-filters" aria-label="선박 분류">${[['all','전체 15'],['cargo','상선'],['passenger','여객'],['work','작업선'],['leisure','레저']].map(([id,name])=>`<button data-filter="${id}" class="${fleetFilter===id?'chosen':''}">${name}</button>`).join('')}</div><div class="fleet-list">${ships.filter(s=>fleetFilter==='all'||s.category===fleetFilter).map(s=>`<button class="ship-card ${s.id===spec.id?'chosen':''}" data-ship="${s.id}"><img loading="lazy" src="${import.meta.env.BASE_URL}fleet/${s.id}.${['fishing','jetski'].includes(s.id)?'svg':'webp'}" alt="${s.name}"><div><small>${s.name}</small><h3>${s.en}</h3><p>${s.features[0]} · ${s.maxSpeed} kn</p></div><span>${s.id===spec.id?'승선 중':'↗'}</span></button>`).join('')}</div><p class="fine">선박 변경 또는 낚시·레이싱 시작 시 진행 중인 의뢰와 화물을 초기화합니다. 강에서는 요트만 항해할 수 있어요.</p>`;
 if(tab==='chart')body.innerHTML=`<canvas id="atlas" width="700" height="450" aria-label="한국 중국 일본의 항만 위치 지도"></canvas><p class="chart-key">24개 해역 · 75개 작업 수역 / ${countries[region.country]} · ${region.name}</p><div class="map-filters">${[['all','전체'],['KR','한국'],['CN','중국'],['JP','일본']].map(([id,label])=>`<button data-map-filter="${id}" class="${mapFilter===id?'chosen':''}">${label}</button>`).join('')}</div><div class="region-list">${regions.filter(r=>mapFilter==='all'||r.country===mapFilter).map(r=>`<button data-region="${r.id}" class="region-card ${r.id===region.id?'chosen':''}"><small>${countries[r.country]} · ${r.en}</small><h3>${r.name}</h3><p>${r.ports.join(' · ')}</p><span>${r.id===region.id?'현재 해역':gameMode==='mission'?'이곳 미션 시작':'자유 항해로 이동'}</span></button>`).join('')}</div><details class="science-note"><summary>현재 해역 상세도 · 레이더 범례</summary><p class="fine">흰 삼각형: 통항 선박 · 주황 선: 어망 · 주황 ×: 표류물 · 파란 타원: 고래 관찰 안내(실제 레이더 반사 표적 아님)</p><canvas id="map" width="700" height="350" aria-label="현재 선박과 항구의 항해도"></canvas></details><p class="fine">광역 지도는 공개 해안선 자료를 사용합니다. 18개 항만 배경 지형은 Mapzen Terrain Tiles(USGS·NOAA)의 공개 고도 자료입니다. 높이·거리는 연출용으로 조정했고 항로를 평탄화했습니다. 부두는 게임용 배치로 실측 3D 항만이 아닙니다. 해역을 직접 선택하면 현재 의뢰·화물이 초기화됩니다. 해외 운송은 운송 의뢰에서 시작하세요.</p>${region.source?`<a class="fleet-source" href="${region.source}" target="_blank" rel="noreferrer">항만 배치 참고 자료 ↗</a>`:''}`;
 if(tab==='jobs')body.innerHTML=`<p class="panel-intro">① 금색 작업 수역에서 선적<br/>② 레이더의 금색 항로로 항해<br/>③ 목적지에서 정박하고 하역</p><div class="log-row"><span>항해 수익 <b id="credits">₩ ${credits.toLocaleString('ko-KR')}</b></span><span>완료 ${deliveries}회</span></div>${mission?`<div class="job-card"><small>${{loading:'① 선적 대기',sailing:'② 항해 중',crossing:'② 외해 횡단 대기',arrived:'③ 하역 대기'}[mission.phase]}</small><h3>${mission.origin.name} → ${mission.name}</h3><p>${regions.find(r=>r.id===mission.originRegion)?.name} 출발 · ${mission.destinationRegionName}<br/>${spec.cargo} ${mission.units||6}단위 · 보상 ₩ ${mission.reward.toLocaleString('ko-KR')}</p><div class="job-buttons">${mission.phase==='loading'?'<button id="job-load">선적 시작</button>':mission.phase==='crossing'?'<button id="job-cross">도착 해역으로 항해</button>':'<button id="job-unload">하역 · 운송 정산</button>'}<button id="job-auto" class="secondary">레이더 항로로 자동 항해</button><button data-panel="cargo" class="secondary">적재 상태</button><button id="job-cancel" class="text-button">다른 의뢰 고르기</button></div></div>`:`${completedMission?`<div class="delivery-complete">배송 완료 · ₩ ${completedMission.reward.toLocaleString('ko-KR')}<small>${completedMission.name}에 화물을 인도했습니다.</small></div>`:''}<h3>현재 해역의 운송</h3>${ports.filter(p=>p.id!==localMission(region,state,spec).origin.id).map(p=>`<div class="job-card"><small>${spec.cargo}</small><h3>${p.name}</h3><p>${p.berth} · 화물 6단위</p><button data-job="${ports.indexOf(p)}">의뢰 받기</button></div>`).join('')} ${region.layout!=='river'?`<h3>국내 · 해외 항로</h3><div class="voyage-destinations">${recommendedDestinations(region).map(r=>`<button data-contract-region="${r.id}"><small>${countries[r.country]}</small><b>${r.name}</b><span>${r.ports[0]} ↗</span></button>`).join('')}</div><label class="contract-label">전체 목적지<select id="contract-region">${regions.filter(r=>r.layout!=='river'&&r.id!==region.id).map(r=>`<option value="${r.id}">${countries[r.country]} · ${r.name}</option>`).join('')}</select></label><label class="contract-label">도착 작업 수역<select id="contract-port"></select></label><button id="accept-contract" class="primary-contract">이 항구로 운송하기</button>`:''}`}<div id="handling-info" class="handling-info" ${handling?'':'hidden'}><span id="handling-label"></span><progress id="handling-progress" max="1" value="0"></progress></div><p class="fine">하역 조건: 목적지 95 m 이내 · 2.7 kn 미만 · 정박. 외해 운송은 출항 지점에서 긴 항로를 압축 이동한 뒤 도착 해역을 직접 항해합니다. 가상의 운송 의뢰이며 실제 정기항로 정보는 아닙니다.</p>`;
 if(tab==='cargo')renderCargo(body);
 if(tab==='settings')body.innerHTML=`<h3>시간</h3><div class="segmented">${[['day','한낮'],['sunset','노을'],['night','밤바다']].map(([id,n])=>`<button data-time="${id}" class="${timeMode===id?'chosen':''}">${n}</button>`).join('')}</div><h3>바람과 파도</h3><div class="segmented">${Object.entries({dynamic:{name:'자동 날씨'},...WEATHER}).map(([id,w])=>`<button data-weather="${id}" class="${weather===id?'chosen':''}">${w.name}</button>`).join('')}</div><p class="fine">자동 날씨: 맑음 → 거친 물결 → 돌풍이 서서히 변합니다. 태풍은 직접 선택하는 체험 모드입니다. 실제 예보가 아닌 게임용 날씨이며 배속과 관계없이 변화합니다. 강풍에서는 감속하고 주위 선박을 자주 확인하세요.</p><h3>시점</h3><div class="segmented"><button id="camera-bridge" class="${ocean?.cameraMode===1?'chosen':''}">1인칭 브릿지</button><button id="camera-follow" class="${ocean?.cameraMode===0?'chosen':''}">3인칭 선박</button></div><h3>레이더 읽기</h3><p class="fine">숫자를 눌러 400 m–6.4 km 범위를 바꾸고, 선박 표적을 누르면 추적합니다. 흰 삼각형은 선박, 뒤쪽 선은 지난 궤적, 앞쪽 선은 60초 예상 이동입니다. 주황 선은 어망, 원은 작업 구역, ×는 표류물입니다. 파란 해양 생물과 어구는 학습용 보조 표시이며 실제 레이더에서 항상 탐지되는 물체는 아닙니다.</p><h3>바다 소리 · 항해 BGM</h3><div class="menu-actions"><button id="music-toggle" aria-pressed="${audio.musicEnabled}">항해 BGM ${audio.musicEnabled?'켜짐':'꺼짐'}</button><button id="ambient-horns" aria-pressed="${audio.ambientHorns}">먼 고동 ${audio.ambientHorns?'켜짐':'꺼짐'}</button></div><label class="volume">BGM 음량 <input id="music-volume" type="range" min="0" max="100" value="${audio.musicVolume*100}"></label><label class="volume">음량 <input id="volume" type="range" min="0" max="100" value="${audio.volume*100}"></label><div class="menu-actions"><button id="sound">${audio.active?'소리 끄기':'소리 켜기'}</button><button id="menu-pause">${paused?'항해 계속':'일시정지'}</button><button id="menu-speed">항해 ${simSpeed}×</button></div><p class="fine">화면 좌우 드래그: 둘러보기 · 위아래: 시점 높이 · 항해 배속 1×/3×/8×/20× · W/S: 출력 · A/D: 조타 · C: 시점 · F: 고동 · Space: 닻 · P: 자동 항해 · H: 물멍<br/>메뉴를 열면 이동은 멈추지만 파도와 배의 흔들림은 계속 관찰할 수 있어요.</p>`;
 bindSchool(body);bindAcademy(body);bindTraining(body);
 body.querySelectorAll('[data-leisure]').forEach(b=>b.onclick=()=>startLeisure(b.dataset.leisure));body.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));body.querySelectorAll('[data-map-filter]').forEach(b=>b.onclick=()=>{mapFilter=b.dataset.mapFilter;renderPanel();});
 if(tab==='chart')loadAtlas().then(()=>drawAtlas($('#atlas'),regions,region,mission));
 body.querySelectorAll('[data-contract-region]').forEach(b=>b.onclick=()=>acceptContract(regions.find(r=>r.id===b.dataset.contractRegion)));
 if($('#contract-region')){const fill=()=>{const r=regions.find(r=>r.id===$('#contract-region').value);$('#contract-port').innerHTML=r.ports.map((p,i)=>`<option value="${i}">${p}</option>`).join('');};fill();$('#contract-region').onchange=fill;$('#accept-contract').onclick=()=>acceptContract(regions.find(r=>r.id===$('#contract-region').value),Number($('#contract-port').value));}
 body.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{fleetFilter=b.dataset.filter;renderPanel();});
 bind('#fleet-inspect','onclick',()=>{setCamera(0);closePanel();});bind('#fleet-bridge','onclick',()=>{setCamera(1);closePanel();});bind('#fleet-load','onclick',()=>{if(beginHandling('기본 화물 선적',{bays:[1,1,1,1,1,1],high:false,ballast:false})){setCamera(0);closePanel();}});
 body.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));
 body.querySelectorAll('[data-ship]').forEach(b=>b.onclick=()=>{if(handling)return toast('화물 작업이 끝난 뒤 선박을 변경하세요.');const next=ships.find(s=>s.id===b.dataset.ship);if(region.layout==='river'&&next.draft>region.depth)return toast('강에서는 요트로 항해하세요.');spec=next;ocean?.setShip(spec);reset();renderPanel();$('#panel').scrollTop=0;});
 body.querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>{if(handling)return toast('화물 작업이 끝난 뒤 해역을 변경하세요.');region=regions.find(r=>r.id===b.dataset.region);if(region.layout==='river'&&spec.draft>region.depth){spec=ships.find(s=>s.id==='yacht');ocean?.setShip(spec);}watchTask=null;ports=ocean?.setRegion(region)||[];reset();renderPanel();});
 body.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>acceptContract(region,Number(b.dataset.job)));
 body.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{timeMode=b.dataset.time;ocean?.setTime(timeMode);renderPanel();});body.querySelectorAll('[data-weather]').forEach(b=>b.onclick=()=>{weather=b.dataset.weather;renderPanel();});
 bind('#music-toggle','onclick',()=>{audio.setMusic(!audio.musicEnabled);renderPanel();});bind('#ambient-horns','onclick',()=>{audio.setAmbientHorns(!audio.ambientHorns);renderPanel();});bind('#music-volume','oninput',e=>audio.setMusicVolume(e.target.value/100));bind('#volume','oninput',e=>audio.setVolume(e.target.value/100));bind('#settings','onclick',()=>openPanel('settings'));bind('#sound','onclick',toggleSound);bind('#zen','onclick',()=>{closePanel();toggleZen();});bind('#photo','onclick',()=>{closePanel();ocean?.screenshot();toast('바다의 순간을 저장했습니다.');});
 bind('#menu-pause','onclick',()=>{togglePause();renderPanel();});bind('#menu-speed','onclick',()=>{cycleSpeed();renderPanel();});
 bind('#camera-follow','onclick',()=>{setCamera(0);closePanel();});bind('#camera-bridge','onclick',()=>{setCamera(1);closePanel();});
 bind('#job-cross','onclick',()=>{crossSea();closePanel();});bind('#job-load','onclick',()=>loadMission());bind('#job-unload','onclick',()=>unloadMission());bind('#job-auto','onclick',()=>{if(setAuto(true))closePanel();});
 bind('#job-cancel','onclick',()=>{if(handling)return toast('작업 중에는 취소할 수 없습니다.');mission=null;route=[];routeKey='';setAuto(false);renderPanel();});
}
function renderCargo(body){
 const editable=atBerth()&&!handling&&!state.capsized;info=stability(spec,cargo);
 body.innerHTML=`<div class="cargo-status"><span class="berth ${editable?'ready':''}">${editable?'항구에 정박 · 화물 작업 가능':handling?'화물 작업 중':'항구에 정박하면 적재 변경 가능'}</span><b id="cargo-unit-count">${cargoUnits(cargo)} / 18 단위</b></div>
 <canvas id="stability-canvas" width="660" height="245" aria-label="화물의 무게중심 G, 메타센터 M과 복원정 그래프"></canvas>
 <div class="stability-values"><div><small>GM · 초기 복원성</small><b id="gm-value">${info.gm.toFixed(2)} m</b></div><div><small>롤링 · 좌우</small><b id="roll-value">0.0°</b></div><div><small>피칭 · 앞뒤</small><b id="pitch-value">0.0°</b></div></div>
 <p id="stability-explanation" class="lesson-explanation"></p>
 <details ${lesson?'open':''} class="learning"><summary>항해사 실습 · 직접 비교하기</summary><div class="preset-buttons"><button data-preset="low" ${!editable?'disabled':''}>① 낮고 고르게</button><button data-preset="high" ${!editable||liquidShip(spec)?'disabled':''}>② 높이 쌓기</button><button data-preset="list" ${!editable?'disabled':''}>③ 좌현에 몰기</button></div><p id="lesson-result">${lesson?.text||'같은 12단위 화물을 낮게·높게 비교하거나, 좌현 편중으로 평균 기울기를 관찰해 보세요.'}</p><button id="observe" class="secondary">3인칭으로 움직임 관찰</button></details>
 <div class="cargo-layout"><div class="bow-label">↑ 선수</div><div class="bay-columns"><span>좌현</span><span>우현</span></div><div class="bay-grid">${cargo.bays.map((n,i)=>`<div class="bay"><small>${BAY_NAMES[i]}</small><div class="bay-fill">${[0,1,2].map(j=>`<i class="${j<n?'filled':''}"></i>`).join('')}</div><div class="bay-buttons"><button data-bay="${i}" data-change="-1" aria-label="${BAY_NAMES[i]} 하역" ${!editable||n===0?'disabled':''}>−</button><b>${n}</b><button data-bay="${i}" data-change="1" aria-label="${BAY_NAMES[i]} 선적" ${!editable||n===3?'disabled':''}>＋</button></div></div>`).join('')}</div><div class="stern-label">선미</div></div>
 ${!liquidShip(spec)?`<label class="check-row"><input id="high-cargo" type="checkbox" ${cargo.high?'checked':''} ${!editable?'disabled':''}> 화물을 높은 갑판에 배치</label>`:'<p class="fine">탱크 1·2칸: 부분 적재 / 3칸: 가득 참. 부분 적재 탱크에는 자유수면 보정이 적용됩니다.</p>'}
 <label class="check-row"><input id="ballast" type="checkbox" ${cargo.ballast?'checked':''} ${!editable?'disabled':''}> 낮은 밸러스트 탱크 채우기</label>
 <div class="cargo-footer"><span id="draft-value">흘수 ${info.draft.toFixed(1)} m</span><span id="kg-value">KG ${info.kg.toFixed(2)} m</span><button id="empty-cargo" ${!editable?'disabled':''}>전체 하역</button></div>
 <div id="handling-info" class="handling-info" ${handling?'':'hidden'}><span id="handling-label"></span><progress id="handling-progress" max="1" value="0"></progress></div>
 <details class="science-note"><summary>복원력을 읽는 법</summary><p>G는 무게중심, M은 작은 기울기에서의 메타센터입니다. GM = KM − KG에서 액체 자유수면 영향을 보정합니다. 작은 각도에서 GZ ≈ GM × sin(기울기)이며, 편중 화물은 이 관계에 추가 영향을 줍니다.</p><p>GM이 커지면 보통 더 빠르게 돌아오지만 흔들림이 거칠 수 있습니다. GM 하나로 실제 선박의 안전을 판단할 수는 없습니다. 이 화면의 선체 계수·하중·파도 응답은 교육용 근사치입니다.</p><a href="https://www.imo.org/en/ourwork/safety/pages/shipdesignandstability-default.aspx" target="_blank" rel="noreferrer">IMO 선박 복원성 자료 ↗</a></details>`;
 body.querySelectorAll('[data-bay]').forEach(b=>b.onclick=()=>{if(!canEdit())return;const next=structuredClone(cargo);next.bays[Number(b.dataset.bay)]=clamp(next.bays[Number(b.dataset.bay)]+Number(b.dataset.change),0,3);beginHandling(Number(b.dataset.change)>0?'선적':'하역',next);});
 body.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{if(!canEdit())return;const id=b.dataset.preset,next=cargoPreset(id),before=stability(spec,cargo),after=stability(spec,next);lesson={id,text:`${id==='list'?'좌현 편중':'같은 12단위 비교'} · GM ${before.gm.toFixed(2)} → ${after.gm.toFixed(2)} m. ${id==='low'?'G가 낮아졌을 때 복원 속도를 관찰하세요.':id==='high'?'G가 올라가면 GM이 작아집니다. 낮은 적재와 비교하세요.':'기울어진 쪽이 계속 낮게 유지되는 횡경사를 관찰하세요.'}`};beginHandling('적재 재배치',next);});
 bind('#high-cargo','onchange',e=>{if(canEdit())beginHandling('적재 재배치',{...structuredClone(cargo),high:e.target.checked});});bind('#ballast','onchange',e=>{if(canEdit())beginHandling('밸러스트 조절',{...structuredClone(cargo),ballast:e.target.checked});});bind('#empty-cargo','onclick',()=>{if(canEdit())beginHandling('전체 하역',emptyCargo());});bind('#observe','onclick',()=>{setCamera(0);closePanel();toast('항해 수첩 → 화물·복원력에서 실시간 수치를 비교하세요.');});
}
function canEdit(){if(handling){toast('진행 중인 화물 작업을 마쳐 주세요.');return false;}if(!atBerth()){toast('항구에서 감속한 뒤 닻을 내려야 합니다.');return false;}return true;}
function beginHandling(label,next,onComplete){if(!canEdit())return false;handling={label,next,onComplete,progress:0,duration:3};state.throttle=0;setAuto(false);if($('#panel').open)renderPanel();return true;}
function loadMission(){if(!mission||mission.phase!=='loading')return;if(mission.originRegion!==region.id||!canDock(state,mission.origin))return toast('출발 항구에서 선적하세요.');beginHandling('화물 선적',{bays:[1,1,1,1,1,1],high:false,ballast:false},()=>{if(mission)mission.phase='sailing';toast('선적 완료. 흘수와 복원력을 확인하고 출항하세요.');});}
function unloadMission(){if(trainingBook.run&&trainingBook.run.phase<5)return toast('승선 실습의 당직·기상 단계를 마친 뒤 화물을 인도하세요.');if(!mission||mission.phase==='loading')return toast('먼저 출발 항구에서 선적하세요.');if(mission.destinationRegion!==region.id||!canDock(state,mission))return toast('도착 항구 반경 95 m 안에서 2.7 kn 미만으로 감속하세요.');if(cargoUnits(cargo)<6)return toast('계약 화물 6단위가 필요합니다.');const reward=mission.reward;beginHandling('도착 화물 하역',emptyCargo(),()=>{credits+=reward;deliveries++;tickTraining(0,'delivered');completedMission={name:mission.name,portId:mission.id,reward};mission=null;route=[];routeKey='';save();toast('하역 완료 · ₩ '+reward.toLocaleString('ko-KR')+' 지급');});}
function setAuto(value){if(value&&activity)return false;if(value&&(handling||state.capsized||rescueCall))return false;if(value&&mission){route=planRoute(state,jobTarget(),routingObstacles(),spec.beam*.5+50);if(!route){toast('안전한 자동 항로를 찾지 못했습니다. 수동으로 수로로 이동하세요.');return false;}}autopilot=value;$('#autopilot').classList.toggle('active',value);if(value){helmTarget=0;state.anchored=false;syncAnchor();toast(mission?'지정 항구로 자동 항해합니다.':'현재 방위를 유지합니다.');}return true;}
function toggleAnchor(){if(activity?.type==='race'&&activity.run.phase!=='racing')return;if(activity?.type==='fishing'&&['waiting','bite','reeling'].includes(activity.run.phase))return toast('채비를 회수한 뒤 출항하세요.');if(handling)return toast('화물 작업이 끝난 뒤 출항하세요.');if(state.anchored){commandThrottle(.65);}else{state.anchored=true;state.throttle=0;helmTarget=0;setAuto(false);syncAnchor();}}

function togglePause(){paused=!paused;$('#pause').textContent=paused?'항해 계속':'일시정지';}
function cycleSpeed(){if(activity)return toast('낚시와 레이싱은 실시간으로 진행됩니다.');simSpeed=simSpeed===3?8:simSpeed===8?20:simSpeed===20?1:3;$('#time-speed').textContent='항해 '+simSpeed+'×';$('#pace-toggle').textContent=simSpeed+'× 항해';}
function toggleZen(){zen=!zen;document.body.classList.toggle('zen',zen);$('#exit-zen').hidden=!zen;}
async function blowHorn(){try{await audio.playSignal('long',spec.length);}catch{toast('오디오를 시작할 수 없습니다.');}}
$('#horn').onclick=blowHorn;
async function toggleSound(){try{await audio.toggle();if($('#panel').open)renderPanel();}catch{toast('오디오를 시작할 수 없습니다.');}}
document.querySelectorAll('[data-start-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.startMode));syncWelcomeModes();
$('#training-chip').onclick=()=>openPanel('training');$('#start-training').onclick=()=>{gameMode='mission';$('#start').click();openPanel('training');};
$('#start').onclick=async()=>{if(gameMode==='mission'&&!mission&&!completedMission)mission=localMission(region,state,spec);started=true;$('#welcome').classList.add('dismissed');setCamera(0);await toggleSound();};
$('#officer').onclick=()=>openPanel('menu');$('#menu').onclick=()=>openPanel('menu');$('#panel-back').onclick=()=>openPanel('menu');$('#close-panel').onclick=closePanel;$('#panel').addEventListener('close',()=>keys={});
$('#camera-toggle').onclick=()=>setCamera(1-ocean.cameraMode);$('#motion-readout').onclick=()=>openPanel('cargo');$('#anchor').onclick=toggleAnchor;$('#autopilot').onclick=()=>setAuto(!autopilot);$('#exit-zen').onclick=toggleZen;
$('#throttle').oninput=e=>{const value=Number(e.target.value);commandThrottle(Math.abs(value)<4?0:value/100);};$('#pause').onclick=togglePause;$('#time-speed').onclick=cycleSpeed;$('#pace-toggle').onclick=cycleSpeed;
$('#recover').onclick=()=>{reset();paused=false;$('#pause').textContent='일시정지';toast('항구로 돌아왔습니다. 화물을 낮고 고르게 배치해 보세요.');};
window.addEventListener('keydown',e=>{if(e.target.closest('#signal-panel,#signal-toggle'))return;if(!started||e.target.matches('input,textarea,select,[contenteditable=true],[role=slider]')||$('#panel').open)return;const k=e.key.toLowerCase();if(['w','a','s','d',' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys[k]=true;if((k==='w'||k==='arrowup')&&paused)commandThrottle(Math.max(.35,state.throttle));if(e.repeat)return;if(k===' ')toggleAnchor();if(k==='p')setAuto(!autopilot);if(k==='f')blowHorn();if(k==='h')toggleZen();if(k==='c')setCamera(1-ocean.cameraMode);if(k==='escape'&&zen)toggleZen();});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);window.addEventListener('blur',()=>keys={});
window.addEventListener('pagehide',save);setInterval(save,15000);
function drawMap(){const canvas=$('#map');if(!canvas)return;const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,scale=.12;c.fillStyle='#123641';c.fillRect(0,0,w,h);c.strokeStyle='#8bbbad20';for(let x=0;x<w;x+=35){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}for(let y=0;y<h;y+=35){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();}const project=p=>[w/2+(p.x-state.x)*scale,h*.65+(p.z-state.z)*scale];
 c.fillStyle='#416e65';for(const o of ocean?.obstacles||[]){const [x,y]=project(o);c.beginPath();c.ellipse(x,y,o.radius*scale,o.radius*scale*.8,0,0,Math.PI*2);c.fill();}if(region.layout==='river'){const left=w/2+(-310-state.x)*scale,right=w/2+(310-state.x)*scale;c.fillRect(0,0,left,h);c.fillRect(right,0,w-right,h);}
 if(mission){const [x,y]=project(jobTarget());c.setLineDash([5,6]);c.strokeStyle='#e7be7d';c.beginPath();c.moveTo(w/2,h*.65);c.lineTo(x,y);c.stroke();c.setLineDash([]);}for(const p of ports){const [x,y]=project(p);c.strokeStyle='#a9dcd1';c.beginPath();c.arc(x,y,6,0,Math.PI*2);c.stroke();c.font='16px sans-serif';c.fillStyle='#d1e1dc';c.fillText(p.name,x+12,y+5);}c.save();c.translate(w/2,h*.65);c.rotate(state.heading);c.beginPath();c.moveTo(0,-12);c.lineTo(8,9);c.lineTo(0,4);c.lineTo(-8,9);c.closePath();c.fillStyle='#f4d19a';c.fill();c.restore();c.fillStyle='#c3d7d5';c.font='17px sans-serif';c.fillText('N ↑',w-50,30);}
function updateUI(){updateLeisureUI();const sailButton=$('#sail-toggle');sailButton.hidden=spec.kind!=='yacht'||!started||zen;sailButton.textContent=`${state.sailTarget?'돛 접기':'돛 펼치기'} · ${Math.round((state.sailArea||0)*100)}%`;sailButton.setAttribute('aria-pressed',String(!!state.sailTarget));$('#voyage-hint').hidden=gameMode==='free';
 const tr=trainingBook.run;$('#training-chip').hidden=!tr||zen;$('#training-chip').textContent=tr?`승선 실습 ${Math.min(6,tr.phase+1)}/6 · ${tr.status==='question'?'상황 판단':tr.status==='review'?'복습':TRAINING_STEPS[tr.phase]?.name||'완료'} ↗`:'';
 $('#damage-panel').classList.toggle('assisting',!!rescueCall);$('#damage-panel').hidden=!damageNotice||state.capsized;$('#damage-open').hidden=damageNotice||!state.damage||state.capsized;$('#damage-open').textContent=`선체 ${Math.round(100-(state.damage||0))}% · 수리`;
 $('#damage-title').textContent=state.damage?`선체 내구도 ${Math.round(100-state.damage)}%`:'수리 완료 · 항해 재개';$('#hull-health').value=100-(state.damage||0);
 $('#damage-status').textContent=rescueCall?(rescueCall.status==='responding'?`구조정 접근 중 · ${Math.round(Math.hypot(rescueCall.x-state.x,rescueCall.z-state.z))} m`:'구조대 응급 수리 중'):state.damage?'기관 정지 → 인명·침수·복원성 확인 → 지원 요청. 수리가 끝나면 자동으로 전진합니다.':recoveryPending?'안전한 복구 위치를 찾는 중 · 주변 선박이 지나가면 자동 재개합니다.':'복구 완료 · 전진 항해를 재개했습니다.';
 $('#repair-tap').disabled=!!rescueCall||!state.damage;$('#call-rescue').disabled=!!rescueCall||!state.damage;

 const w=weatherState;$('#weather-readout').textContent=`${w.name||'산들바람'} · 바람 ${w.wind.toFixed(0)} m/s${w.group>1.18?' · 큰 파도 접근':''}`;$('#weather-readout').classList.toggle('storm',w.storm>.6);
 info=stability(spec,cargo);const roll=(state.roll*180/Math.PI).toFixed(1),pitch=(state.pitch*180/Math.PI).toFixed(1);
 $('#pace-toggle').textContent=simSpeed+'× 항해';$('#speed').textContent=(Math.abs(state.speed)/.5144).toFixed(1);$('#heading').textContent=String(((Math.round(state.heading*180/Math.PI)%360)+360)%360).padStart(3,'0')+'°';$('#roll').textContent=roll+'°';$('#pitch').textContent=pitch+'°';$('#throttle-value').textContent=Math.abs(state.throttle)<.025?'중립':(state.throttle<0?'후진 ':'전진 ')+Math.round(Math.abs(state.throttle)*100)+'%';$('#throttle').value=Math.round(state.throttle*100);$('#throttle').setAttribute('aria-valuetext',$('#throttle-value').textContent);setWheel(autopilot?state.rudder:helmTarget);$('#rudder-value').textContent=Math.abs(state.rudder)<.02?'중앙':(state.rudder<0?'좌현 ':'우현 ')+Math.round(Math.abs(state.rudder)*35)+'°';$('#throttle').disabled=!!handling||state.capsized||!!rescueCall;$('#stability-dot').classList.toggle('warning',info.status!=='안정');
 updateRoute();const action=$('#mission-action');action.hidden=true;$('#mission-nav').textContent='';$('#mission-stage').textContent=gameMode==='mission'?'미션 항해 · ① 선적 → ② 항해 → ③ 하역':'자유 항해';
 if(paused)$('#mission-status').textContent='일시정지';else if(handling)$('#mission-status').textContent=handling.label+' '+Math.round(handling.progress*100)+'%';else if(mission){const target=jobTarget(),next=route[0]||target,nav=bearingTo(state,next),dist=Math.round(Math.hypot(state.x-target.x,state.z-target.z));$('#mission-status').textContent=(mission.phase==='loading'?'선적 · ':target.isGate?'출항 · ':'하역 · ')+target.name;$('#mission-nav').textContent=`${dist} m · ${String(nav.bearing).padStart(3,'0')}° · ${Math.abs(nav.relative)<8?'앞으로':nav.relative>0?'우현으로':'좌현으로'}${route.length>1?' · 경유지 '+route.length+'개':''}`;
 if(dist<95){action.hidden=false;if(!state.anchored||Math.abs(state.speed)>=1.4){action.textContent=state.anchored?'감속 중…':'정박하기';action.onclick=()=>{if(!state.anchored)toggleAnchor();};}else if(target.isGate){action.textContent='도착 해역으로';action.onclick=crossSea;}else{action.textContent=mission.phase==='loading'?'선적 시작':'하역 시작';action.onclick=mission.phase==='loading'?loadMission:unloadMission;}}
 else{action.hidden=false;action.textContent=autopilot?'수동 조타':'자동 항해';action.onclick=()=>setAuto(!autopilot);}}
 else if(completedMission){$('#mission-status').textContent='배송 완료 · ₩ '+completedMission.reward.toLocaleString('ko-KR');action.hidden=false;action.textContent='다음 미션';action.onclick=()=>openPanel('jobs');}
 else if(gameMode==='mission'){$('#mission-status').textContent='다음 화물의 목적지를 선택하세요';action.hidden=false;action.textContent='미션 선택';action.onclick=()=>openPanel('jobs');}
 else if(info.status!=='안정'){$('#mission-status').textContent=info.status+' · 적재 상태를 확인하세요';action.hidden=false;action.textContent='복원력 보기';action.onclick=()=>openPanel('cargo');}
 else $('#mission-status').textContent=state.anchored?'레버를 올리거나 출항을 눌러보세요':autopilot?'자동 항해 중':spec.name+' · '+(weatherState.name||'산들바람');
 if($('#stability-canvas')){drawStability($('#stability-canvas'),state,spec,cargo);$('#gm-value').textContent=info.gm.toFixed(2)+' m';$('#gm-value').classList.toggle('warning-text',info.gm<.5);$('#roll-value').textContent=roll+'°';$('#pitch-value').textContent=pitch+'°';$('#stability-explanation').textContent=lessonText(info,state,cargo);}
 if($('#handling-info')){$('#handling-info').hidden=!handling;if(handling){$('#handling-label').textContent=handling.label+' · '+Math.round(handling.progress*100)+'%';$('#handling-progress').value=handling.progress;}}
 const near=ocean?.world?trafficAdvisory(ocean.world,state,spec.beam):null,tracked=ocean?.world?.contacts.find(c=>c.id===ocean.world.trackedId),contact=near?.danger?near:tracked?contactSolution(tracked,state,spec.beam):near;
 updateWatchUI();
 const watch=$('#sea-watch');if(watch){watch.hidden=!contact||(!document.body.classList.contains('instruments-open')&&contact.distance>120);watch.classList.toggle('danger',!!contact?.danger);if(contact)watch.textContent=`${contact.danger?'⚠ ':''}${contact.name} · ${Math.round(contact.distance)} m · ${tracked&&!near?.danger?(contact.rawTcpa>0?`최근접 ${Math.round(contact.cpa)} m / ${Math.ceil(contact.tcpa)}초 뒤`:'멀어지는 중'):watchHint(contact)}`;}
 if(ocean)ocean.navRoute=route;drawMap();drawRadar($('#radar'),state,ocean?.obstacles||[],ports,mission?jobTarget():null,t,radarRange,region.layout==='river',route,ocean?.world);drawAtlas($('#atlas'),regions,region,mission);
 $('#control-tip').textContent=academyTask?`학습 · ${practices[academyTask.kind].title} · 메뉴에서 실습 안내 확인`:handling?'화물 작업 중 · 잠시 후 출항할 수 있어요':paused?'일시정지 · 레버를 올리면 다시 항해합니다':autopilot?'자동 항해 중 · 휠이나 레버를 움직이면 수동 전환':state.anchored?'레버를 위로 올리면 출항 · 휠을 돌리면 조타':Math.abs(state.speed)<.5&&Math.abs(state.throttle)>.1?'기관 가동 중 · 배가 서서히 속도를 올립니다':'휠을 돌려 방향 조절 · 정박 버튼으로 멈추기';
}
let last=performance.now(),uiTimer=0;
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;const active=started&&!paused&&!$('#panel').open&&!document.hidden&&!handling&&!state.capsized;if(started&&!paused&&!document.hidden)stepWeather(weatherState,dt,weather,region);const strength=weatherState.strength??region.wave,wind=weatherState.wind;
 if(!paused&&!document.hidden){t+=dt;
 if(handling){handling.progress=clamp(handling.progress+dt/handling.duration,0,1);if(handling.progress>=1){const done=handling;cargo=done.next;handling=null;done.onComplete?.();updateAcademy(0,true);if($('#panel').open&&tab==='cargo')tickTraining(0,'cargo');save();if($('#panel').open)renderPanel();refresh();}}
 // Attitude remains at real time, including while a menu is open; voyage time warp affects translation only.
 if(rescueCall?.status==='assisting'){repairByCrew(state,dt);if(!state.damage){rescueCall.status='complete';rescueCall.name='해양경찰 구조정 · 지원 완료';rescueCall=null;ocean.rescueTarget=null;finishRecovery();save();}}
 if(recoveryPending&&t>recoveryRetryAt){recoveryRetryAt=t+2;finishRecovery();}
 stepAttitude(state,spec,cargo,{wave:strength,wind,windDirection:weatherState.direction},t,dt);
 }
 if(active){updateAcademy(dt);tickTraining(dt);tickLeisure(dt);}
 if(active){for(let i=0;i<simSpeed;i++){
 if(ocean?.world)stepTraffic(ocean.world,dt,{...state,assisted:autopilot});const before={x:state.x,z:state.z},impactSpeed=Math.abs(state.speed),wasAuto=autopilot;
 const throttleKey=(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0),steerKey=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0);if(throttleKey)commandThrottle(state.throttle+throttleKey*dt*.5);const racing=activity?.type==='race';if(racing){helmTarget=clamp(steerKey+raceSteering.value,-1,1);$('#race-steering').dataset.direction=String(helmTarget);}else if(steerKey)commandSteer(clamp(helmTarget+steerKey*dt*1.2,-1,1));const input={throttle:0,steer:helmTarget,quickSteer:racing};
 if(autopilot){state.throttle=.65;const target=jobTarget();if(target){if(route.length>1&&Math.hypot(route[0].x-state.x,route[0].z-state.z)<30)route.shift();const waypoint=route[0]||target;const dist=Math.hypot(target.x-state.x,target.z-state.z),desired=Math.atan2(waypoint.x-state.x,-(waypoint.z-state.z)),diff=Math.atan2(Math.sin(desired-state.heading),Math.cos(desired-state.heading));input.steer=clamp(diff*2,-1,1);if(Math.abs(diff)>.4||route.length>1)state.throttle=.3;const stopping=state.speed/(spec.accel*.18)*(info.mass/(spec.mass*100))+85;if(route.length<=1&&dist<stopping)state.throttle=.08;if(route.length<=1&&dist<78){state.throttle=0;state.anchored=true;syncAnchor();if(canDock(state,target)){setAuto(false);if(mission.phase==='sailing')mission.phase=target.isGate?'crossing':'arrived';toast(mission.phase==='loading'?'선적 항구 도착. 선적을 시작하세요.':target.isGate?'출항 지점 도착. 도착 해역으로 이동하세요.':'도착했습니다. 하역을 시작하세요.');}}}}
 const contact=ocean?.world?trafficAdvisory(ocean.world,state,spec.beam):null;
 if(autopilot&&contact?.danger){
  const emergency=contact.distance<contact.radius+spec.beam*.5+30;
  let detour=route.length>1;
  if(mission&&!['whale','shark'].includes(contact.kind)&&ocean.world.time-trafficReplanAt>3){trafficReplanAt=ocean.world.time;const blockers=ocean.world.contacts.filter(c=>!['whale','shark'].includes(c.kind)&&!c.site).map(c=>({...c,radius:Math.max(1,Math.min(c.radius+(c.kind==='towing'?110:20),Math.hypot(c.x-state.x,c.z-state.z)-spec.beam*.5-65))}));const candidate=planRoute(state,jobTarget(),[...routingObstacles(),...blockers],spec.beam*.5+50);if(candidate?.length){route=candidate;detour=true;}}
  // A low-speed game detour avoids the mutual stop of two courtesy controllers.
  // It is route assistance, not a COLREG manoeuvre decision.
  if(detour&&!emergency&&!['whale','shark'].includes(contact.kind)){state.throttle=Math.min(state.throttle,.18);state.speed=Math.min(state.speed,2);}else{state.throttle=0;state.speed*=Math.exp(-dt*1.5);}
 }
 stepVessel(state,spec,{wind,windDirection:weatherState.direction,river:region.layout==='river',loadFactor:info.mass/(spec.mass*100)},dt,input);
 const groundHit=ocean?stopAtBoundary(state,before,(x,z)=>ocean.groundHeight(x,z)>2):false;
 if(groundHit){recordImpact(impactSpeed);setAuto(false);if(t-lastCollision>3){lastCollision=t;toast('육지 접촉으로 정지했습니다. 손상을 확인하세요.');}}
 const targets=ocean?.world?[...ocean.world.contacts.filter(c=>c.kind!=='coastguard'),...ocean.world.hazards]:[];
 for(const tow of targets.filter(c=>c.kind==='towing')){const end=towEnd(tow);for(let j=1;j<=10;j++)targets.push({x:tow.x+(end.x-tow.x)*j/10,z:tow.z+(end.z-tow.z)*j/10,radius:22});}
 const impactContact=stopAtCircles(state,before,targets,spec.beam*.5);
 if(impactContact){recordImpact(Math.max(impactSpeed,Math.hypot(impactContact.vx||0,impactContact.vz||0)));setAuto(false);}
 const boundaryHit=applyBoundary(state,region,ocean?.obstacles||[],before,spec.beam*.5);
 if(activity?.type==='race'){const event=resolveRaceCollision(activity.run,state,before);if(event&&t-lastCollision>2){lastCollision=t;toast('코스 접촉으로 정지 · 조타와 후진 레버로 벗어나세요.');}}

 if(watchTask&&ocean?.world){const result=stepWatch(watchTask,ocean.world,state,spec.beam,dt,wasAuto,!!contact?.collision||boundaryHit||groundHit);if(result.done){watchTask=null;ocean.world.trackedId=null;if(!result.cancelled){school.log.unshift(result);school.log=school.log.slice(0,12);save();toast(`${result.success?'안전 통과 기록!':'실습 복기'} ${result.reason}`);}}}
 if(boundaryHit)recordImpact(impactSpeed);
 if(boundaryHit&&t-lastCollision>3){lastCollision=t;setAuto(false);state.throttle=0;toast('해안·장애물 접촉 · 수리 완료 후 안전 수역에서 자동 재개합니다.');}
 }}
 if(state.capsized){rescueCall=null;if($('#rescue').hidden){closePanel();handling=null;}$('#rescue').hidden=false;setAuto(false);}
 leisureView?.update(activity,state,t,strength);if(!paused){ocean?.setWeather(weatherState,state);ocean?.update(state,t,dt,strength,cargo,handling);}audio.update(t,paused?0:state.speed,wind,spec.id==='yacht',paused||state.anchored?0:state.throttle,started&&!paused&&!document.hidden&&!$('#panel').open,ocean?.foam.impact||0);uiTimer+=dt;if(uiTimer>.12){uiTimer=0;updateUI();}
}
spawnAtPort();const restored=restoreTrip(saved.trip,region,spec);if(restored){state=restored.state;cargo=restored.cargo;mission=gameMode==='mission'?restored.mission:null;completedMission=restored.completed;damageNotice=state.damage>0;}else if(gameMode==='mission')mission=localMission(region,state,spec);if(trainingBook.run){if(trainingBook.run.region===region.id&&trainingBook.run.ship===spec.id){trainingBook.run.question=trainingQuestion(trainingBook.run.phase,trainingContext());if(trainingBook.run.phase===4&&trainingBook.run.status==='practice')weather='rough';}else cancelTraining();}refresh();syncWelcomeModes();loadAtlas();requestAnimationFrame(animate);

function endLeisure(){raceSteering.reset();document.body.classList.remove('instruments-open');$('#instruments-toggle')?.setAttribute('aria-pressed','false');$('#leisure-hud')?.classList.remove('expanded');$('#leisure-more')?.setAttribute('aria-expanded','false');activity=null;state.jumpHeight=0;state.jumpVelocity=0;leisureView?.clear();document.body.classList.remove('leisure-active','fishing-mode','race-mode');if($('#leisure-hud'))$('#leisure-hud').hidden=true;}
function openWater(){
 const obstacles=ocean.obstacles;for(let radius=1300;radius<6500;radius+=650)for(let n=0;n<12;n++){const c={x:Math.sin(n*Math.PI/6)*radius,z:Math.cos(n*Math.PI/6)*radius};let clear=true;for(let x=-100;x<=500;x+=50)for(let z=-450;z<=250;z+=50){const px=c.x+x,pz=c.z+z;if(ocean.groundHeight(px,pz)>0||obstacles.some(o=>Math.hypot(px-o.x,pz-o.z)<o.radius+90))clear=false;}if(clear)return c;}return null;
}
async function startLeisure(type){
 if(handling)return toast('화물 작업이 끝나면 시작할 수 있어요.');if(!ocean)return;
 if(region.layout==='river')return toast('낚시와 레이싱은 바다 해역에서 시작할 수 있어요. 항해도에서 바다를 선택하세요.');const center=openWater();if(!center)return toast('이 해역에는 넓은 놀이 수역이 없습니다. 바다 해역으로 이동해 주세요.');
 closePanel();gameMode='free';spec=ships.find(s=>s.id===(type==='race'?'jetski':'fishing'));ocean.setShip(spec);reset();state.x=center.x;state.z=center.z;state.heading=0;state.throttle=0;state.speed=0;state.anchored=true;simSpeed=1;weather='calm';timeMode=type==='race'?'day':'sunset';ocean.setTime(timeMode);started=true;paused=false;$('#welcome').classList.add('dismissed');setCamera(0);ocean.orbit=type==='race'?0:-.65;ocean.zoom=type==='race'?.55:1;
 activity={type,run:type==='race'?newRace(center):newFishing(),center};if(type==='race')leisureView.race(activity.run);else leisureView.fishing();document.body.classList.add('leisure-active',type==='race'?'race-mode':'fishing-mode');$('#leisure-hud').hidden=false;syncAnchor();refresh();updateLeisureUI();save();if(!audio.active)await toggleSound();
}
function tickLeisure(dt){if(!activity)return;const {type,run}=activity;if(type==='fishing'){const fish=stepFishing(run,dt);if(fish)toast(`${fish.name} ${fish.length} cm! 기록하거나 놓아줄 수 있어요.`);}else{const event=stepRaceFeatures(run,state,dt);if(event==='jump')toast('점프!');if(event==='land')ocean.foam.slam=1;if(event==='obstacle'||event==='rail')toast('코스 접촉 +2초');const previous=run.phase;if(stepRace(run,state,dt)){state.throttle=0;state.anchored=true;syncAnchor();const score=run.elapsed+run.penalty;leisureBook.best=leisureBook.best?Math.min(leisureBook.best,score):score;save();toast('완주! 개인 최고 기록을 확인하세요.');}if(previous==='countdown'&&run.phase==='racing'){state.anchored=false;state.throttle=.85;syncAnchor();toast('좌·우 버튼을 누르면 회전 · 손을 떼면 직진!');}}}
function fishingAction(){if(!activity||activity.type!=='fishing')return;const f=activity.run;if(['ready','escaped'].includes(f.phase)){state.anchored=true;state.speed=0;state.throttle=0;syncAnchor();castFishing(f);}else if(f.phase==='bite')strikeFishing(f);else if(f.phase==='reeling'){f.tension=Math.min(1,f.tension+.065);if(f.tension<.87)f.progress=Math.min(1,f.progress+.055);}else if(f.phase==='waiting'){f.phase='ready';f.held=false;}updateLeisureUI();}
function storeCatch(release){if(activity?.type!=='fishing'||activity.run.phase!=='caught')return;leisureBook.fish.push({...activity.run.catch,released:release});leisureBook.fish=leisureBook.fish.slice(-40);activity.run=newFishing();save();toast(release?'도감에 기록하고 바다로 돌려보냈어요.':'어획 기록에 담았습니다. 다음 입질을 기다려 보세요.');updateLeisureUI();}
function updateLeisureUI(){if(!activity)return;$('#fish-journal').hidden=activity.type!=='fishing';$('#fish-journal-list').textContent=leisureBook.fish.length?leisureBook.fish.slice(-8).reverse().map(f=>`${f.name} ${f.length} cm`).join(' / '):'첫 물고기를 기다리고 있어요.';const {type,run}=activity,button=$('#leisure-action');$('#fishing-gauges').hidden=type!=='fishing'||run.phase!=='reeling';$('#catch-choice').hidden=type!=='fishing'||run.phase!=='caught';button.hidden=false;if(type==='race'){const gate=run.gates[run.next],nav=gate?bearingTo(state,gate):null;$('#leisure-label').textContent='부표 타임 트라이얼';$('#leisure-status').textContent=run.phase==='countdown'?`출발 ${Math.max(1,Math.ceil(run.countdown))}`:run.phase==='finished'?`완주 ${(run.elapsed+run.penalty).toFixed(1)}초`:`${(run.elapsed+run.penalty).toFixed(1)}초 · ${run.next} / 7`;$('#leisure-detail').textContent=(gate?`다음 부표 ${Math.round(Math.hypot(gate.x-state.x,gate.z-state.z))} m · ${Math.abs(nav.relative)<10?'↑ 앞으로':nav.relative>0?'↱ 오른쪽':'↰ 왼쪽'} ${Math.round(Math.abs(nav.relative))}° · `:'')+`최고 ${leisureBook.best?leisureBook.best.toFixed(1)+'초':'기록 없음'}${run.penalty?' · 접촉 +'+run.penalty+'초':''}`;button.textContent='다시 달리기';button.onclick=()=>startLeisure('race');}else{const text={ready:['낚싯줄을 드리워 볼까요','찌 던지기'],waiting:['파도와 입질을 기다리세요','채비 회수'],bite:['입질! 지금 챔질하세요','챔질하기'],reeling:['당기고, 느슨하게 놓아주세요','릴 감기 · 누르거나 길게 누르기'],escaped:['물고기가 빠져나갔어요','다시 던지기'],caught:[`${run.catch?.name} · ${run.catch?.length} cm`,'']};$('#leisure-label').textContent='작은 어선 · 낚시 쉼터';$('#leisure-status').textContent=text[run.phase][0];$('#leisure-detail').textContent=run.phase==='reeling'?'장력이 가득 차기 전에 손을 떼세요. 줄을 풀며 천천히 끌어올립니다.':`어획 기록 ${leisureBook.fish.length}마리 · 발견 ${new Set(leisureBook.fish.map(f=>f.name)).size}/4종`;
 button.textContent=run.phase==='reeling'?'릴 감기':text[run.phase][1];button.hidden=run.phase==='caught';button.onclick=fishingAction;$('#line-tension').value=run.tension;$('#fish-progress').value=run.progress;button.classList.toggle('reeling',run.held);}
 $('#leisure-hud').dataset.phase=run.phase;$('#leisure-hud').dataset.jumps=String(run.jumps||0);
}
for(const b of document.querySelectorAll('[data-leisure]'))b.onclick=()=>startLeisure(b.dataset.leisure);
$('#leisure-exit').onclick=()=>{endLeisure();setAuto(false);state.speed=0;state.throttle=0;state.anchored=true;keys={};started=false;paused=false;closePanel();$('#welcome').classList.remove('dismissed');syncAnchor();syncWelcomeModes();save();};$('#fish-release').onclick=()=>storeCatch(true);$('#fish-keep').onclick=()=>storeCatch(false);
const reel=$('#leisure-action');reel.addEventListener('pointerdown',e=>{if(activity?.type==='fishing'&&activity.run.phase==='reeling'){activity.run.held=true;reel.setPointerCapture(e.pointerId);}});for(const event of ['pointerup','pointercancel','lostpointercapture'])reel.addEventListener(event,()=>{if(activity?.type==='fishing')activity.run.held=false;});reel.addEventListener('keydown',e=>{if([' ','Enter'].includes(e.key)&&activity?.run.phase==='reeling'){e.preventDefault();activity.run.held=true;}});reel.addEventListener('keyup',()=>{if(activity?.type==='fishing')activity.run.held=false;});window.addEventListener('blur',()=>{if(activity?.type==='fishing')activity.run.held=false;});

$('#instruments-toggle').onclick=()=>{const expanded=document.body.classList.toggle('instruments-open');$('#instruments-toggle').setAttribute('aria-pressed',String(expanded));};
$('#leisure-more').onclick=()=>{const expanded=$('#leisure-hud').classList.toggle('expanded');$('#leisure-more').setAttribute('aria-expanded',String(expanded));};

import "./clear-hud.css";

$('#sail-toggle').onclick=()=>{state.sailTarget=state.sailTarget?0:1;if(state.sailTarget&&state.anchored){state.anchored=false;syncAnchor();}save();toast(state.sailTarget?'돛을 펼칩니다 · 바람을 옆으로 받으면 힘을 얻고, 맞바람에서는 힘이 줄어요.':'돛을 접습니다 · 바람 추진력이 줄고 보조기관 레버로 이동할 수 있어요.');};

document.addEventListener('visibilitychange',()=>{if(document.hidden)keys={};});

function closeSignals(){ $('#signal-panel').hidden=true;$('#signal-toggle').setAttribute('aria-expanded','false'); }
$('#signal-toggle').onclick=()=>{const open=$('#signal-panel').hidden;$('#signal-panel').hidden=!open;$('#signal-toggle').setAttribute('aria-expanded',String(open));if(open)$('#signal-panel [data-signal]').focus();};
$('#signal-close').onclick=()=>{closeSignals();$('#signal-toggle').focus();};
$('#signal-stop').onclick=()=>{audio.stopSignals();$('#signal-status').textContent='재생 정지';};
for(const b of document.querySelectorAll('[data-signal]'))b.onclick=async()=>{try{if(await audio.playSignal(b.dataset.signal,spec.length))$('#signal-status').textContent=SOUND_SIGNALS[b.dataset.signal].name+' 재생';}catch{$('#signal-status').textContent='소리를 시작할 수 없어요';}};
document.addEventListener('pointerdown',e=>{if(!e.target.closest('#signal-panel,#signal-toggle'))closeSignals();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#signal-panel').hidden){closeSignals();$('#signal-toggle').focus();}});
