import {WEATHER,createWeather,stepWeather} from './weather.js';
import {lessons,RULES_URL,restoreSchool,beginWatch,observeWatch,stepWatch,watchHint} from './watch-school.js';
import {contactSolution} from './traffic.js';
import {stepTraffic,trafficAdvisory} from './traffic.js';
import {tripSnapshot,restoreTrip} from './trip-save.js';
import {countries,seaGate} from './harbor-data.js';
import {makeMission,localMission,missionTarget,bearingTo,recommendedDestinations} from './missions.js';
import {loadAtlas,drawAtlas} from './atlas.js';
import './style.css';
import {ships,regions,portLocations} from './data.js';
import {createVessel,stepVessel,canDock,applyBoundary,clamp} from './physics.js';
import {emptyCargo,cargoUnits,cargoPreset,stability,stepAttitude,canHandleCargo,liquidShip,BAY_NAMES} from './stability.js';
import {OceanScene} from './scene.js';
import {SeaAudio} from './audio.js';
import {planRoute} from './navigation.js';
import {officerPortrait} from './bridge.js';
import {helmMarkup,bindWheel,drawRadar} from './helm.js';
import {drawStability,lessonText} from './education.js';
const $=s=>document.querySelector(s);
let saved={};try{saved=JSON.parse(localStorage.getItem('yoonseul-save')||'{}')||{};}catch{}
let credits=Number.isFinite(saved.credits)&&saved.credits>=0?saved.credits:0;
let totalDistance=Number.isFinite(saved.distance)?saved.distance:0,deliveries=Number.isFinite(saved.deliveries)?saved.deliveries:0;
let region=regions.find(r=>r.id===(saved.mode?saved.region:'busan'))||regions.find(r=>r.id==='busan'),spec=ships.find(s=>s.id===saved.ship)||ships[1];
if(region.layout==='river'&&spec.draft>region.depth)spec=ships[0];
let state=createVessel(),cargo=emptyCargo(),simSpeed=3,weather='dynamic',timeMode='sunset';
let started=false,paused=false,zen=false,autopilot=false,mission=null,handling=null,ports=[],keys={},tab='menu',lastCollision=-100;
let fleetFilter='all',helmTarget=0,radarRange=3200,gameMode=saved.mode==='free'?'free':'mission',mapFilter='all',completedMission=null,routeKey='',routeChecked=-10;
let route=[],t=0,lesson=null,info=stability(spec,cargo),ocean;
let school=restoreSchool(saved.school),watchTask=null,quizFeedback={},trafficReplanAt=-100;
const audio=new SeaAudio(),weatherState=createWeather();
$('#app').innerHTML=`
<div id="ocean" aria-label="3D 항해 화면"></div><div class="vignette"></div>
<header class="topbar hud"><a class="brand" href="#" aria-label="윤슬"><span>≋</span> 윤슬</a><div class="location"><span id="region-title"></span><small id="place-name"></small></div><div class="top-actions"><button id="camera-toggle" aria-label="1인칭 브릿지로 전환">1인칭 브릿지</button><button id="menu" aria-label="항해 메뉴 열기"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg><span>메뉴</span></button></div></header>
<div id="voyage-hint" class="hud"><small id="mission-stage"></small><span id="mission-status">출항 준비 완료</span><div class="mission-next"><span id="mission-nav"></span><button id="mission-action" hidden></button></div></div>
<button id="weather-readout" class="hud" aria-label="날씨와 해상 상태 설정"></button><div id="sea-watch" class="hud" role="status" hidden></div><div id="watch-task" class="hud" hidden><span id="watch-task-text"></span><button id="watch-observe">표적 확인</button><button id="watch-details" aria-label="항해 실습 수첩 열기">수첩 ↗</button></div>${helmMarkup(officerPortrait)}
<div class="keyboard-hint hud">W / S 레버 &nbsp; A / D 조타 &nbsp; C 시점 &nbsp; Space 출항·정박 <button id="time-speed">항해 3×</button><button id="pause">일시정지</button></div>
<button id="exit-zen" hidden>항해 화면으로</button><div id="toast" role="status"></div>
<div id="welcome"><div class="welcome-content"><span class="welcome-kicker">바다가 기다립니다.</span><h1>오늘도<br/>좋은 항해를.</h1><p>레버를 올리고, 조타기를 돌려보세요.<br/>바다 위의 첫 항해가 시작됩니다.</p><div class="welcome-modes"><button data-start-mode="mission">미션 항해</button><button data-start-mode="free">자유 항해</button></div><button id="start">첫 화물 미션 시작 <span>↗</span></button><small>한국 · 중국 · 일본 / 24개 해역 · 75개 작업 수역</small></div></div>
<dialog id="panel"><div class="panel-head"><button id="panel-back" aria-label="항해 메뉴로">‹</button><h2 id="panel-title"></h2><button id="close-panel" aria-label="닫기">✕</button></div><div id="panel-body"></div></dialog>
<div id="rescue" hidden><h2>배가 크게 기울었습니다</h2><p>높거나 편중된 화물을 낮고 고르게 배치해 보세요.<br/>이 게임의 복원력 모델은 큰 각도의 실제 거동을 재현하지 않습니다.</p><button id="recover">항구로 복귀 · 안전하게 다시 적재</button></div><div id="error" hidden></div>`;
try{ocean=new OceanScene($('#ocean'));ocean.setShip(spec);ports=ocean.setRegion(region);}catch(error){$('#error').hidden=false;$('#error').textContent='3D 화면을 시작할 수 없습니다. 하드웨어 가속을 켠 Chrome 또는 Edge에서 다시 열어 주세요.';console.error(error);}
function atBerth(){return canHandleCargo(state,ports);}
function spawnAtPort(){state.x=ports[0]?.x||0;state.z=(ports[0]?.z||0)+46;state.anchored=true;syncAnchor();}
function save(){try{localStorage.setItem('yoonseul-save',JSON.stringify({school,credits,distance:totalDistance+state.distance,deliveries,ship:spec.id,region:region.id,mode:gameMode,trip:tripSnapshot(region,spec,state,cargo,mission,completedMission)}));}catch{}}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function refresh(){routeKey='';info=stability(spec,cargo);$('#region-title').textContent=region.name;$('#place-name').textContent=region.label;syncCamera();syncAnchor();}
function syncAnchor(){$('#anchor').classList.toggle('active',state.anchored);$('#anchor .anchor-label').textContent=state.anchored?'출항':'정박';$('#anchor').setAttribute('aria-label',state.anchored?'출항: 닻을 올리고 전진':'정박: 닻을 내려 멈추기');}
function commandThrottle(value){if(handling||state.capsized){toast(handling?'화물 작업이 끝나면 출항할 수 있어요.':'항구로 복귀한 뒤 다시 출항하세요.');return;}state.throttle=clamp(value,-.3,1);if(Math.abs(state.throttle)>.025){if(state.anchored){state.anchored=false;syncAnchor();toast('닻을 올렸습니다. 출항합니다.');}if(paused){paused=false;$('#pause').textContent='일시정지';}}setAuto(false);}
function commandSteer(value){if(handling||state.capsized)return;helmTarget=value;setAuto(false);}
const setWheel=bindWheel($('#steering-wheel'),commandSteer);
$('#center-wheel').onclick=()=>{commandSteer(0);setWheel(0);};
$('#weather-readout').onclick=()=>openPanel('settings');
$('#radar').onclick=e=>{
 if(!ocean?.world||watchTask)return;const rect=e.currentTarget.getBoundingClientRect(),x=((e.clientX-rect.left)/rect.width*320-160)*radarRange/143+state.x,z=((e.clientY-rect.top)/rect.height*320-160)*radarRange/143+state.z;
 const nearest=ocean.world.contacts.filter(c=>c.kind!=='whale'&&Math.hypot(c.x-state.x,c.z-state.z)<=radarRange).sort((a,b)=>Math.hypot(a.x-x,a.z-z)-Math.hypot(b.x-x,b.z-z))[0];
 ocean.world.trackedId=nearest&&Math.hypot(nearest.x-x,nearest.z-z)<radarRange*.13?nearest.id:null;
};
$('#radar-range').onclick=()=>{radarRange=({400:800,800:1600,1600:3200,3200:6400,6400:400})[radarRange];$('#radar-range').textContent=radarRange+' m';};

function syncCamera(){const bridge=ocean?.cameraMode===1;document.body.classList.toggle('bridge-view',bridge);$('#camera-toggle').textContent=bridge?'3인칭 선박':'1인칭 브릿지';$('#camera-toggle').setAttribute('aria-label',bridge?'3인칭 선박으로 전환':'1인칭 브릿지로 전환');}
function setCamera(mode){ocean?.setCamera(mode);syncCamera();}
function reset(){trafficReplanAt=-100;watchTask=null;if(ocean?.world)ocean.world.trackedId=null;totalDistance+=state.distance;state=createVessel();helmTarget=0;setWheel(0);cargo=emptyCargo();mission=null;handling=null;lesson=null;autopilot=false;simSpeed=3;$('#time-speed').textContent='항해 3×';$('#autopilot').classList.remove('active');spawnAtPort();completedMission=null;if(gameMode==='mission')mission=localMission(region,state,spec);$('#rescue').hidden=true;refresh();save();}
function openPanel(name){tab=name;keys={};if(!$('#panel').open)$('#panel').showModal();renderPanel();}
function closePanel(){$('#panel').close();keys={};}
function bind(selector,event,fn){const el=$(selector);if(el)el[event]=fn;}
function jobTarget(){return missionTarget(mission,region);}
function setMode(mode){if(handling)return toast('화물 작업이 끝난 뒤 모드를 바꿀 수 있어요.');gameMode=mode;setAuto(false);route=[];routeKey='';completedMission=null;mission=mode==='mission'?localMission(region,state,spec):null;save();if($('#panel').open)renderPanel();syncWelcomeModes();}
function syncWelcomeModes(){document.querySelectorAll('[data-start-mode]').forEach(b=>b.classList.toggle('chosen',b.dataset.startMode===gameMode));$('#start').innerHTML=(gameMode==='mission'?(mission&&mission.phase!=='loading'?'미션 이어하기':completedMission?'다음 항해 시작':'첫 화물 미션 시작'):'자유롭게 승선하기')+' <span>↗</span>';}
function acceptContract(destination,index=0){if(handling)return toast('진행 중인 화물 작업을 마쳐 주세요.');const nearest=localMission(region,state,spec).origin;const originIndex=ports.findIndex(p=>p.id===nearest.id);mission=makeMission(region,destination,Math.max(0,originIndex),index,spec);gameMode='mission';completedMission=null;setAuto(false);route=[];routeKey='';save();renderPanel();toast('금색 표시에서 화물을 싣고 레이더 항로를 따라가세요.');}
function crossSea(){if(!mission||mission.destinationRegion===region.id||mission.phase==='loading'||!state.anchored||!canDock(state,jobTarget()))return;const next=regions.find(r=>r.id===mission.destinationRegion);if(!next)return;region=next;trafficReplanAt=-100;watchTask=null;ports=ocean.setRegion(region);const gate=seaGate(region);state.x=gate.x;state.z=gate.z;state.heading=Math.PI;state.speed=0;state.throttle=0;state.anchored=true;helmTarget=0;mission.phase='sailing';route=[];routeKey='';autopilot=false;ocean.cameraSnap=true;refresh();save();toast('외해 구간 압축 이동 · '+region.name+' 입항 수역입니다. 레이더로 부두를 찾아가세요.');}
function routingObstacles(){return (ocean?.obstacles||[]).map(o=>o.hazard?{...o,radius:o.radius+65}:o);}
function updateRoute(){if(!mission){route=[];ocean?.setDestination(null);return;}const target=jobTarget(),key=region.id+mission.phase+target.name;if(key!==routeKey||(t-routeChecked>3&&route.length&&Math.hypot(state.x-route[0].x,state.z-route[0].z)>2000)){route=planRoute(state,target,routingObstacles(),spec.beam*.5+50)||[];routeKey=key;routeChecked=t;}while(route.length>1&&Math.hypot(state.x-route[0].x,state.z-route[0].z)<45)route.shift();ocean?.setDestination(target);}

const escapeText=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function schoolMarkup(){const nearby=(ocean?.world?.contacts||[]).filter(c=>c.kind!=='whale').map(c=>contactSolution(c,state,spec.beam)).sort((a,b)=>a.distance-b.distance);
 return `<div class="school-hero"><small>WATCHKEEPER / 항해 입문</small><h3>바다에서 만나고,<br>수첩에서 이해하기.</h3><p>항로에서 만나는 표적을 선택 → 700 m 안에서 표적 확인 → 직접 조타해 안전하게 통과하세요. 일부러 배에 접근할 필요는 없습니다.</p><div class="log-row"><span>안전 통과 <b>${school.log.filter(r=>r.success).length}회</b></span><span>개념 학습 <b>${school.passed.length} / ${lessons.length}</b></span></div></div>
 ${watchTask?`<div class="job-card"><small>진행 중인 관측</small><h3>${escapeText(watchTask.name)}</h3><p>확인 ${watchTask.observed?'완료':'대기'} · 직접 항해 ${Math.round(watchTask.travel)} m</p><button id="watch-cancel">관측 종료</button></div>`:''}
 <h3>주변에서 실습할 표적</h3><p class="fine">선택한 배는 레이더에서 청록색 원으로 표시됩니다. 1×로 관측을 시작합니다. 안전 거리가 줄면 먼저 감속·회피하세요.</p><div class="school-contacts">${nearby.slice(0,8).map(c=>`<button data-watch="${c.id}"><span>${c.name}<small>${watchHint(c)}</small></span><b>${Math.round(c.distance)} m ↗</b></button>`).join('')||'<p>이 해역에는 실습 표적이 없습니다. 항해도에서 바다 항만으로 이동하세요.</p>'}</div>
 <details class="science-note"><summary>실습 기록 기준과 시뮬레이션 범위</summary><p class="fine">게임 기준: 250 m 이상에서 확인, 350 m 안을 통과한 뒤 460 m 밖으로 이격, 직접 항해 120 m 이상, 선체 여유 35 m 이상, 접촉·자동 항해 없이 6분(항해 시간) 이내. 이 수치는 게임 평가용이며 법정 안전거리나 COLREG 적합 판정이 아닙니다. 타선 위치·작업 정보는 관측 보조 표시이며 실제 레이더가 선종·작업을 자동 식별한다는 뜻이 아닙니다. 타선은 임의 순환과 겹침 방지 정지를 사용하며 완전한 국제해상충돌예방규칙 AI가 아닙니다. 등화의 가시 범위·전 신호 체계, 수로·통항분리·제한시계 항법은 재현하지 않습니다. 공인 훈련·자격 평가를 대신하지 않는 입문 게임입니다.</p></details>
 <h3>항해 상황을 읽는 6가지 연습</h3>${lessons.map(l=>`<details class="lesson-card"><summary>${school.passed.includes(l.id)?'✓':'○'} ${l.title}<small>${l.rule}</small></summary><p>${l.question}</p><div class="quiz-options">${l.options.map((o,i)=>`<button data-quiz="${l.id}" data-answer="${i}">${o}</button>`).join('')}</div>${quizFeedback[l.id]?`<p class="quiz-feedback" role="status">${quizFeedback[l.id]}</p>`:''}<a href="${RULES_URL}" target="_blank" rel="noreferrer">국제규칙 원문 확인 ↗</a></details>`).join('')}
 <h3>최근 관측 복기</h3>${school.log.length?school.log.map(r=>`<div class="school-log"><b>${r.success?'✓ 안전 통과':'↻ 다시 연습'} · ${escapeText(r.name)}</b><p>최소 선체 여유 ${r.minClearance} m · 직접 항해 ${r.travel} m</p><small>${escapeText(r.reason||'저장된 관측 기록')}</small></div>`).join(''):'<p class="fine">첫 관측을 시작하면 여기에 결과가 남습니다. 기록은 이 브라우저에 저장됩니다.</p>'}
 <p class="fine">항법 설명은 국제규칙 기준입니다. USCG 문서의 미국 Inland 예외는 적용하지 않았습니다. 실제 운항에는 최신 해도·항행통보·현지 항만 규정이 필요합니다.</p><a class="fleet-source" href="https://www.imo.org/en/ourwork/safety/pages/preventing-collisions.aspx" target="_blank" rel="noreferrer">IMO 항법 설명과 참고 자료 ↗</a>`;
}
function bindSchool(body){body.querySelectorAll('[data-watch]').forEach(b=>b.onclick=()=>{const c=ocean.world.contacts.find(c=>c.id===b.dataset.watch);if(!c)return;watchTask=beginWatch(c,state);ocean.world.trackedId=c.id;simSpeed=1;$('#time-speed').textContent='항해 1×';$('#pace-toggle').textContent='1× 항해';setAuto(false);closePanel();toast('청록색 레이더 표적을 관측하고 표적 확인을 누르세요.');});bind('#watch-cancel','onclick',()=>{watchTask=null;ocean.world.trackedId=null;renderPanel();});body.querySelectorAll('[data-quiz]').forEach(b=>b.onclick=()=>{const l=lessons.find(l=>l.id===b.dataset.quiz),correct=Number(b.dataset.answer)===l.answer;if(correct&&!school.passed.includes(l.id))school.passed.push(l.id);quizFeedback[l.id]=`${correct?'정답입니다.':'다시 생각해 보세요.'} ${l.explain}`;save();const open=[...body.querySelectorAll('details[open]')].map(e=>e.querySelector('summary').textContent.replace(/^[✓○] /,''));renderPanel();body.querySelectorAll('details').forEach(e=>{if(open.includes(e.querySelector('summary').textContent.replace(/^[✓○] /,'')))e.open=true;});});}
function updateWatchUI(){const el=$('#watch-task'),c=watchTask&&ocean?.world?.contacts.find(c=>c.id===watchTask.id);el.hidden=!c;if(!c)return;const s=contactSolution(c,state,spec.beam);$('#watch-task-text').textContent=`${c.name} · ${s.bearing.toFixed(0)}° / ${Math.round(s.distance)} m · CPA ${Math.round(s.cpa)} m · ${s.rawTcpa>0?`TCPA ${Math.round(s.rawTcpa)}초`:'이격/정지'}${watchTask.observed?' · 확인 ✓':''}`;$('#watch-observe').disabled=watchTask.observed||s.distance>700;$('#watch-observe').textContent=watchTask.observed?'확인 ✓':s.distance>700?'700 m 안에서 확인':'표적 확인';}
$('#watch-details').onclick=()=>openPanel('school');
$('#watch-observe').onclick=()=>{if(watchTask&&observeWatch(watchTask,ocean.world.contacts.find(c=>c.id===watchTask.id),state))toast('관측 기록. 레이더와 바깥 경계를 계속하며 직접 조타하세요.');};
function renderPanel(){
 const body=$('#panel-body');$('#panel-title').textContent={menu:'항해 수첩',fleet:'승선할 배',chart:'항해도와 해역',jobs:'운송 의뢰',cargo:'선적 · 하역 · 복원력',settings:'항해 환경',school:'항해 실습 수첩'}[tab];$('#panel-back').hidden=tab==='menu';
 if(tab==='menu')body.innerHTML=`<div class="mode-switch"><button data-mode="mission" class="${gameMode==='mission'?'chosen':''}">미션 항해</button><button data-mode="free" class="${gameMode==='free'?'chosen':''}">자유 항해</button></div><div class="officer-intro">${officerPortrait}<div><small>당직 항해사</small><h3>${spec.en}</h3><p>${spec.name} · ${region.name}</p></div></div><button class="school-entry" data-panel="school"><span>당직 항해 실습</span><small>타선 관측 · 안전 통과 · COLREG 퀴즈 ↗</small></button><div class="menu-grid"><button data-panel="fleet"><span>⚓</span>선박 선택<small>13척의 서로 다른 실루엣</small></button><button data-panel="chart"><span>⌁</span>항해도<small>한국 · 중국 · 일본</small></button><button data-panel="cargo"><span>▦</span>화물 · 복원력<small>싣고, 기울고, 돌아오고</small></button><button data-panel="jobs"><span>▤</span>운송 의뢰<small>선적부터 하역까지</small></button></div><div class="log-row"><span>항해 수익 <b id="credits">₩ ${credits.toLocaleString('ko-KR')}</b></span><span>운송 ${deliveries}회</span></div><div class="menu-actions"><button id="settings">환경 설정</button><button id="sound">${audio.active?'소리 끄기':'소리 켜기'}</button><button id="zen">물멍 모드</button><button id="photo">사진 저장</button><button id="menu-pause">${paused?'항해 계속':'일시정지'}</button><button id="menu-speed">항해 ${simSpeed}×</button></div>`;
 if(tab==='school')body.innerHTML=schoolMarkup();
 if(tab==='fleet')body.innerHTML=`<div class="fleet-feature"><img src="${import.meta.env.BASE_URL}fleet/${spec.id}.webp" alt="${spec.name} 3D 모델 적재 예시"><small>${spec.name}${spec.brand?' · 선사 참고 도장':''}</small><h3>${spec.en}</h3><p>${spec.type}</p><div class="fleet-tags">${spec.features.map(f=>`<span>${f}</span>`).join('')}</div><div class="fleet-specs"><span>게임 전장 <b>${spec.length} m</b></span><span>폭 <b>${spec.beam} m</b></span><span>게임 최고 속력 <b>${spec.maxSpeed} kn</b></span></div><div class="fleet-preview-actions"><button id="fleet-inspect">3D로 둘러보기</button><button id="fleet-bridge" class="secondary">브릿지 승선</button></div><button id="fleet-load" class="fleet-load">기본 화물 싣고 살펴보기</button>${spec.source?`<a class="fleet-source" href="${spec.source}" target="_blank" rel="noreferrer">${spec.reference} ↗</a>`:''}</div><p class="fleet-note">실제 선종을 참고한 게임용 축소 모델입니다. 선사 도장은 비공식 창작 표현이며 실제 선박의 정밀 복제·공식 제휴 모델은 아닙니다. 위 이미지는 적재 예시입니다.</p><div class="fleet-filters" aria-label="선박 분류">${[['all','전체 13'],['cargo','상선'],['passenger','여객'],['work','작업선'],['leisure','요트']].map(([id,name])=>`<button data-filter="${id}" class="${fleetFilter===id?'chosen':''}">${name}</button>`).join('')}</div><div class="fleet-list">${ships.filter(s=>fleetFilter==='all'||s.category===fleetFilter).map(s=>`<button class="ship-card ${s.id===spec.id?'chosen':''}" data-ship="${s.id}"><img loading="lazy" src="${import.meta.env.BASE_URL}fleet/${s.id}.webp" alt="${s.name}"><div><small>${s.name}</small><h3>${s.en}</h3><p>${s.features[0]} · ${s.maxSpeed} kn</p></div><span>${s.id===spec.id?'승선 중':'↗'}</span></button>`).join('')}</div><p class="fine">선박 변경 시 진행 중인 의뢰와 화물을 초기화합니다. 강에서는 요트만 항해할 수 있어요.</p>`;
 if(tab==='chart')body.innerHTML=`<canvas id="atlas" width="700" height="450" aria-label="한국 중국 일본의 항만 위치 지도"></canvas><p class="chart-key">24개 해역 · 75개 작업 수역 / ${countries[region.country]} · ${region.name}</p><div class="map-filters">${[['all','전체'],['KR','한국'],['CN','중국'],['JP','일본']].map(([id,label])=>`<button data-map-filter="${id}" class="${mapFilter===id?'chosen':''}">${label}</button>`).join('')}</div><div class="region-list">${regions.filter(r=>mapFilter==='all'||r.country===mapFilter).map(r=>`<button data-region="${r.id}" class="region-card ${r.id===region.id?'chosen':''}"><small>${countries[r.country]} · ${r.en}</small><h3>${r.name}</h3><p>${r.ports.join(' · ')}</p><span>${r.id===region.id?'현재 해역':gameMode==='mission'?'이곳 미션 시작':'자유 항해로 이동'}</span></button>`).join('')}</div><details class="science-note"><summary>현재 해역 상세도 · 레이더 범례</summary><p class="fine">흰 삼각형: 통항 선박 · 주황 선: 어망 · 주황 ×: 표류물 · 파란 타원: 고래 관찰 안내(실제 레이더 반사 표적 아님)</p><canvas id="map" width="700" height="350" aria-label="현재 선박과 항구의 항해도"></canvas></details><p class="fine">광역 지도는 공개 해안선 자료를 사용합니다. 18개 항만 배경 지형은 Mapzen Terrain Tiles(USGS·NOAA)의 공개 고도 자료입니다. 높이·거리는 연출용으로 조정했고 항로를 평탄화했습니다. 부두는 게임용 배치로 실측 3D 항만이 아닙니다. 해역을 직접 선택하면 현재 의뢰·화물이 초기화됩니다. 해외 운송은 운송 의뢰에서 시작하세요.</p>${region.source?`<a class="fleet-source" href="${region.source}" target="_blank" rel="noreferrer">항만 배치 참고 자료 ↗</a>`:''}`;
 if(tab==='jobs')body.innerHTML=`<p class="panel-intro">① 금색 작업 수역에서 선적<br/>② 레이더의 금색 항로로 항해<br/>③ 목적지에서 정박하고 하역</p><div class="log-row"><span>항해 수익 <b id="credits">₩ ${credits.toLocaleString('ko-KR')}</b></span><span>완료 ${deliveries}회</span></div>${mission?`<div class="job-card"><small>${{loading:'① 선적 대기',sailing:'② 항해 중',crossing:'② 외해 횡단 대기',arrived:'③ 하역 대기'}[mission.phase]}</small><h3>${mission.origin.name} → ${mission.name}</h3><p>${regions.find(r=>r.id===mission.originRegion)?.name} 출발 · ${mission.destinationRegionName}<br/>${spec.cargo} ${mission.units||6}단위 · 보상 ₩ ${mission.reward.toLocaleString('ko-KR')}</p><div class="job-buttons">${mission.phase==='loading'?'<button id="job-load">선적 시작</button>':mission.phase==='crossing'?'<button id="job-cross">도착 해역으로 항해</button>':'<button id="job-unload">하역 · 운송 정산</button>'}<button id="job-auto" class="secondary">레이더 항로로 자동 항해</button><button data-panel="cargo" class="secondary">적재 상태</button><button id="job-cancel" class="text-button">다른 의뢰 고르기</button></div></div>`:`${completedMission?`<div class="delivery-complete">배송 완료 · ₩ ${completedMission.reward.toLocaleString('ko-KR')}<small>${completedMission.name}에 화물을 인도했습니다.</small></div>`:''}<h3>현재 해역의 운송</h3>${ports.filter(p=>p.id!==localMission(region,state,spec).origin.id).map(p=>`<div class="job-card"><small>${spec.cargo}</small><h3>${p.name}</h3><p>${p.berth} · 화물 6단위</p><button data-job="${ports.indexOf(p)}">의뢰 받기</button></div>`).join('')} ${region.layout!=='river'?`<h3>국내 · 해외 항로</h3><div class="voyage-destinations">${recommendedDestinations(region).map(r=>`<button data-contract-region="${r.id}"><small>${countries[r.country]}</small><b>${r.name}</b><span>${r.ports[0]} ↗</span></button>`).join('')}</div><label class="contract-label">전체 목적지<select id="contract-region">${regions.filter(r=>r.layout!=='river'&&r.id!==region.id).map(r=>`<option value="${r.id}">${countries[r.country]} · ${r.name}</option>`).join('')}</select></label><label class="contract-label">도착 작업 수역<select id="contract-port"></select></label><button id="accept-contract" class="primary-contract">이 항구로 운송하기</button>`:''}`}<div id="handling-info" class="handling-info" ${handling?'':'hidden'}><span id="handling-label"></span><progress id="handling-progress" max="1" value="0"></progress></div><p class="fine">하역 조건: 목적지 95 m 이내 · 2.7 kn 미만 · 정박. 외해 운송은 출항 지점에서 긴 항로를 압축 이동한 뒤 도착 해역을 직접 항해합니다. 가상의 운송 의뢰이며 실제 정기항로 정보는 아닙니다.</p>`;
 if(tab==='cargo')renderCargo(body);
 if(tab==='settings')body.innerHTML=`<h3>시간</h3><div class="segmented">${[['day','한낮'],['sunset','노을'],['night','밤바다']].map(([id,n])=>`<button data-time="${id}" class="${timeMode===id?'chosen':''}">${n}</button>`).join('')}</div><h3>바람과 파도</h3><div class="segmented">${Object.entries({dynamic:{name:'자동 날씨'},...WEATHER}).map(([id,w])=>`<button data-weather="${id}" class="${weather===id?'chosen':''}">${w.name}</button>`).join('')}</div><p class="fine">자동 날씨: 맑음 → 거친 물결 → 돌풍이 서서히 변합니다. 태풍은 직접 선택하는 체험 모드입니다. 실제 예보가 아닌 게임용 날씨이며 배속과 관계없이 변화합니다. 강풍에서는 감속하고 주위 선박을 자주 확인하세요.</p><h3>시점</h3><div class="segmented"><button id="camera-bridge" class="${ocean?.cameraMode===1?'chosen':''}">1인칭 브릿지</button><button id="camera-follow" class="${ocean?.cameraMode===0?'chosen':''}">3인칭 선박</button></div><h3>레이더 읽기</h3><p class="fine">숫자를 눌러 400 m–6.4 km 범위를 바꾸고, 선박 표적을 누르면 추적합니다. 흰 삼각형은 선박, 뒤쪽 선은 지난 궤적, 앞쪽 선은 60초 예상 이동입니다. 주황 선은 어망, 원은 작업 구역, ×는 표류물입니다. 파란 고래와 어구는 학습용 보조 표시이며 실제 레이더에서 항상 탐지되는 물체는 아닙니다.</p><h3>바다 소리 · 항해 BGM</h3><div class="menu-actions"><button id="music-toggle" aria-pressed="${audio.musicEnabled}">항해 BGM ${audio.musicEnabled?'켜짐':'꺼짐'}</button><button id="ambient-horns" aria-pressed="${audio.ambientHorns}">먼 고동 ${audio.ambientHorns?'켜짐':'꺼짐'}</button></div><label class="volume">BGM 음량 <input id="music-volume" type="range" min="0" max="100" value="${audio.musicVolume*100}"></label><label class="volume">음량 <input id="volume" type="range" min="0" max="100" value="${audio.volume*100}"></label><div class="menu-actions"><button id="sound">${audio.active?'소리 끄기':'소리 켜기'}</button><button id="menu-pause">${paused?'항해 계속':'일시정지'}</button><button id="menu-speed">항해 ${simSpeed}×</button></div><p class="fine">화면 좌우 드래그: 둘러보기 · 위아래: 시점 높이 · 항해 배속 1×/3×/8×/20× · W/S: 출력 · A/D: 조타 · C: 시점 · F: 고동 · Space: 닻 · P: 자동 항해 · H: 물멍<br/>메뉴를 열면 이동은 멈추지만 파도와 배의 흔들림은 계속 관찰할 수 있어요.</p>`;
 bindSchool(body);
 body.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));body.querySelectorAll('[data-map-filter]').forEach(b=>b.onclick=()=>{mapFilter=b.dataset.mapFilter;renderPanel();});
 if(tab==='chart')loadAtlas().then(()=>drawAtlas($('#atlas'),regions,region,mission));
 body.querySelectorAll('[data-contract-region]').forEach(b=>b.onclick=()=>acceptContract(regions.find(r=>r.id===b.dataset.contractRegion)));
 if($('#contract-region')){const fill=()=>{const r=regions.find(r=>r.id===$('#contract-region').value);$('#contract-port').innerHTML=r.ports.map((p,i)=>`<option value="${i}">${p}</option>`).join('');};fill();$('#contract-region').onchange=fill;$('#accept-contract').onclick=()=>acceptContract(regions.find(r=>r.id===$('#contract-region').value),Number($('#contract-port').value));}
 body.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{fleetFilter=b.dataset.filter;renderPanel();});
 bind('#fleet-inspect','onclick',()=>{setCamera(0);closePanel();});bind('#fleet-bridge','onclick',()=>{setCamera(1);closePanel();});bind('#fleet-load','onclick',()=>{if(beginHandling('기본 화물 선적',{bays:[1,1,1,1,1,1],high:false,ballast:false})){setCamera(0);closePanel();}});
 body.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));
 body.querySelectorAll('[data-ship]').forEach(b=>b.onclick=()=>{if(handling)return toast('화물 작업이 끝난 뒤 선박을 변경하세요.');const next=ships.find(s=>s.id===b.dataset.ship);if(region.layout==='river'&&next.draft>region.depth)return toast('강에서는 요트로 항해하세요.');spec=next;ocean?.setShip(spec);reset();renderPanel();$('#panel').scrollTop=0;});
 body.querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>{if(handling)return toast('화물 작업이 끝난 뒤 해역을 변경하세요.');region=regions.find(r=>r.id===b.dataset.region);if(region.layout==='river'&&spec.draft>region.depth){spec=ships[0];ocean?.setShip(spec);}watchTask=null;ports=ocean?.setRegion(region)||[];reset();renderPanel();});
 body.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>acceptContract(region,Number(b.dataset.job)));
 body.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{timeMode=b.dataset.time;ocean?.setTime(timeMode);renderPanel();});body.querySelectorAll('[data-weather]').forEach(b=>b.onclick=()=>{weather=b.dataset.weather;renderPanel();});
 bind('#music-toggle','onclick',()=>{audio.setMusic(!audio.musicEnabled);renderPanel();});bind('#ambient-horns','onclick',()=>{audio.setAmbientHorns(!audio.ambientHorns);renderPanel();});bind('#music-volume','oninput',e=>audio.setMusicVolume(e.target.value/100));bind('#volume','oninput',e=>audio.setVolume(e.target.value/100));bind('#settings','onclick',()=>openPanel('settings'));bind('#sound','onclick',toggleSound);bind('#zen','onclick',()=>{closePanel();toggleZen();});bind('#photo','onclick',()=>{closePanel();ocean?.screenshot();toast('바다의 순간을 저장했습니다.');});
 bind('#menu-pause','onclick',()=>{togglePause();renderPanel();});bind('#menu-speed','onclick',()=>{cycleSpeed();renderPanel();});
 bind('#camera-follow','onclick',()=>{setCamera(0);closePanel();});bind('#camera-bridge','onclick',()=>{setCamera(1);closePanel();});
 bind('#job-cross','onclick',()=>{crossSea();closePanel();});bind('#job-load','onclick',()=>loadMission());bind('#job-unload','onclick',()=>unloadMission());bind('#job-auto','onclick',()=>{if(setAuto(true))closePanel();});
 bind('#job-cancel','onclick',()=>{if(handling)return toast('작업 중에는 취소할 수 없습니다.');mission=null;route=[];routeKey='';setAuto(false);renderPanel();});
}
function renderCargo(body){
 const editable=atBerth()&&!handling&&!state.capsized;info=stability(spec,cargo);
 body.innerHTML=`<div class="cargo-status"><span class="berth ${editable?'ready':''}">${editable?'항구에 정박 · 화물 작업 가능':handling?'화물 작업 중':'항구에 정박하면 적재 변경 가능'}</span><b id="cargo-unit-count">${cargoUnits(cargo)} / 18 단위</b></div>
 <canvas id="stability-canvas" width="660" height="245" aria-label="화물의 무게중심 G, 메타센터 M과 복원정 그래프"></canvas>
 <div class="stability-values"><div><small>GM · 초기 복원성</small><b id="gm-value">${info.gm.toFixed(2)} m</b></div><div><small>롤링 · 좌우</small><b id="roll-value">0.0°</b></div><div><small>피칭 · 앞뒤</small><b id="pitch-value">0.0°</b></div></div>
 <p id="stability-explanation" class="lesson-explanation"></p>
 <details ${lesson?'open':''} class="learning"><summary>항해사 실습 · 직접 비교하기</summary><div class="preset-buttons"><button data-preset="low" ${!editable?'disabled':''}>① 낮고 고르게</button><button data-preset="high" ${!editable||liquidShip(spec)?'disabled':''}>② 높이 쌓기</button><button data-preset="list" ${!editable?'disabled':''}>③ 좌현에 몰기</button></div><p id="lesson-result">${lesson?.text||'같은 12단위 화물을 낮게·높게 비교하거나, 좌현 편중으로 평균 기울기를 관찰해 보세요.'}</p><button id="observe" class="secondary">3인칭으로 움직임 관찰</button></details>
 <div class="cargo-layout"><div class="bow-label">↑ 선수</div><div class="bay-columns"><span>좌현</span><span>우현</span></div><div class="bay-grid">${cargo.bays.map((n,i)=>`<div class="bay"><small>${BAY_NAMES[i]}</small><div class="bay-fill">${[0,1,2].map(j=>`<i class="${j<n?'filled':''}"></i>`).join('')}</div><div class="bay-buttons"><button data-bay="${i}" data-change="-1" aria-label="${BAY_NAMES[i]} 하역" ${!editable||n===0?'disabled':''}>−</button><b>${n}</b><button data-bay="${i}" data-change="1" aria-label="${BAY_NAMES[i]} 선적" ${!editable||n===3?'disabled':''}>＋</button></div></div>`).join('')}</div><div class="stern-label">선미</div></div>
 ${!liquidShip(spec)?`<label class="check-row"><input id="high-cargo" type="checkbox" ${cargo.high?'checked':''} ${!editable?'disabled':''}> 화물을 높은 갑판에 배치</label>`:'<p class="fine">탱크 1·2칸: 부분 적재 / 3칸: 가득 참. 부분 적재 탱크에는 자유수면 보정이 적용됩니다.</p>'}
 <label class="check-row"><input id="ballast" type="checkbox" ${cargo.ballast?'checked':''} ${!editable?'disabled':''}> 낮은 밸러스트 탱크 채우기</label>
 <div class="cargo-footer"><span id="draft-value">흘수 ${info.draft.toFixed(1)} m</span><span id="kg-value">KG ${info.kg.toFixed(2)} m</span><button id="empty-cargo" ${!editable?'disabled':''}>전체 하역</button></div>
 <div id="handling-info" class="handling-info" ${handling?'':'hidden'}><span id="handling-label"></span><progress id="handling-progress" max="1" value="0"></progress></div>
 <details class="science-note"><summary>복원력을 읽는 법</summary><p>G는 무게중심, M은 작은 기울기에서의 메타센터입니다. GM = KM − KG에서 액체 자유수면 영향을 보정합니다. 작은 각도에서 GZ ≈ GM × sin(기울기)이며, 편중 화물은 이 관계에 추가 영향을 줍니다.</p><p>GM이 커지면 보통 더 빠르게 돌아오지만 흔들림이 거칠 수 있습니다. GM 하나로 실제 선박의 안전을 판단할 수는 없습니다. 이 화면의 선체 계수·하중·파도 응답은 교육용 근사치입니다.</p><a href="https://www.imo.org/en/ourwork/safety/pages/shipdesignandstability-default.aspx" target="_blank" rel="noreferrer">IMO 선박 복원성 자료 ↗</a></details>`;
 body.querySelectorAll('[data-bay]').forEach(b=>b.onclick=()=>{if(!canEdit())return;const next=structuredClone(cargo);next.bays[Number(b.dataset.bay)]=clamp(next.bays[Number(b.dataset.bay)]+Number(b.dataset.change),0,3);beginHandling(Number(b.dataset.change)>0?'선적':'하역',next);});
 body.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{if(!canEdit())return;const id=b.dataset.preset,next=cargoPreset(id),before=stability(spec,cargo),after=stability(spec,next);lesson={id,text:`${id==='list'?'좌현 편중':'같은 12단위 비교'} · GM ${before.gm.toFixed(2)} → ${after.gm.toFixed(2)} m. ${id==='low'?'G가 낮아졌을 때 복원 속도를 관찰하세요.':id==='high'?'G가 올라가면 GM이 작아집니다. 낮은 적재와 비교하세요.':'기울어진 쪽이 계속 낮게 유지되는 횡경사를 관찰하세요.'}`};beginHandling('적재 재배치',next);});
 bind('#high-cargo','onchange',e=>{if(canEdit())beginHandling('적재 재배치',{...structuredClone(cargo),high:e.target.checked});});bind('#ballast','onchange',e=>{if(canEdit())beginHandling('밸러스트 조절',{...structuredClone(cargo),ballast:e.target.checked});});bind('#empty-cargo','onclick',()=>{if(canEdit())beginHandling('전체 하역',emptyCargo());});bind('#observe','onclick',()=>{setCamera(0);closePanel();toast('항해 수첩 → 화물·복원력에서 실시간 수치를 비교하세요.');});
}
function canEdit(){if(handling){toast('진행 중인 화물 작업을 마쳐 주세요.');return false;}if(!atBerth()){toast('항구에서 감속한 뒤 닻을 내려야 합니다.');return false;}return true;}
function beginHandling(label,next,onComplete){if(!canEdit())return false;handling={label,next,onComplete,progress:0,duration:3};state.throttle=0;setAuto(false);if($('#panel').open)renderPanel();return true;}
function loadMission(){if(!mission||mission.phase!=='loading')return;if(mission.originRegion!==region.id||!canDock(state,mission.origin))return toast('출발 항구에서 선적하세요.');beginHandling('화물 선적',{bays:[1,1,1,1,1,1],high:false,ballast:false},()=>{if(mission)mission.phase='sailing';toast('선적 완료. 흘수와 복원력을 확인하고 출항하세요.');});}
function unloadMission(){if(!mission||mission.phase==='loading')return toast('먼저 출발 항구에서 선적하세요.');if(mission.destinationRegion!==region.id||!canDock(state,mission))return toast('도착 항구 반경 95 m 안에서 2.7 kn 미만으로 감속하세요.');if(cargoUnits(cargo)<6)return toast('계약 화물 6단위가 필요합니다.');const reward=mission.reward;beginHandling('도착 화물 하역',emptyCargo(),()=>{credits+=reward;deliveries++;completedMission={name:mission.name,portId:mission.id,reward};mission=null;route=[];routeKey='';save();toast('하역 완료 · ₩ '+reward.toLocaleString('ko-KR')+' 지급');});}
function setAuto(value){if(value&&(handling||state.capsized))return false;if(value&&mission){route=planRoute(state,jobTarget(),routingObstacles(),spec.beam*.5+50);if(!route){toast('안전한 자동 항로를 찾지 못했습니다. 수동으로 수로로 이동하세요.');return false;}}autopilot=value;$('#autopilot').classList.toggle('active',value);if(value){helmTarget=0;state.anchored=false;syncAnchor();toast(mission?'지정 항구로 자동 항해합니다.':'현재 방위를 유지합니다.');}return true;}
function toggleAnchor(){if(handling)return toast('화물 작업이 끝난 뒤 출항하세요.');if(state.anchored){commandThrottle(.65);}else{state.anchored=true;state.throttle=0;helmTarget=0;setAuto(false);syncAnchor();}}

function togglePause(){paused=!paused;$('#pause').textContent=paused?'항해 계속':'일시정지';}
function cycleSpeed(){simSpeed=simSpeed===3?8:simSpeed===8?20:simSpeed===20?1:3;$('#time-speed').textContent='항해 '+simSpeed+'×';$('#pace-toggle').textContent=simSpeed+'× 항해';}
function toggleZen(){zen=!zen;document.body.classList.toggle('zen',zen);$('#exit-zen').hidden=!zen;}
async function blowHorn(){try{const played=await audio.soundHorn(spec.length);if(played)toast('고동 —');else if(!audio.active)toast('메뉴에서 소리를 켜면 고동을 울릴 수 있어요.');}catch{toast('오디오를 시작할 수 없습니다.');}}
$('#horn').onclick=blowHorn;
async function toggleSound(){try{await audio.toggle();if($('#panel').open)renderPanel();}catch{toast('오디오를 시작할 수 없습니다.');}}
document.querySelectorAll('[data-start-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.startMode));syncWelcomeModes();
$('#start').onclick=async()=>{if(gameMode==='mission'&&!mission&&!completedMission)mission=localMission(region,state,spec);started=true;$('#welcome').classList.add('dismissed');setCamera(0);await toggleSound();};
$('#officer').onclick=()=>openPanel('menu');$('#menu').onclick=()=>openPanel('menu');$('#panel-back').onclick=()=>openPanel('menu');$('#close-panel').onclick=closePanel;$('#panel').addEventListener('close',()=>keys={});
$('#camera-toggle').onclick=()=>setCamera(1-ocean.cameraMode);$('#motion-readout').onclick=()=>openPanel('cargo');$('#anchor').onclick=toggleAnchor;$('#autopilot').onclick=()=>setAuto(!autopilot);$('#exit-zen').onclick=toggleZen;
$('#throttle').oninput=e=>{const value=Number(e.target.value);commandThrottle(Math.abs(value)<4?0:value/100);};$('#pause').onclick=togglePause;$('#time-speed').onclick=cycleSpeed;$('#pace-toggle').onclick=cycleSpeed;
$('#recover').onclick=()=>{reset();paused=false;$('#pause').textContent='일시정지';toast('항구로 돌아왔습니다. 화물을 낮고 고르게 배치해 보세요.');};
window.addEventListener('keydown',e=>{if(!started||e.target.matches('input,textarea,select,[contenteditable=true],[role=slider]')||$('#panel').open)return;const k=e.key.toLowerCase();if(['w','a','s','d',' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys[k]=true;if((k==='w'||k==='arrowup')&&paused)commandThrottle(Math.max(.35,state.throttle));if(e.repeat)return;if(k===' ')toggleAnchor();if(k==='p')setAuto(!autopilot);if(k==='f')blowHorn();if(k==='h')toggleZen();if(k==='c')setCamera(1-ocean.cameraMode);if(k==='escape'&&zen)toggleZen();});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);window.addEventListener('blur',()=>keys={});
window.addEventListener('pagehide',save);setInterval(save,15000);
function drawMap(){const canvas=$('#map');if(!canvas)return;const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,scale=.12;c.fillStyle='#123641';c.fillRect(0,0,w,h);c.strokeStyle='#8bbbad20';for(let x=0;x<w;x+=35){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}for(let y=0;y<h;y+=35){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();}const project=p=>[w/2+(p.x-state.x)*scale,h*.65+(p.z-state.z)*scale];
 c.fillStyle='#416e65';for(const o of ocean?.obstacles||[]){const [x,y]=project(o);c.beginPath();c.ellipse(x,y,o.radius*scale,o.radius*scale*.8,0,0,Math.PI*2);c.fill();}if(region.layout==='river'){const left=w/2+(-310-state.x)*scale,right=w/2+(310-state.x)*scale;c.fillRect(0,0,left,h);c.fillRect(right,0,w-right,h);}
 if(mission){const [x,y]=project(jobTarget());c.setLineDash([5,6]);c.strokeStyle='#e7be7d';c.beginPath();c.moveTo(w/2,h*.65);c.lineTo(x,y);c.stroke();c.setLineDash([]);}for(const p of ports){const [x,y]=project(p);c.strokeStyle='#a9dcd1';c.beginPath();c.arc(x,y,6,0,Math.PI*2);c.stroke();c.font='16px sans-serif';c.fillStyle='#d1e1dc';c.fillText(p.name,x+12,y+5);}c.save();c.translate(w/2,h*.65);c.rotate(state.heading);c.beginPath();c.moveTo(0,-12);c.lineTo(8,9);c.lineTo(0,4);c.lineTo(-8,9);c.closePath();c.fillStyle='#f4d19a';c.fill();c.restore();c.fillStyle='#c3d7d5';c.font='17px sans-serif';c.fillText('N ↑',w-50,30);}
function updateUI(){
 const w=weatherState;$('#weather-readout').textContent=`${w.name||'산들바람'} · 바람 ${w.wind.toFixed(0)} m/s${w.group>1.18?' · 큰 파도 접근':''}`;$('#weather-readout').classList.toggle('storm',w.storm>.6);
 info=stability(spec,cargo);const roll=(state.roll*180/Math.PI).toFixed(1),pitch=(state.pitch*180/Math.PI).toFixed(1);
 $('#pace-toggle').textContent=simSpeed+'× 항해';$('#speed').textContent=(Math.abs(state.speed)/.5144).toFixed(1);$('#heading').textContent=String(((Math.round(state.heading*180/Math.PI)%360)+360)%360).padStart(3,'0')+'°';$('#roll').textContent=roll+'°';$('#pitch').textContent=pitch+'°';$('#throttle-value').textContent=Math.abs(state.throttle)<.025?'중립':(state.throttle<0?'후진 ':'전진 ')+Math.round(Math.abs(state.throttle)*100)+'%';$('#throttle').value=Math.round(state.throttle*100);$('#throttle').setAttribute('aria-valuetext',$('#throttle-value').textContent);setWheel(autopilot?state.rudder:helmTarget);$('#rudder-value').textContent=Math.abs(state.rudder)<.02?'중앙':(state.rudder<0?'좌현 ':'우현 ')+Math.round(Math.abs(state.rudder)*35)+'°';$('#throttle').disabled=!!handling||state.capsized;$('#stability-dot').classList.toggle('warning',info.status!=='안정');
 updateRoute();const action=$('#mission-action');action.hidden=true;$('#mission-nav').textContent='';$('#mission-stage').textContent=gameMode==='mission'?'미션 항해 · ① 선적 → ② 항해 → ③ 하역':'자유 항해';
 if(paused)$('#mission-status').textContent='일시정지';else if(handling)$('#mission-status').textContent=handling.label+' '+Math.round(handling.progress*100)+'%';else if(mission){const target=jobTarget(),next=route[0]||target,nav=bearingTo(state,next),dist=Math.round(Math.hypot(state.x-target.x,state.z-target.z));$('#mission-status').textContent=(mission.phase==='loading'?'선적 · ':target.isGate?'출항 · ':'하역 · ')+target.name;$('#mission-nav').textContent=`${dist} m · ${String(nav.bearing).padStart(3,'0')}° · ${Math.abs(nav.relative)<8?'앞으로':nav.relative>0?'우현으로':'좌현으로'}${route.length>1?' · 경유지 '+route.length+'개':''}`;
 if(dist<95){action.hidden=false;if(!state.anchored||Math.abs(state.speed)>=1.4){action.textContent=state.anchored?'감속 중…':'정박하기';action.onclick=()=>{if(!state.anchored)toggleAnchor();};}else if(target.isGate){action.textContent='도착 해역으로';action.onclick=crossSea;}else{action.textContent=mission.phase==='loading'?'선적 시작':'하역 시작';action.onclick=mission.phase==='loading'?loadMission:unloadMission;}}
 else{action.hidden=false;action.textContent=autopilot?'수동 조타':'자동 항해';action.onclick=()=>setAuto(!autopilot);}}
 else if(completedMission){$('#mission-status').textContent='배송 완료 · ₩ '+completedMission.reward.toLocaleString('ko-KR');action.hidden=false;action.textContent='다음 미션';action.onclick=()=>openPanel('jobs');}
 else if(gameMode==='mission'){$('#mission-status').textContent='다음 화물의 목적지를 선택하세요';action.hidden=false;action.textContent='미션 선택';action.onclick=()=>openPanel('jobs');}
 else if(info.status!=='안정'){$('#mission-status').textContent=info.status+' · 적재 상태를 확인하세요';action.hidden=false;action.textContent='복원력 보기';action.onclick=()=>openPanel('cargo');}
 else $('#mission-status').textContent=state.anchored?'레버를 올리거나 출항을 눌러보세요':autopilot?'자동 항해 중':spec.name+' · '+(weatherState.name||'산들바람');
 if($('#stability-canvas')){drawStability($('#stability-canvas'),state,spec,cargo);$('#gm-value').textContent=info.gm.toFixed(2)+' m';$('#gm-value').classList.toggle('warning-text',info.gm<.5);$('#roll-value').textContent=roll+'°';$('#pitch-value').textContent=pitch+'°';$('#stability-explanation').textContent=lessonText(info,state,cargo);}
 if($('#handling-info')){$('#handling-info').hidden=!handling;if(handling){$('#handling-label').textContent=handling.label+' · '+Math.round(handling.progress*100)+'%';$('#handling-progress').value=handling.progress;}}
 const near=ocean?.world?trafficAdvisory(ocean.world,state,spec.beam):null,tracked=ocean?.world?.contacts.find(c=>c.id===ocean.world.trackedId),contact=near?.danger?near:tracked?contactSolution(tracked,state,spec.beam):near;
 updateWatchUI();
 const watch=$('#sea-watch');if(watch){watch.hidden=!contact;watch.classList.toggle('danger',!!contact?.danger);if(contact)watch.textContent=`${contact.danger?'⚠ ':''}${contact.name} · ${Math.round(contact.distance)} m · ${tracked&&!near?.danger?(contact.rawTcpa>0?`최근접 ${Math.round(contact.cpa)} m / ${Math.ceil(contact.tcpa)}초 뒤`:'멀어지는 중'):watchHint(contact)}`;}
 if(ocean)ocean.navRoute=route;drawMap();drawRadar($('#radar'),state,ocean?.obstacles||[],ports,mission?jobTarget():null,t,radarRange,region.layout==='river',route,ocean?.world);drawAtlas($('#atlas'),regions,region,mission);
 $('#control-tip').textContent=handling?'화물 작업 중 · 잠시 후 출항할 수 있어요':paused?'일시정지 · 레버를 올리면 다시 항해합니다':autopilot?'자동 항해 중 · 휠이나 레버를 움직이면 수동 전환':state.anchored?'레버를 위로 올리면 출항 · 휠을 돌리면 조타':Math.abs(state.speed)<.5&&Math.abs(state.throttle)>.1?'기관 가동 중 · 배가 서서히 속도를 올립니다':'휠을 돌려 방향 조절 · 정박 버튼으로 멈추기';
}
let last=performance.now(),uiTimer=0;
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;const active=started&&!paused&&!$('#panel').open&&!document.hidden&&!handling&&!state.capsized;if(started&&!paused&&!document.hidden)stepWeather(weatherState,dt,weather,region);const strength=weatherState.strength??region.wave,wind=weatherState.wind;
 if(!paused&&!document.hidden){t+=dt;
 if(handling){handling.progress=clamp(handling.progress+dt/handling.duration,0,1);if(handling.progress>=1){const done=handling;cargo=done.next;handling=null;done.onComplete?.();save();if($('#panel').open)renderPanel();refresh();}}
 // Attitude remains at real time, including while a menu is open; voyage time warp affects translation only.
 stepAttitude(state,spec,cargo,{wave:strength,wind,windDirection:weatherState.direction},t,dt);
 }
 if(active){for(let i=0;i<simSpeed;i++){
 if(ocean?.world)stepTraffic(ocean.world,dt,{...state,assisted:autopilot});const before={x:state.x,z:state.z},wasAuto=autopilot;
 const throttleKey=(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0),steerKey=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0);if(throttleKey)commandThrottle(state.throttle+throttleKey*dt*.5);if(steerKey)commandSteer(clamp(helmTarget+steerKey*dt*1.2,-1,1));const input={throttle:0,steer:helmTarget};
 if(autopilot){state.throttle=.65;const target=jobTarget();if(target){if(route.length>1&&Math.hypot(route[0].x-state.x,route[0].z-state.z)<30)route.shift();const waypoint=route[0]||target;const dist=Math.hypot(target.x-state.x,target.z-state.z),desired=Math.atan2(waypoint.x-state.x,-(waypoint.z-state.z)),diff=Math.atan2(Math.sin(desired-state.heading),Math.cos(desired-state.heading));input.steer=clamp(diff*2,-1,1);if(Math.abs(diff)>.4||route.length>1)state.throttle=.3;const stopping=state.speed/(spec.accel*.18)*(info.mass/(spec.mass*100))+85;if(route.length<=1&&dist<stopping)state.throttle=.08;if(route.length<=1&&dist<78){state.throttle=0;state.anchored=true;syncAnchor();if(canDock(state,target)){setAuto(false);if(mission.phase==='sailing')mission.phase=target.isGate?'crossing':'arrived';toast(mission.phase==='loading'?'선적 항구 도착. 선적을 시작하세요.':target.isGate?'출항 지점 도착. 도착 해역으로 이동하세요.':'도착했습니다. 하역을 시작하세요.');}}}}
 const contact=ocean?.world?trafficAdvisory(ocean.world,state,spec.beam):null;
 if(autopilot&&contact?.danger){
  const emergency=contact.distance<contact.radius+spec.beam*.5+30;
  let detour=route.length>1;
  if(mission&&contact.kind!=='whale'&&ocean.world.time-trafficReplanAt>3){trafficReplanAt=ocean.world.time;const blockers=ocean.world.contacts.filter(c=>c.kind!=='whale'&&!c.site).map(c=>({...c,radius:Math.max(1,Math.min(c.radius+(c.kind==='towing'?110:20),Math.hypot(c.x-state.x,c.z-state.z)-spec.beam*.5-65))}));const candidate=planRoute(state,jobTarget(),[...routingObstacles(),...blockers],spec.beam*.5+50);if(candidate?.length){route=candidate;detour=true;}}
  // A low-speed game detour avoids the mutual stop of two courtesy controllers.
  // It is route assistance, not a COLREG manoeuvre decision.
  if(detour&&!emergency&&contact.kind!=='whale'){state.throttle=Math.min(state.throttle,.18);state.speed=Math.min(state.speed,2);}else{state.throttle=0;state.speed*=Math.exp(-dt*1.5);}
 }
 stepVessel(state,spec,{wind,windDirection:weatherState.direction,river:region.layout==='river',loadFactor:info.mass/(spec.mass*100)},dt,input);
 const groundHit=ocean?.groundHeight(state.x,state.z)>2;
 if(groundHit){if(ocean.groundHeight(before.x,before.z)>2){const berth=ports.reduce((a,p)=>Math.hypot(p.x-state.x,p.z-state.z)<Math.hypot(a.x-state.x,a.z-state.z)?p:a,ports[0]);before.x=berth.x;before.z=berth.z+46;state.anchored=true;syncAnchor();}state.x=before.x;state.z=before.z;state.speed=-Math.abs(state.speed)*.15;state.throttle=0;setAuto(false);if(t-lastCollision>3){lastCollision=t;toast('얕은 해안입니다. 후진하여 수로로 돌아오세요.');}}
 if(contact?.collision&&!state.anchored){state.x=before.x;state.z=before.z;state.speed*=.7;state.throttle=0;setAuto(false);if(t-lastCollision>3){lastCollision=t;toast(contact.kind==='whale'?'고래 가까이에서는 멈추고 거리를 확보하세요.':'접촉 위험! 레버를 중립에 놓고 진로를 바꾸세요.');}}
 const boundaryHit=applyBoundary(state,region,ocean?.obstacles||[]);
 if(watchTask&&ocean?.world){const result=stepWatch(watchTask,ocean.world,state,spec.beam,dt,wasAuto,!!contact?.collision||boundaryHit||groundHit);if(result.done){watchTask=null;ocean.world.trackedId=null;if(!result.cancelled){school.log.unshift(result);school.log=school.log.slice(0,12);save();toast(`${result.success?'안전 통과 기록!':'실습 복기'} ${result.reason}`);}}}
 if(boundaryHit&&t-lastCollision>3){lastCollision=t;setAuto(false);state.throttle=0;toast('해안 또는 장애물에 닿았습니다. 후진해서 수로로 이동하세요.');}
 }}
 if(state.capsized){if($('#rescue').hidden){closePanel();handling=null;}$('#rescue').hidden=false;setAuto(false);}
 if(!paused){ocean?.setWeather(weatherState,state);ocean?.update(state,t,dt,strength,cargo,handling);}audio.update(t,paused?0:state.speed,wind,spec.id==='yacht',paused||state.anchored?0:state.throttle,started&&!paused&&!document.hidden&&!$('#panel').open,ocean?.foam.impact||0);uiTimer+=dt;if(uiTimer>.12){uiTimer=0;updateUI();}
}
spawnAtPort();const restored=restoreTrip(saved.trip,region,spec);if(restored){state=restored.state;cargo=restored.cargo;mission=gameMode==='mission'?restored.mission:null;completedMission=restored.completed;}else if(gameMode==='mission')mission=localMission(region,state,spec);refresh();syncWelcomeModes();loadAtlas();requestAnimationFrame(animate);
