import * as T from 'three';
export class OpenTerrain{
 constructor(scene){this.scene=scene;this.token=0;this.mesh=null;this.data=null;}
 async load(region){const token=++this.token;this.dispose();if(region.layout!=='harbor')return;try{const r=await fetch(`${import.meta.env.BASE_URL}maps/terrain/${region.id}.json`);if(!r.ok)throw Error('terrain');const data=await r.json();if(token!==this.token)return;const n=data.size,geo=new T.PlaneGeometry(14000,14000,n-1,n-1);geo.rotateX(-Math.PI/2);const p=geo.attributes.position,colors=[];this.offset={x:(.5-data.origin[0])*14000,z:(.5-data.origin[1])*14000};this.data=data;
 for(let i=0;i<p.count;i++){const x=p.getX(i)+this.offset.x,z=p.getZ(i)+this.offset.z;let h=data.heights[i];const dx=Math.max(-1250-x,0,x-1350),dz=Math.max(-3300-z,0,z-650),blend=T.MathUtils.smoothstep(Math.hypot(dx,dz),0,700);h=h>0?T.MathUtils.lerp(-40,h*1.4,blend):-40;p.setY(i,h-2);const c=new T.Color(h<3?0x8c927d:h<45?0x697d63:h<220?0x405b49:0x546353);c.multiplyScalar(.87+.13*Math.sin(x*.029)*Math.cos(z*.024));colors.push(c.r,c.g,c.b);}
 geo.setAttribute('color',new T.Float32BufferAttribute(colors,3));geo.computeVertexNormals();const material=new T.MeshStandardMaterial({vertexColors:true,roughness:1});material.onBeforeCompile=shader=>{shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 terrainPosition;').replace('#include <begin_vertex>','#include <begin_vertex>\nterrainPosition=position;');shader.fragmentShader=shader.fragmentShader.replace('#include <common>',`#include <common>\nvarying vec3 terrainPosition;\nfloat terrainNoise(vec3 p){return fract(sin(dot(floor(p),vec3(12.9898,78.233,37.719)))*43758.5453);}`).replace('#include <color_fragment>',`#include <color_fragment>\ndiffuseColor.rgb*=.85+.3*terrainNoise(terrainPosition*.16);`);};this.mesh=new T.Mesh(geo,material);this.mesh.position.set(this.offset.x,0,this.offset.z);this.mesh.receiveShadow=true;this.mesh.userData.source='Mapzen / USGS / NOAA';this.scene.add(this.mesh);
 }catch(e){if(token===this.token)this.data=null;console.warn('Terrain unavailable:',region.id);}}
 heightAt(x,z){if(!this.mesh)return -10;const n=this.data.size,u=(x-this.offset.x+7000)/14000*(n-1),v=(z-this.offset.z+7000)/14000*(n-1);if(u<0||v<0||u>=n-1||v>=n-1)return -10;const p=this.mesh.geometry.attributes.position,i=Math.floor(u),j=Math.floor(v),a=u-i,b=v-j;return (p.getY(j*n+i)*(1-a)+p.getY(j*n+i+1)*a)*(1-b)+(p.getY((j+1)*n+i)*(1-a)+p.getY((j+1)*n+i+1)*a)*b;}
 dispose(){if(this.mesh){this.scene.remove(this.mesh);this.mesh.geometry.dispose();this.mesh.material.dispose();}this.mesh=null;this.data=null;}
}
